INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'beef tacos',
  'Beef Tacos',
  '[{"name":"corn tortillas","quantity":3,"unit":"pieces"},{"name":"ground beef","quantity":150,"unit":"g"},{"name":"taco seasoning","quantity":15,"unit":"g"},{"name":"cheddar cheese","quantity":40,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"},{"name":"tomato","quantity":40,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"salsa","quantity":40,"unit":"g"}]',
  1,
  480,
  28,
  35,
  26,
  4,
  4,
  820,
  '["milk"]',
  '["moderate_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken quesadilla',
  'Chicken Quesadilla',
  '[{"name":"flour tortilla","quantity":2,"unit":"large"},{"name":"grilled chicken","quantity":120,"unit":"g"},{"name":"cheddar cheese","quantity":80,"unit":"g"},{"name":"peppers","quantity":40,"unit":"g"},{"name":"onion","quantity":30,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"salsa","quantity":40,"unit":"g"}]',
  1,
  580,
  35,
  42,
  30,
  3,
  4,
  980,
  '["gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'caesar salad',
  'Caesar Salad',
  '[{"name":"romaine lettuce","quantity":200,"unit":"g"},{"name":"parmesan cheese","quantity":40,"unit":"g"},{"name":"croutons","quantity":40,"unit":"g"},{"name":"caesar dressing","quantity":60,"unit":"ml"},{"name":"lemon juice","quantity":15,"unit":"ml"},{"name":"anchovy paste","quantity":5,"unit":"g"}]',
  1,
  380,
  12,
  18,
  30,
  4,
  3,
  780,
  '["gluten","milk","egg","fish"]',
  '["low"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken caesar salad',
  'Chicken Caesar Salad',
  '[{"name":"romaine lettuce","quantity":200,"unit":"g"},{"name":"grilled chicken breast","quantity":150,"unit":"g"},{"name":"parmesan cheese","quantity":40,"unit":"g"},{"name":"croutons","quantity":40,"unit":"g"},{"name":"caesar dressing","quantity":60,"unit":"ml"},{"name":"lemon juice","quantity":15,"unit":"ml"}]',
  1,
  520,
  42,
  18,
  32,
  4,
  3,
  920,
  '["gluten","milk","egg","fish"]',
  '["low"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'greek salad',
  'Greek Salad',
  '[{"name":"cucumber","quantity":100,"unit":"g"},{"name":"tomato","quantity":120,"unit":"g"},{"name":"red onion","quantity":40,"unit":"g"},{"name":"kalamata olives","quantity":40,"unit":"g"},{"name":"feta cheese","quantity":60,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"oregano","quantity":2,"unit":"g"},{"name":"red wine vinegar","quantity":15,"unit":"ml"}]',
  1,
  320,
  8,
  12,
  28,
  3,
  6,
  680,
  '["milk"]',
  '["high_fructan","moderate_polyol"]',
  '["vegetarian","gluten-free","keto"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'cobb salad',
  'Cobb Salad',
  '[{"name":"mixed greens","quantity":150,"unit":"g"},{"name":"grilled chicken","quantity":120,"unit":"g"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"hard-boiled egg","quantity":2,"unit":"whole"},{"name":"avocado","quantity":80,"unit":"g"},{"name":"tomato","quantity":60,"unit":"g"},{"name":"blue cheese","quantity":40,"unit":"g"},{"name":"red wine vinaigrette","quantity":45,"unit":"ml"}]',
  1,
  580,
  38,
  14,
  42,
  6,
  4,
  920,
  '["egg","milk"]',
  '["moderate_polyol"]',
  '["gluten-free","keto"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'club sandwich',
  'Club Sandwich',
  '[{"name":"white bread","quantity":3,"unit":"slices"},{"name":"turkey breast","quantity":80,"unit":"g"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"},{"name":"tomato","quantity":40,"unit":"g"},{"name":"mayonnaise","quantity":30,"unit":"g"}]',
  1,
  520,
  28,
  38,
  28,
  3,
  5,
  1150,
  '["gluten","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'blt sandwich',
  'BLT Sandwich',
  '[{"name":"white bread","quantity":2,"unit":"slices"},{"name":"bacon","quantity":60,"unit":"g"},{"name":"lettuce","quantity":40,"unit":"g"},{"name":"tomato","quantity":60,"unit":"g"},{"name":"mayonnaise","quantity":30,"unit":"g"}]',
  1,
  450,
  18,
  28,
  30,
  2,
  4,
  980,
  '["gluten","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'grilled cheese sandwich',
  'Grilled Cheese Sandwich',
  '[{"name":"white bread","quantity":2,"unit":"slices"},{"name":"cheddar cheese","quantity":60,"unit":"g"},{"name":"butter","quantity":20,"unit":"g"}]',
  1,
  420,
  15,
  28,
  28,
  1,
  3,
  680,
  '["gluten","milk"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'eggs benedict',
  'Eggs Benedict',
  '[{"name":"English muffin","quantity":1,"unit":"whole"},{"name":"Canadian bacon","quantity":60,"unit":"g"},{"name":"poached egg","quantity":2,"unit":"whole"},{"name":"hollandaise sauce","quantity":60,"unit":"ml"}]',
  1,
  580,
  25,
  28,
  42,
  2,
  2,
  1150,
  '["gluten","egg","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pancakes',
  'Pancakes',
  '[{"name":"all-purpose flour","quantity":150,"unit":"g"},{"name":"milk","quantity":240,"unit":"ml"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"butter","quantity":30,"unit":"g"},{"name":"maple syrup","quantity":60,"unit":"ml"},{"name":"baking powder","quantity":5,"unit":"g"}]',
  1,
  520,
  12,
  82,
  16,
  2,
  35,
  580,
  '["gluten","milk","egg"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'french toast',
  'French Toast',
  '[{"name":"brioche bread","quantity":3,"unit":"slices"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"milk","quantity":60,"unit":"ml"},{"name":"cinnamon","quantity":2,"unit":"g"},{"name":"vanilla extract","quantity":5,"unit":"ml"},{"name":"butter","quantity":20,"unit":"g"},{"name":"maple syrup","quantity":45,"unit":"ml"},{"name":"powdered sugar","quantity":15,"unit":"g"}]',
  1,
  580,
  15,
  72,
  25,
  2,
  42,
  420,
  '["gluten","milk","egg"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'avocado toast',
  'Avocado Toast',
  '[{"name":"sourdough bread","quantity":2,"unit":"slices"},{"name":"avocado","quantity":150,"unit":"g"},{"name":"lemon juice","quantity":10,"unit":"ml"},{"name":"red pepper flakes","quantity":1,"unit":"g"},{"name":"sea salt","quantity":2,"unit":"g"},{"name":"olive oil","quantity":10,"unit":"ml"}]',
  1,
  380,
  8,
  35,
  24,
  10,
  2,
  520,
  '["gluten"]',
  '["moderate_polyol","high_fructan"]',
  '["vegan","dairy-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken noodle soup',
  'Chicken Noodle Soup',
  '[{"name":"chicken breast","quantity":150,"unit":"g"},{"name":"egg noodles","quantity":100,"unit":"g"},{"name":"chicken broth","quantity":500,"unit":"ml"},{"name":"carrot","quantity":60,"unit":"g"},{"name":"celery","quantity":40,"unit":"g"},{"name":"onion","quantity":50,"unit":"g"},{"name":"parsley","quantity":5,"unit":"g"}]',
  1,
  280,
  25,
  28,
  8,
  2,
  4,
  980,
  '["gluten","egg"]',
  '["high_fructan","moderate_polyol"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tomato soup',
  'Tomato Soup',
  '[{"name":"crushed tomatoes","quantity":400,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"vegetable broth","quantity":250,"unit":"ml"},{"name":"heavy cream","quantity":60,"unit":"ml"},{"name":"butter","quantity":20,"unit":"g"},{"name":"basil","quantity":10,"unit":"g"}]',
  1,
  220,
  4,
  18,
  15,
  4,
  10,
  680,
  '["milk"]',
  '["high_fructan","high_fructose"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'clam chowder',
  'Clam Chowder',
  '[{"name":"clams","quantity":200,"unit":"g"},{"name":"potato","quantity":200,"unit":"g"},{"name":"heavy cream","quantity":240,"unit":"ml"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"celery","quantity":40,"unit":"g"},{"name":"butter","quantity":30,"unit":"g"},{"name":"flour","quantity":20,"unit":"g"}]',
  1,
  420,
  18,
  32,
  26,
  2,
  4,
  850,
  '["shellfish","milk","gluten"]',
  '["high_fructan","high_lactose","moderate_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'fish and chips',
  'Fish and Chips',
  '[{"name":"cod fillet","quantity":200,"unit":"g"},{"name":"flour","quantity":100,"unit":"g"},{"name":"beer","quantity":120,"unit":"ml"},{"name":"potato","quantity":250,"unit":"g"},{"name":"vegetable oil","quantity":100,"unit":"ml"},{"name":"tartar sauce","quantity":40,"unit":"g"},{"name":"lemon wedge","quantity":1,"unit":"piece"}]',
  1,
  780,
  32,
  68,
  42,
  4,
  2,
  720,
  '["fish","gluten","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'grilled salmon',
  'Grilled Salmon',
  '[{"name":"salmon fillet","quantity":180,"unit":"g"},{"name":"olive oil","quantity":15,"unit":"ml"},{"name":"lemon","quantity":30,"unit":"g"},{"name":"dill","quantity":5,"unit":"g"},{"name":"garlic","quantity":2,"unit":"cloves"},{"name":"butter","quantity":15,"unit":"g"}]',
  1,
  380,
  36,
  2,
  25,
  0,
  1,
  280,
  '["fish","milk"]',
  '["high_fructan"]',
  '["gluten-free","keto","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'shrimp scampi',
  'Shrimp Scampi',
  '[{"name":"shrimp","quantity":300,"unit":"g"},{"name":"linguine","quantity":200,"unit":"g"},{"name":"butter","quantity":60,"unit":"g"},{"name":"garlic","quantity":5,"unit":"cloves"},{"name":"white wine","quantity":120,"unit":"ml"},{"name":"lemon juice","quantity":30,"unit":"ml"},{"name":"parsley","quantity":15,"unit":"g"},{"name":"red pepper flakes","quantity":2,"unit":"g"}]',
  1,
  620,
  35,
  58,
  28,
  3,
  3,
  720,
  '["shellfish","gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');
