INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'gambas al ajillo',
  'Gambas al Ajillo',
  '[{"name":"shrimp","quantity":400,"unit":"g"},{"name":"garlic","quantity":30,"unit":"g"},{"name":"olive oil","quantity":100,"unit":"ml"},{"name":"dried chili","quantity":5,"unit":"g"},{"name":"parsley","quantity":15,"unit":"g"}]',
  1,
  380,
  32,
  4,
  28,
  1,
  1,
  580,
  '["shellfish"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free","low-carb","keto-friendly"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'albondigas',
  'Albóndigas',
  '[{"name":"ground beef","quantity":300,"unit":"g"},{"name":"ground pork","quantity":200,"unit":"g"},{"name":"breadcrumbs","quantity":50,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"tomato sauce","quantity":300,"unit":"ml"},{"name":"onion","quantity":80,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"}]',
  1,
  420,
  32,
  18,
  26,
  2,
  6,
  620,
  '["wheat","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pan con tomate',
  'Pan con Tomate',
  '[{"name":"bread","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"}]',
  1,
  280,
  6,
  42,
  10,
  4,
  6,
  480,
  '["wheat"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pulpo a la gallega',
  'Pulpo a la Gallega',
  '[{"name":"octopus","quantity":500,"unit":"g"},{"name":"potatoes","quantity":300,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"},{"name":"paprika","quantity":10,"unit":"g"},{"name":"sea salt","quantity":5,"unit":"g"}]',
  1,
  320,
  36,
  24,
  12,
  3,
  2,
  620,
  '["mollusk"]',
  '[]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'calamares a la romana',
  'Calamares a la Romana',
  '[{"name":"squid","quantity":400,"unit":"g"},{"name":"flour","quantity":150,"unit":"g"},{"name":"vegetable oil","quantity":200,"unit":"ml"},{"name":"lemon","quantity":1,"unit":"whole"}]',
  1,
  380,
  26,
  32,
  18,
  1,
  1,
  520,
  '["wheat","mollusk"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'empanada gallega',
  'Empanada Gallega',
  '[{"name":"bread dough","quantity":400,"unit":"g"},{"name":"tuna","quantity":300,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"bell peppers","quantity":100,"unit":"g"},{"name":"tomato sauce","quantity":100,"unit":"ml"},{"name":"olive oil","quantity":40,"unit":"ml"}]',
  1,
  420,
  24,
  42,
  18,
  3,
  5,
  680,
  '["wheat","fish","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pintxos assorted',
  'Pintxos Assorted',
  '[{"name":"bread","quantity":100,"unit":"g"},{"name":"anchovies","quantity":40,"unit":"g"},{"name":"olives","quantity":40,"unit":"g"},{"name":"serrano ham","quantity":40,"unit":"g"},{"name":"manchego cheese","quantity":40,"unit":"g"}]',
  1,
  320,
  16,
  26,
  18,
  2,
  3,
  820,
  '["wheat","fish","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'gazpacho',
  'Gazpacho',
  '[{"name":"tomatoes","quantity":500,"unit":"g"},{"name":"cucumber","quantity":100,"unit":"g"},{"name":"bell peppers","quantity":80,"unit":"g"},{"name":"bread","quantity":50,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"},{"name":"sherry vinegar","quantity":30,"unit":"ml"}]',
  1,
  180,
  4,
  18,
  12,
  4,
  10,
  320,
  '["wheat"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'churros con chocolate',
  'Churros con Chocolate',
  '[{"name":"flour","quantity":250,"unit":"g"},{"name":"water","quantity":250,"unit":"ml"},{"name":"butter","quantity":30,"unit":"g"},{"name":"sugar","quantity":50,"unit":"g"},{"name":"vegetable oil","quantity":500,"unit":"ml"},{"name":"dark chocolate","quantity":150,"unit":"g"},{"name":"milk","quantity":200,"unit":"ml"}]',
  1,
  420,
  6,
  52,
  22,
  3,
  28,
  180,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'flan',
  'Flan',
  '[{"name":"eggs","quantity":4,"unit":"whole"},{"name":"milk","quantity":500,"unit":"ml"},{"name":"sugar","quantity":200,"unit":"g"},{"name":"vanilla","quantity":5,"unit":"ml"}]',
  1,
  280,
  8,
  42,
  10,
  0,
  40,
  120,
  '["milk","egg"]',
  '["high_lactose"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'crema catalana',
  'Crema Catalana',
  '[{"name":"milk","quantity":500,"unit":"ml"},{"name":"egg yolks","quantity":6,"unit":"whole"},{"name":"sugar","quantity":150,"unit":"g"},{"name":"cornstarch","quantity":30,"unit":"g"},{"name":"cinnamon stick","quantity":1,"unit":"piece"},{"name":"lemon zest","quantity":5,"unit":"g"}]',
  1,
  320,
  8,
  42,
  14,
  0,
  36,
  80,
  '["milk","egg"]',
  '["high_lactose"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'spaghetti and meatballs',
  'Spaghetti and Meatballs',
  '[{"name":"spaghetti","quantity":200,"unit":"g"},{"name":"ground beef","quantity":300,"unit":"g"},{"name":"breadcrumbs","quantity":30,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"parmesan cheese","quantity":30,"unit":"g"},{"name":"marinara sauce","quantity":250,"unit":"ml"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"olive oil","quantity":15,"unit":"ml"},{"name":"basil","quantity":5,"unit":"g"}]',
  1,
  650,
  35,
  70,
  25,
  4,
  8,
  850,
  '["gluten","egg","milk"]',
  '["high_fructan","moderate_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'penne arrabbiata',
  'Penne Arrabbiata',
  '[{"name":"penne pasta","quantity":200,"unit":"g"},{"name":"crushed tomatoes","quantity":400,"unit":"g"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"red chili flakes","quantity":5,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"parsley","quantity":10,"unit":"g"}]',
  1,
  420,
  12,
  72,
  10,
  4,
  6,
  320,
  '["gluten"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'classic cheeseburger',
  'Classic Cheeseburger',
  '[{"name":"ground beef patty","quantity":150,"unit":"g"},{"name":"hamburger bun","quantity":1,"unit":"whole"},{"name":"cheddar cheese","quantity":30,"unit":"g"},{"name":"lettuce","quantity":20,"unit":"g"},{"name":"tomato","quantity":30,"unit":"g"},{"name":"onion","quantity":20,"unit":"g"},{"name":"pickles","quantity":15,"unit":"g"},{"name":"ketchup","quantity":15,"unit":"ml"},{"name":"mustard","quantity":10,"unit":"ml"}]',
  1,
  550,
  32,
  35,
  32,
  2,
  8,
  850,
  '["gluten","milk"]',
  '["high_fructan","moderate_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bacon cheeseburger',
  'Bacon Cheeseburger',
  '[{"name":"ground beef patty","quantity":150,"unit":"g"},{"name":"hamburger bun","quantity":1,"unit":"whole"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"cheddar cheese","quantity":30,"unit":"g"},{"name":"lettuce","quantity":20,"unit":"g"},{"name":"tomato","quantity":30,"unit":"g"},{"name":"onion","quantity":20,"unit":"g"}]',
  1,
  680,
  38,
  35,
  42,
  2,
  6,
  1150,
  '["gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pad thai',
  'Pad Thai',
  '[{"name":"rice noodles","quantity":200,"unit":"g"},{"name":"shrimp","quantity":150,"unit":"g"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"tofu","quantity":100,"unit":"g"},{"name":"bean sprouts","quantity":80,"unit":"g"},{"name":"peanuts","quantity":30,"unit":"g"},{"name":"green onion","quantity":20,"unit":"g"},{"name":"fish sauce","quantity":30,"unit":"ml"},{"name":"tamarind paste","quantity":20,"unit":"g"},{"name":"palm sugar","quantity":15,"unit":"g"},{"name":"lime","quantity":1,"unit":"wedge"}]',
  1,
  580,
  28,
  65,
  22,
  3,
  12,
  1200,
  '["shellfish","peanut","egg","soy","fish"]',
  '["high_fructan","high_gos"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken burrito',
  'Chicken Burrito',
  '[{"name":"flour tortilla","quantity":1,"unit":"large"},{"name":"grilled chicken","quantity":150,"unit":"g"},{"name":"rice","quantity":100,"unit":"g"},{"name":"black beans","quantity":80,"unit":"g"},{"name":"cheddar cheese","quantity":40,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"guacamole","quantity":50,"unit":"g"},{"name":"salsa","quantity":50,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"}]',
  1,
  720,
  42,
  68,
  28,
  8,
  4,
  1250,
  '["gluten","milk"]',
  '["high_gos","moderate_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'beef tacos',
  'Beef Tacos',
  '[{"name":"corn tortillas","quantity":3,"unit":"pieces"},{"name":"ground beef","quantity":150,"unit":"g"},{"name":"taco seasoning","quantity":15,"unit":"g"},{"name":"cheddar cheese","quantity":40,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"},{"name":"tomato","quantity":40,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"salsa","quantity":40,"unit":"g"}]',
  1,
  480,
  28,
  35,
  26,
  4,
  4,
  820,
  '["milk"]',
  '["moderate_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken quesadilla',
  'Chicken Quesadilla',
  '[{"name":"flour tortilla","quantity":2,"unit":"large"},{"name":"grilled chicken","quantity":120,"unit":"g"},{"name":"cheddar cheese","quantity":80,"unit":"g"},{"name":"peppers","quantity":40,"unit":"g"},{"name":"onion","quantity":30,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"salsa","quantity":40,"unit":"g"}]',
  1,
  580,
  35,
  42,
  30,
  3,
  4,
  980,
  '["gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'caesar salad',
  'Caesar Salad',
  '[{"name":"romaine lettuce","quantity":200,"unit":"g"},{"name":"parmesan cheese","quantity":40,"unit":"g"},{"name":"croutons","quantity":40,"unit":"g"},{"name":"caesar dressing","quantity":60,"unit":"ml"},{"name":"lemon juice","quantity":15,"unit":"ml"},{"name":"anchovy paste","quantity":5,"unit":"g"}]',
  1,
  380,
  12,
  18,
  30,
  4,
  3,
  780,
  '["gluten","milk","egg","fish"]',
  '["low"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken caesar salad',
  'Chicken Caesar Salad',
  '[{"name":"romaine lettuce","quantity":200,"unit":"g"},{"name":"grilled chicken breast","quantity":150,"unit":"g"},{"name":"parmesan cheese","quantity":40,"unit":"g"},{"name":"croutons","quantity":40,"unit":"g"},{"name":"caesar dressing","quantity":60,"unit":"ml"},{"name":"lemon juice","quantity":15,"unit":"ml"}]',
  1,
  520,
  42,
  18,
  32,
  4,
  3,
  920,
  '["gluten","milk","egg","fish"]',
  '["low"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'greek salad',
  'Greek Salad',
  '[{"name":"cucumber","quantity":100,"unit":"g"},{"name":"tomato","quantity":120,"unit":"g"},{"name":"red onion","quantity":40,"unit":"g"},{"name":"kalamata olives","quantity":40,"unit":"g"},{"name":"feta cheese","quantity":60,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"oregano","quantity":2,"unit":"g"},{"name":"red wine vinegar","quantity":15,"unit":"ml"}]',
  1,
  320,
  8,
  12,
  28,
  3,
  6,
  680,
  '["milk"]',
  '["high_fructan","moderate_polyol"]',
  '["vegetarian","gluten-free","keto"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'cobb salad',
  'Cobb Salad',
  '[{"name":"mixed greens","quantity":150,"unit":"g"},{"name":"grilled chicken","quantity":120,"unit":"g"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"hard-boiled egg","quantity":2,"unit":"whole"},{"name":"avocado","quantity":80,"unit":"g"},{"name":"tomato","quantity":60,"unit":"g"},{"name":"blue cheese","quantity":40,"unit":"g"},{"name":"red wine vinaigrette","quantity":45,"unit":"ml"}]',
  1,
  580,
  38,
  14,
  42,
  6,
  4,
  920,
  '["egg","milk"]',
  '["moderate_polyol"]',
  '["gluten-free","keto"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'club sandwich',
  'Club Sandwich',
  '[{"name":"white bread","quantity":3,"unit":"slices"},{"name":"turkey breast","quantity":80,"unit":"g"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"},{"name":"tomato","quantity":40,"unit":"g"},{"name":"mayonnaise","quantity":30,"unit":"g"}]',
  1,
  520,
  28,
  38,
  28,
  3,
  5,
  1150,
  '["gluten","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'blt sandwich',
  'BLT Sandwich',
  '[{"name":"white bread","quantity":2,"unit":"slices"},{"name":"bacon","quantity":60,"unit":"g"},{"name":"lettuce","quantity":40,"unit":"g"},{"name":"tomato","quantity":60,"unit":"g"},{"name":"mayonnaise","quantity":30,"unit":"g"}]',
  1,
  450,
  18,
  28,
  30,
  2,
  4,
  980,
  '["gluten","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'grilled cheese sandwich',
  'Grilled Cheese Sandwich',
  '[{"name":"white bread","quantity":2,"unit":"slices"},{"name":"cheddar cheese","quantity":60,"unit":"g"},{"name":"butter","quantity":20,"unit":"g"}]',
  1,
  420,
  15,
  28,
  28,
  1,
  3,
  680,
  '["gluten","milk"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'eggs benedict',
  'Eggs Benedict',
  '[{"name":"English muffin","quantity":1,"unit":"whole"},{"name":"Canadian bacon","quantity":60,"unit":"g"},{"name":"poached egg","quantity":2,"unit":"whole"},{"name":"hollandaise sauce","quantity":60,"unit":"ml"}]',
  1,
  580,
  25,
  28,
  42,
  2,
  2,
  1150,
  '["gluten","egg","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pancakes',
  'Pancakes',
  '[{"name":"all-purpose flour","quantity":150,"unit":"g"},{"name":"milk","quantity":240,"unit":"ml"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"butter","quantity":30,"unit":"g"},{"name":"maple syrup","quantity":60,"unit":"ml"},{"name":"baking powder","quantity":5,"unit":"g"}]',
  1,
  520,
  12,
  82,
  16,
  2,
  35,
  580,
  '["gluten","milk","egg"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'french toast',
  'French Toast',
  '[{"name":"brioche bread","quantity":3,"unit":"slices"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"milk","quantity":60,"unit":"ml"},{"name":"cinnamon","quantity":2,"unit":"g"},{"name":"vanilla extract","quantity":5,"unit":"ml"},{"name":"butter","quantity":20,"unit":"g"},{"name":"maple syrup","quantity":45,"unit":"ml"},{"name":"powdered sugar","quantity":15,"unit":"g"}]',
  1,
  580,
  15,
  72,
  25,
  2,
  42,
  420,
  '["gluten","milk","egg"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'avocado toast',
  'Avocado Toast',
  '[{"name":"sourdough bread","quantity":2,"unit":"slices"},{"name":"avocado","quantity":150,"unit":"g"},{"name":"lemon juice","quantity":10,"unit":"ml"},{"name":"red pepper flakes","quantity":1,"unit":"g"},{"name":"sea salt","quantity":2,"unit":"g"},{"name":"olive oil","quantity":10,"unit":"ml"}]',
  1,
  380,
  8,
  35,
  24,
  10,
  2,
  520,
  '["gluten"]',
  '["moderate_polyol","high_fructan"]',
  '["vegan","dairy-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken noodle soup',
  'Chicken Noodle Soup',
  '[{"name":"chicken breast","quantity":150,"unit":"g"},{"name":"egg noodles","quantity":100,"unit":"g"},{"name":"chicken broth","quantity":500,"unit":"ml"},{"name":"carrot","quantity":60,"unit":"g"},{"name":"celery","quantity":40,"unit":"g"},{"name":"onion","quantity":50,"unit":"g"},{"name":"parsley","quantity":5,"unit":"g"}]',
  1,
  280,
  25,
  28,
  8,
  2,
  4,
  980,
  '["gluten","egg"]',
  '["high_fructan","moderate_polyol"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tomato soup',
  'Tomato Soup',
  '[{"name":"crushed tomatoes","quantity":400,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"vegetable broth","quantity":250,"unit":"ml"},{"name":"heavy cream","quantity":60,"unit":"ml"},{"name":"butter","quantity":20,"unit":"g"},{"name":"basil","quantity":10,"unit":"g"}]',
  1,
  220,
  4,
  18,
  15,
  4,
  10,
  680,
  '["milk"]',
  '["high_fructan","high_fructose"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'clam chowder',
  'Clam Chowder',
  '[{"name":"clams","quantity":200,"unit":"g"},{"name":"potato","quantity":200,"unit":"g"},{"name":"heavy cream","quantity":240,"unit":"ml"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"celery","quantity":40,"unit":"g"},{"name":"butter","quantity":30,"unit":"g"},{"name":"flour","quantity":20,"unit":"g"}]',
  1,
  420,
  18,
  32,
  26,
  2,
  4,
  850,
  '["shellfish","milk","gluten"]',
  '["high_fructan","high_lactose","moderate_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'fish and chips',
  'Fish and Chips',
  '[{"name":"cod fillet","quantity":200,"unit":"g"},{"name":"flour","quantity":100,"unit":"g"},{"name":"beer","quantity":120,"unit":"ml"},{"name":"potato","quantity":250,"unit":"g"},{"name":"vegetable oil","quantity":100,"unit":"ml"},{"name":"tartar sauce","quantity":40,"unit":"g"},{"name":"lemon wedge","quantity":1,"unit":"piece"}]',
  1,
  780,
  32,
  68,
  42,
  4,
  2,
  720,
  '["fish","gluten","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'grilled salmon',
  'Grilled Salmon',
  '[{"name":"salmon fillet","quantity":180,"unit":"g"},{"name":"olive oil","quantity":15,"unit":"ml"},{"name":"lemon","quantity":30,"unit":"g"},{"name":"dill","quantity":5,"unit":"g"},{"name":"garlic","quantity":2,"unit":"cloves"},{"name":"butter","quantity":15,"unit":"g"}]',
  1,
  380,
  36,
  2,
  25,
  0,
  1,
  280,
  '["fish","milk"]',
  '["high_fructan"]',
  '["gluten-free","keto","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'shrimp scampi',
  'Shrimp Scampi',
  '[{"name":"shrimp","quantity":300,"unit":"g"},{"name":"linguine","quantity":200,"unit":"g"},{"name":"butter","quantity":60,"unit":"g"},{"name":"garlic","quantity":5,"unit":"cloves"},{"name":"white wine","quantity":120,"unit":"ml"},{"name":"lemon juice","quantity":30,"unit":"ml"},{"name":"parsley","quantity":15,"unit":"g"},{"name":"red pepper flakes","quantity":2,"unit":"g"}]',
  1,
  620,
  35,
  58,
  28,
  3,
  3,
  720,
  '["shellfish","gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'cheeseburger',
  'Cheeseburger',
  '[{"name":"ground beef","quantity":200,"unit":"g"},{"name":"cheddar cheese","quantity":50,"unit":"g"},{"name":"burger bun","quantity":1,"unit":"piece"},{"name":"lettuce","quantity":30,"unit":"g"},{"name":"tomato","quantity":50,"unit":"g"},{"name":"onion","quantity":30,"unit":"g"},{"name":"pickles","quantity":20,"unit":"g"},{"name":"ketchup","quantity":20,"unit":"ml"},{"name":"mustard","quantity":10,"unit":"ml"}]',
  1,
  650,
  35,
  42,
  38,
  2,
  10,
  980,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'philly cheesesteak',
  'Philly Cheesesteak',
  '[{"name":"ribeye steak","quantity":250,"unit":"g"},{"name":"provolone cheese","quantity":60,"unit":"g"},{"name":"hoagie roll","quantity":1,"unit":"piece"},{"name":"onion","quantity":80,"unit":"g"},{"name":"bell peppers","quantity":60,"unit":"g"},{"name":"mushrooms","quantity":50,"unit":"g"}]',
  1,
  720,
  42,
  48,
  40,
  3,
  6,
  1100,
  '["wheat","milk"]',
  '["high_fructan","high_polyol","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pulled pork sandwich',
  'Pulled Pork Sandwich',
  '[{"name":"pork shoulder","quantity":200,"unit":"g"},{"name":"brioche bun","quantity":1,"unit":"piece"},{"name":"bbq sauce","quantity":60,"unit":"ml"},{"name":"coleslaw","quantity":80,"unit":"g"},{"name":"apple cider vinegar","quantity":15,"unit":"ml"}]',
  1,
  580,
  32,
  52,
  26,
  2,
  22,
  890,
  '["wheat","egg"]',
  '["high_fructan","high_fructose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'hot dog',
  'Hot Dog',
  '[{"name":"beef frankfurter","quantity":100,"unit":"g"},{"name":"hot dog bun","quantity":1,"unit":"piece"},{"name":"mustard","quantity":15,"unit":"ml"},{"name":"ketchup","quantity":15,"unit":"ml"},{"name":"relish","quantity":15,"unit":"g"},{"name":"onion","quantity":20,"unit":"g"}]',
  1,
  380,
  14,
  32,
  22,
  1,
  8,
  920,
  '["wheat"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'lobster roll',
  'Lobster Roll',
  '[{"name":"lobster meat","quantity":150,"unit":"g"},{"name":"split-top bun","quantity":1,"unit":"piece"},{"name":"mayonnaise","quantity":30,"unit":"g"},{"name":"butter","quantity":20,"unit":"g"},{"name":"celery","quantity":20,"unit":"g"},{"name":"lemon juice","quantity":10,"unit":"ml"},{"name":"chives","quantity":5,"unit":"g"}]',
  1,
  420,
  28,
  28,
  24,
  1,
  4,
  680,
  '["shellfish","wheat","egg","milk"]',
  '["high_fructan","high_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'fried chicken',
  'Fried Chicken',
  '[{"name":"chicken pieces","quantity":400,"unit":"g"},{"name":"flour","quantity":100,"unit":"g"},{"name":"buttermilk","quantity":250,"unit":"ml"},{"name":"paprika","quantity":8,"unit":"g"},{"name":"garlic powder","quantity":5,"unit":"g"},{"name":"cayenne pepper","quantity":2,"unit":"g"},{"name":"vegetable oil","quantity":500,"unit":"ml"}]',
  1,
  680,
  42,
  32,
  42,
  1,
  2,
  780,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bbq ribs',
  'BBQ Ribs',
  '[{"name":"pork ribs","quantity":500,"unit":"g"},{"name":"bbq sauce","quantity":120,"unit":"ml"},{"name":"brown sugar","quantity":30,"unit":"g"},{"name":"paprika","quantity":10,"unit":"g"},{"name":"garlic powder","quantity":5,"unit":"g"},{"name":"onion powder","quantity":5,"unit":"g"}]',
  1,
  720,
  45,
  28,
  48,
  1,
  24,
  1020,
  '[]',
  '["high_fructan","high_fructose"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'brisket',
  'Brisket',
  '[{"name":"beef brisket","quantity":400,"unit":"g"},{"name":"salt","quantity":10,"unit":"g"},{"name":"black pepper","quantity":8,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"}]',
  1,
  520,
  48,
  4,
  34,
  1,
  2,
  680,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free","keto","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'buffalo wings',
  'Buffalo Wings',
  '[{"name":"chicken wings","quantity":500,"unit":"g"},{"name":"hot sauce","quantity":80,"unit":"ml"},{"name":"butter","quantity":60,"unit":"g"},{"name":"garlic powder","quantity":3,"unit":"g"},{"name":"celery sticks","quantity":60,"unit":"g"},{"name":"blue cheese dressing","quantity":60,"unit":"ml"}]',
  1,
  580,
  38,
  8,
  44,
  1,
  2,
  1450,
  '["milk"]',
  '["high_lactose","high_polyol"]',
  '["gluten-free","keto","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'mac and cheese',
  'Mac and Cheese',
  '[{"name":"elbow macaroni","quantity":250,"unit":"g"},{"name":"cheddar cheese","quantity":200,"unit":"g"},{"name":"milk","quantity":250,"unit":"ml"},{"name":"butter","quantity":40,"unit":"g"},{"name":"flour","quantity":30,"unit":"g"},{"name":"mustard powder","quantity":3,"unit":"g"}]',
  1,
  580,
  22,
  58,
  30,
  2,
  6,
  720,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'meatloaf',
  'Meatloaf',
  '[{"name":"ground beef","quantity":500,"unit":"g"},{"name":"breadcrumbs","quantity":80,"unit":"g"},{"name":"egg","quantity":2,"unit":"pieces"},{"name":"onion","quantity":80,"unit":"g"},{"name":"ketchup","quantity":60,"unit":"ml"},{"name":"worcestershire sauce","quantity":15,"unit":"ml"},{"name":"garlic","quantity":10,"unit":"g"}]',
  1,
  420,
  32,
  22,
  24,
  1,
  8,
  680,
  '["wheat","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken pot pie',
  'Chicken Pot Pie',
  '[{"name":"chicken breast","quantity":300,"unit":"g"},{"name":"pie crust","quantity":250,"unit":"g"},{"name":"peas","quantity":80,"unit":"g"},{"name":"carrots","quantity":80,"unit":"g"},{"name":"celery","quantity":50,"unit":"g"},{"name":"cream","quantity":200,"unit":"ml"},{"name":"chicken broth","quantity":200,"unit":"ml"},{"name":"flour","quantity":30,"unit":"g"}]',
  1,
  520,
  28,
  42,
  28,
  4,
  6,
  780,
  '["wheat","milk"]',
  '["high_fructan","high_lactose","high_gos"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'ny style pizza',
  'NY-Style Pizza',
  '[{"name":"pizza dough","quantity":300,"unit":"g"},{"name":"mozzarella cheese","quantity":200,"unit":"g"},{"name":"tomato sauce","quantity":120,"unit":"ml"},{"name":"olive oil","quantity":15,"unit":"ml"},{"name":"oregano","quantity":3,"unit":"g"},{"name":"garlic","quantity":5,"unit":"g"}]',
  1,
  680,
  28,
  72,
  32,
  4,
  8,
  1100,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'clam chowder',
  'Clam Chowder',
  '[{"name":"clams","quantity":300,"unit":"g"},{"name":"potatoes","quantity":200,"unit":"g"},{"name":"heavy cream","quantity":250,"unit":"ml"},{"name":"bacon","quantity":60,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"celery","quantity":50,"unit":"g"},{"name":"flour","quantity":30,"unit":"g"},{"name":"thyme","quantity":3,"unit":"g"}]',
  1,
  480,
  24,
  32,
  30,
  2,
  4,
  920,
  '["shellfish","wheat","milk"]',
  '["high_fructan","high_lactose","high_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');
