INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'misir wat',
  'Misir Wat',
  '[{"name":"red lentils","quantity":300,"unit":"g"},{"name":"berbere spice","quantity":30,"unit":"g"},{"name":"onion","quantity":200,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"niter kibbeh","quantity":40,"unit":"g"}]',
  1,
  340,
  18,
  48,
  10,
  16,
  6,
  380,
  '["milk"]',
  '["high_gos","high_fructan"]',
  '["gluten-free","vegetarian","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'gomen',
  'Gomen',
  '[{"name":"collard greens","quantity":500,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"vegetable oil","quantity":40,"unit":"ml"}]',
  1,
  180,
  6,
  18,
  10,
  8,
  4,
  280,
  '[]',
  '["high_fructan"]',
  '["vegan","gluten-free","dairy-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'alicha wot',
  'Alicha Wot',
  '[{"name":"chicken","quantity":500,"unit":"g"},{"name":"onion","quantity":200,"unit":"g"},{"name":"turmeric","quantity":10,"unit":"g"},{"name":"ginger","quantity":15,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"niter kibbeh","quantity":40,"unit":"g"}]',
  1,
  380,
  38,
  12,
  20,
  2,
  6,
  480,
  '["milk"]',
  '["high_fructan"]',
  '["gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'berbere chicken',
  'Berbere Chicken',
  '[{"name":"chicken thighs","quantity":600,"unit":"g"},{"name":"berbere spice","quantity":40,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"garlic","quantity":20,"unit":"g"},{"name":"niter kibbeh","quantity":50,"unit":"g"},{"name":"tomato paste","quantity":40,"unit":"g"}]',
  1,
  420,
  40,
  14,
  24,
  3,
  6,
  580,
  '["milk"]',
  '["high_fructan"]',
  '["gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'ethiopian lentil stew',
  'Ethiopian Lentil Stew',
  '[{"name":"brown lentils","quantity":300,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":150,"unit":"g"},{"name":"berbere spice","quantity":20,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"vegetable oil","quantity":30,"unit":"ml"}]',
  1,
  320,
  18,
  46,
  8,
  16,
  6,
  380,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","gluten-free","dairy-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'ethiopian chickpea stew',
  'Ethiopian Chickpea Stew',
  '[{"name":"chickpeas","quantity":400,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"berbere spice","quantity":25,"unit":"g"},{"name":"tomato paste","quantity":40,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"vegetable oil","quantity":30,"unit":"ml"}]',
  1,
  340,
  16,
  48,
  10,
  12,
  8,
  420,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","gluten-free","dairy-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'siga wat',
  'Siga Wat',
  '[{"name":"beef chunks","quantity":600,"unit":"g"},{"name":"berbere spice","quantity":50,"unit":"g"},{"name":"onion","quantity":300,"unit":"g"},{"name":"niter kibbeh","quantity":60,"unit":"g"},{"name":"garlic","quantity":20,"unit":"g"},{"name":"ginger","quantity":15,"unit":"g"}]',
  1,
  480,
  45,
  16,
  28,
  4,
  8,
  620,
  '["milk"]',
  '["high_fructan"]',
  '["gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'key wat',
  'Key Wat',
  '[{"name":"beef","quantity":500,"unit":"g"},{"name":"berbere spice","quantity":45,"unit":"g"},{"name":"onion","quantity":250,"unit":"g"},{"name":"niter kibbeh","quantity":50,"unit":"g"},{"name":"garlic","quantity":20,"unit":"g"},{"name":"cardamom","quantity":3,"unit":"g"}]',
  1,
  460,
  42,
  18,
  26,
  4,
  8,
  580,
  '["milk"]',
  '["high_fructan"]',
  '["gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'atakilt wat',
  'Atakilt Wat',
  '[{"name":"cabbage","quantity":300,"unit":"g"},{"name":"carrots","quantity":150,"unit":"g"},{"name":"potatoes","quantity":200,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"turmeric","quantity":8,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"vegetable oil","quantity":40,"unit":"ml"}]',
  1,
  240,
  5,
  36,
  10,
  8,
  8,
  320,
  '[]',
  '["high_fructan"]',
  '["vegan","gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'firfir',
  'Firfir',
  '[{"name":"injera","quantity":200,"unit":"g"},{"name":"berbere spice","quantity":20,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"niter kibbeh","quantity":40,"unit":"g"},{"name":"tomatoes","quantity":80,"unit":"g"}]',
  1,
  320,
  8,
  42,
  14,
  6,
  6,
  420,
  '["milk"]',
  '["high_fructan"]',
  '["gluten-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'ethiopian sambusa',
  'Ethiopian Sambusa',
  '[{"name":"pastry dough","quantity":300,"unit":"g"},{"name":"ground beef","quantity":250,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"jalapeño","quantity":30,"unit":"g"},{"name":"berbere spice","quantity":10,"unit":"g"},{"name":"vegetable oil","quantity":200,"unit":"ml"}]',
  1,
  320,
  16,
  28,
  18,
  2,
  2,
  420,
  '["wheat"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'dulet',
  'Dulet',
  '[{"name":"lamb liver","quantity":200,"unit":"g"},{"name":"lamb tripe","quantity":150,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"jalapeño","quantity":40,"unit":"g"},{"name":"niter kibbeh","quantity":40,"unit":"g"},{"name":"cardamom","quantity":3,"unit":"g"}]',
  1,
  380,
  32,
  12,
  24,
  2,
  4,
  520,
  '["milk"]',
  '["high_fructan"]',
  '["gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'ethiopian coffee ceremony',
  'Ethiopian Coffee Ceremony',
  '[{"name":"coffee beans","quantity":100,"unit":"g"},{"name":"water","quantity":500,"unit":"ml"},{"name":"sugar","quantity":30,"unit":"g"}]',
  1,
  30,
  0,
  8,
  0,
  0,
  8,
  2,
  '[]',
  '[]',
  '["vegan","gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tej honey wine',
  'Tej (Honey Wine)',
  '[{"name":"honey","quantity":500,"unit":"g"},{"name":"water","quantity":2000,"unit":"ml"},{"name":"gesho leaves","quantity":50,"unit":"g"}]',
  1,
  180,
  0,
  42,
  0,
  0,
  40,
  5,
  '[]',
  '["high_fructose"]',
  '["gluten-free","dairy-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'ethiopian spiced tea',
  'Ethiopian Spiced Tea',
  '[{"name":"black tea","quantity":10,"unit":"g"},{"name":"cinnamon","quantity":3,"unit":"g"},{"name":"cloves","quantity":2,"unit":"g"},{"name":"cardamom","quantity":2,"unit":"g"},{"name":"sugar","quantity":20,"unit":"g"},{"name":"milk","quantity":100,"unit":"ml"}]',
  1,
  80,
  2,
  16,
  2,
  0,
  14,
  40,
  '["milk"]',
  '["high_lactose"]',
  '["gluten-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken tagine with preserved lemon',
  'Chicken Tagine with Preserved Lemon',
  '[{"name":"chicken pieces","quantity":800,"unit":"g"},{"name":"preserved lemons","quantity":60,"unit":"g"},{"name":"olives","quantity":100,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"saffron","quantity":1,"unit":"g"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"cilantro","quantity":20,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"}]',
  1,
  420,
  42,
  12,
  24,
  3,
  4,
  680,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'lamb tagine',
  'Lamb Tagine',
  '[{"name":"lamb shoulder","quantity":600,"unit":"g"},{"name":"dried apricots","quantity":100,"unit":"g"},{"name":"almonds","quantity":60,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"honey","quantity":40,"unit":"g"},{"name":"cinnamon","quantity":5,"unit":"g"},{"name":"ras el hanout","quantity":15,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"}]',
  1,
  520,
  38,
  32,
  28,
  4,
  24,
  520,
  '["tree_nut"]',
  '["high_fructan","high_fructose","high_polyol"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'moroccan couscous',
  'Moroccan Couscous',
  '[{"name":"couscous","quantity":300,"unit":"g"},{"name":"lamb","quantity":300,"unit":"g"},{"name":"chickpeas","quantity":150,"unit":"g"},{"name":"carrots","quantity":100,"unit":"g"},{"name":"zucchini","quantity":100,"unit":"g"},{"name":"turnips","quantity":80,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"raisins","quantity":40,"unit":"g"},{"name":"harissa","quantity":15,"unit":"g"}]',
  1,
  580,
  32,
  68,
  20,
  8,
  14,
  620,
  '["wheat"]',
  '["high_fructan","high_gos","high_fructose"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'harira soup',
  'Harira Soup',
  '[{"name":"lamb","quantity":200,"unit":"g"},{"name":"chickpeas","quantity":150,"unit":"g"},{"name":"lentils","quantity":100,"unit":"g"},{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"celery","quantity":50,"unit":"g"},{"name":"flour","quantity":30,"unit":"g"},{"name":"cilantro","quantity":20,"unit":"g"},{"name":"ginger","quantity":10,"unit":"g"}]',
  1,
  380,
  24,
  42,
  14,
  10,
  8,
  580,
  '["wheat"]',
  '["high_gos","high_fructan","high_polyol"]',
  '["dairy-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pastilla bastilla',
  'Pastilla (Bastilla)',
  '[{"name":"pigeon or chicken","quantity":500,"unit":"g"},{"name":"phyllo dough","quantity":300,"unit":"g"},{"name":"almonds","quantity":150,"unit":"g"},{"name":"eggs","quantity":6,"unit":"pieces"},{"name":"onion","quantity":150,"unit":"g"},{"name":"butter","quantity":100,"unit":"g"},{"name":"cinnamon","quantity":8,"unit":"g"},{"name":"powdered sugar","quantity":40,"unit":"g"}]',
  1,
  520,
  32,
  38,
  30,
  3,
  12,
  480,
  '["wheat","egg","milk","tree_nut"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kefta meatballs',
  'Kefta Meatballs',
  '[{"name":"ground beef","quantity":400,"unit":"g"},{"name":"ground lamb","quantity":200,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"parsley","quantity":30,"unit":"g"},{"name":"cumin","quantity":8,"unit":"g"},{"name":"paprika","quantity":5,"unit":"g"},{"name":"cinnamon","quantity":3,"unit":"g"}]',
  1,
  380,
  32,
  6,
  26,
  1,
  2,
  520,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kefta tagine with eggs',
  'Kefta Tagine with Eggs',
  '[{"name":"ground beef","quantity":400,"unit":"g"},{"name":"eggs","quantity":4,"unit":"pieces"},{"name":"tomatoes","quantity":300,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"cumin","quantity":8,"unit":"g"},{"name":"paprika","quantity":5,"unit":"g"},{"name":"parsley","quantity":20,"unit":"g"}]',
  1,
  420,
  36,
  12,
  26,
  3,
  6,
  580,
  '["egg"]',
  '["high_fructan"]',
  '["gluten-free","dairy-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'mechoui roast lamb',
  'Mechoui (Roast Lamb)',
  '[{"name":"whole lamb leg","quantity":2000,"unit":"g"},{"name":"cumin","quantity":20,"unit":"g"},{"name":"coriander","quantity":15,"unit":"g"},{"name":"garlic","quantity":30,"unit":"g"},{"name":"butter","quantity":100,"unit":"g"},{"name":"salt","quantity":20,"unit":"g"}]',
  1,
  480,
  45,
  2,
  32,
  0,
  0,
  680,
  '["milk"]',
  '["high_fructan"]',
  '["gluten-free","keto","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'merguez',
  'Merguez',
  '[{"name":"lamb","quantity":400,"unit":"g"},{"name":"beef","quantity":200,"unit":"g"},{"name":"harissa","quantity":30,"unit":"g"},{"name":"cumin","quantity":10,"unit":"g"},{"name":"fennel seeds","quantity":5,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"sausage casing","quantity":100,"unit":"g"}]',
  1,
  380,
  28,
  4,
  28,
  1,
  1,
  780,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free","keto","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'zaalouk',
  'Zaalouk',
  '[{"name":"eggplant","quantity":400,"unit":"g"},{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"paprika","quantity":5,"unit":"g"},{"name":"cilantro","quantity":15,"unit":"g"}]',
  1,
  180,
  4,
  18,
  12,
  6,
  8,
  280,
  '[]',
  '["high_fructan"]',
  '["vegan","gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'taktouka',
  'Taktouka',
  '[{"name":"bell peppers","quantity":300,"unit":"g"},{"name":"tomatoes","quantity":300,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"paprika","quantity":5,"unit":"g"}]',
  1,
  160,
  3,
  16,
  10,
  4,
  10,
  240,
  '[]',
  '["high_fructan"]',
  '["vegan","gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'briouats',
  'Briouats',
  '[{"name":"phyllo dough","quantity":200,"unit":"g"},{"name":"ground beef","quantity":200,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"almonds","quantity":40,"unit":"g"},{"name":"cinnamon","quantity":3,"unit":"g"},{"name":"egg","quantity":1,"unit":"piece"},{"name":"vegetable oil","quantity":200,"unit":"ml"}]',
  1,
  280,
  14,
  22,
  16,
  2,
  2,
  320,
  '["wheat","egg","tree_nut"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'moroccan lentil stew',
  'Moroccan Lentil Stew',
  '[{"name":"lentils","quantity":300,"unit":"g"},{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"cumin","quantity":8,"unit":"g"},{"name":"turmeric","quantity":5,"unit":"g"},{"name":"cilantro","quantity":20,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"}]',
  1,
  320,
  18,
  46,
  8,
  16,
  6,
  380,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","gluten-free","dairy-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bissara fava bean soup',
  'Bissara (Fava Bean Soup)',
  '[{"name":"dried fava beans","quantity":400,"unit":"g"},{"name":"garlic","quantity":20,"unit":"g"},{"name":"cumin","quantity":10,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"},{"name":"paprika","quantity":5,"unit":"g"}]',
  1,
  340,
  20,
  44,
  10,
  14,
  4,
  320,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","gluten-free","dairy-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chermoula fish',
  'Chermoula Fish',
  '[{"name":"white fish fillets","quantity":500,"unit":"g"},{"name":"cilantro","quantity":40,"unit":"g"},{"name":"parsley","quantity":30,"unit":"g"},{"name":"garlic","quantity":20,"unit":"g"},{"name":"cumin","quantity":8,"unit":"g"},{"name":"paprika","quantity":5,"unit":"g"},{"name":"lemon juice","quantity":40,"unit":"ml"},{"name":"olive oil","quantity":60,"unit":"ml"}]',
  1,
  320,
  38,
  6,
  16,
  2,
  2,
  420,
  '["fish"]',
  '["high_fructan"]',
  '["gluten-free","dairy-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'moroccan salad assortment',
  'Moroccan Salad Assortment',
  '[{"name":"tomatoes","quantity":150,"unit":"g"},{"name":"cucumbers","quantity":150,"unit":"g"},{"name":"carrots","quantity":100,"unit":"g"},{"name":"beets","quantity":100,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"lemon juice","quantity":30,"unit":"ml"},{"name":"cumin","quantity":5,"unit":"g"}]',
  1,
  180,
  3,
  18,
  12,
  5,
  12,
  180,
  '[]',
  '["high_fructan","high_polyol"]',
  '["vegan","gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'moroccan mint tea',
  'Moroccan Mint Tea',
  '[{"name":"green tea","quantity":15,"unit":"g"},{"name":"fresh mint","quantity":30,"unit":"g"},{"name":"sugar","quantity":40,"unit":"g"},{"name":"water","quantity":500,"unit":"ml"}]',
  1,
  60,
  0,
  16,
  0,
  0,
  16,
  5,
  '[]',
  '[]',
  '["vegan","gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sfenj moroccan donuts',
  'Sfenj (Moroccan Donuts)',
  '[{"name":"flour","quantity":400,"unit":"g"},{"name":"yeast","quantity":10,"unit":"g"},{"name":"salt","quantity":8,"unit":"g"},{"name":"vegetable oil","quantity":500,"unit":"ml"},{"name":"sugar","quantity":60,"unit":"g"}]',
  1,
  280,
  5,
  38,
  12,
  1,
  8,
  280,
  '["wheat"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chebakia',
  'Chebakia',
  '[{"name":"flour","quantity":500,"unit":"g"},{"name":"sesame seeds","quantity":100,"unit":"g"},{"name":"almonds","quantity":100,"unit":"g"},{"name":"honey","quantity":200,"unit":"g"},{"name":"butter","quantity":80,"unit":"g"},{"name":"orange blossom water","quantity":30,"unit":"ml"},{"name":"cinnamon","quantity":5,"unit":"g"}]',
  1,
  320,
  6,
  42,
  14,
  2,
  22,
  120,
  '["wheat","sesame","tree_nut","milk"]',
  '["high_fructan","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'orange cinnamon dessert',
  'Orange Cinnamon Dessert',
  '[{"name":"oranges","quantity":600,"unit":"g"},{"name":"cinnamon","quantity":8,"unit":"g"},{"name":"orange blossom water","quantity":15,"unit":"ml"},{"name":"powdered sugar","quantity":30,"unit":"g"},{"name":"almonds","quantity":40,"unit":"g"}]',
  1,
  180,
  4,
  36,
  4,
  4,
  28,
  10,
  '["tree_nut"]',
  '["high_fructose"]',
  '["vegan","gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'schnitzel',
  'Schnitzel',
  '[{"name":"pork cutlet","quantity":200,"unit":"g"},{"name":"flour","quantity":50,"unit":"g"},{"name":"eggs","quantity":2,"unit":"pieces"},{"name":"breadcrumbs","quantity":100,"unit":"g"},{"name":"butter","quantity":60,"unit":"g"},{"name":"lemon","quantity":1,"unit":"piece"}]',
  1,
  520,
  38,
  32,
  28,
  1,
  1,
  480,
  '["wheat","egg","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bratwurst',
  'Bratwurst',
  '[{"name":"pork sausage","quantity":200,"unit":"g"},{"name":"bread roll","quantity":1,"unit":"piece"},{"name":"mustard","quantity":20,"unit":"g"},{"name":"sauerkraut","quantity":100,"unit":"g"}]',
  1,
  480,
  22,
  32,
  30,
  3,
  4,
  1100,
  '["wheat"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'currywurst',
  'Currywurst',
  '[{"name":"pork sausage","quantity":150,"unit":"g"},{"name":"curry ketchup","quantity":80,"unit":"ml"},{"name":"curry powder","quantity":10,"unit":"g"},{"name":"french fries","quantity":150,"unit":"g"}]',
  1,
  580,
  18,
  48,
  36,
  3,
  16,
  1020,
  '[]',
  '["high_fructan","high_fructose"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'schweinshaxe pork knuckle',
  'Schweinshaxe (Pork Knuckle)',
  '[{"name":"pork knuckle","quantity":800,"unit":"g"},{"name":"caraway seeds","quantity":5,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"beer","quantity":250,"unit":"ml"}]',
  1,
  680,
  52,
  8,
  48,
  1,
  2,
  780,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sauerbraten',
  'Sauerbraten',
  '[{"name":"beef roast","quantity":800,"unit":"g"},{"name":"red wine vinegar","quantity":200,"unit":"ml"},{"name":"red wine","quantity":200,"unit":"ml"},{"name":"onion","quantity":150,"unit":"g"},{"name":"carrots","quantity":100,"unit":"g"},{"name":"ginger snaps","quantity":80,"unit":"g"},{"name":"bay leaves","quantity":3,"unit":"pieces"}]',
  1,
  480,
  45,
  22,
  24,
  2,
  10,
  520,
  '["wheat"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'rouladen',
  'Rouladen',
  '[{"name":"beef slices","quantity":500,"unit":"g"},{"name":"bacon","quantity":100,"unit":"g"},{"name":"pickles","quantity":80,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"mustard","quantity":30,"unit":"g"},{"name":"beef broth","quantity":300,"unit":"ml"}]',
  1,
  480,
  42,
  8,
  32,
  1,
  3,
  920,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'weisswurst',
  'Weisswurst',
  '[{"name":"veal sausage","quantity":200,"unit":"g"},{"name":"sweet mustard","quantity":30,"unit":"g"},{"name":"pretzel","quantity":1,"unit":"piece"},{"name":"parsley","quantity":5,"unit":"g"}]',
  1,
  420,
  24,
  32,
  22,
  1,
  4,
  920,
  '["wheat","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'leberkase',
  'Leberkäse',
  '[{"name":"pork","quantity":300,"unit":"g"},{"name":"beef","quantity":200,"unit":"g"},{"name":"bacon","quantity":100,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"marjoram","quantity":3,"unit":"g"},{"name":"bread roll","quantity":1,"unit":"piece"}]',
  1,
  520,
  28,
  28,
  34,
  1,
  3,
  1080,
  '["wheat"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'german goulash soup',
  'German Goulash Soup',
  '[{"name":"beef chunks","quantity":400,"unit":"g"},{"name":"onion","quantity":200,"unit":"g"},{"name":"bell peppers","quantity":150,"unit":"g"},{"name":"tomato paste","quantity":40,"unit":"g"},{"name":"paprika","quantity":20,"unit":"g"},{"name":"caraway seeds","quantity":5,"unit":"g"},{"name":"potatoes","quantity":200,"unit":"g"}]',
  1,
  420,
  35,
  32,
  18,
  5,
  8,
  680,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sauerkraut',
  'Sauerkraut',
  '[{"name":"fermented cabbage","quantity":300,"unit":"g"},{"name":"bacon","quantity":60,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"caraway seeds","quantity":5,"unit":"g"},{"name":"white wine","quantity":60,"unit":"ml"}]',
  1,
  180,
  6,
  12,
  12,
  5,
  4,
  780,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pretzels',
  'Pretzels',
  '[{"name":"flour","quantity":500,"unit":"g"},{"name":"yeast","quantity":10,"unit":"g"},{"name":"butter","quantity":30,"unit":"g"},{"name":"baking soda","quantity":60,"unit":"g"},{"name":"coarse salt","quantity":15,"unit":"g"}]',
  1,
  280,
  8,
  52,
  4,
  2,
  2,
  920,
  '["wheat","milk"]',
  '["high_fructan"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'spatzle',
  'Spätzle',
  '[{"name":"flour","quantity":300,"unit":"g"},{"name":"eggs","quantity":4,"unit":"pieces"},{"name":"milk","quantity":100,"unit":"ml"},{"name":"nutmeg","quantity":2,"unit":"g"},{"name":"butter","quantity":40,"unit":"g"}]',
  1,
  380,
  14,
  52,
  14,
  2,
  3,
  280,
  '["wheat","egg","milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kartoffelsalat potato salad',
  'Kartoffelsalat (Potato Salad)',
  '[{"name":"potatoes","quantity":600,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"beef broth","quantity":150,"unit":"ml"},{"name":"white wine vinegar","quantity":40,"unit":"ml"},{"name":"vegetable oil","quantity":60,"unit":"ml"},{"name":"mustard","quantity":20,"unit":"g"}]',
  1,
  280,
  5,
  38,
  12,
  4,
  3,
  420,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free","vegan"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kasespatzle',
  'Käsespätzle',
  '[{"name":"spätzle","quantity":400,"unit":"g"},{"name":"emmental cheese","quantity":200,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"butter","quantity":60,"unit":"g"},{"name":"chives","quantity":15,"unit":"g"}]',
  1,
  580,
  24,
  48,
  34,
  2,
  4,
  580,
  '["wheat","egg","milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'flammkuchen',
  'Flammkuchen',
  '[{"name":"thin dough","quantity":250,"unit":"g"},{"name":"crème fraîche","quantity":150,"unit":"g"},{"name":"bacon","quantity":150,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"nutmeg","quantity":2,"unit":"g"}]',
  1,
  480,
  16,
  38,
  30,
  2,
  4,
  780,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');
