INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'margherita pizza',
  'Margherita Pizza',
  '[{"name":"pizza dough","quantity":250,"unit":"g"},{"name":"San Marzano tomatoes","quantity":100,"unit":"g"},{"name":"fresh mozzarella","quantity":150,"unit":"g"},{"name":"fresh basil","quantity":10,"unit":"g"},{"name":"extra virgin olive oil","quantity":15,"unit":"ml"},{"name":"sea salt","quantity":2,"unit":"g"}]',
  1,
  580,
  22,
  68,
  24,
  3,
  5,
  920,
  '["gluten","milk"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pepperoni pizza',
  'Pepperoni Pizza',
  '[{"name":"pizza dough","quantity":250,"unit":"g"},{"name":"tomato sauce","quantity":100,"unit":"ml"},{"name":"mozzarella cheese","quantity":150,"unit":"g"},{"name":"pepperoni","quantity":60,"unit":"g"},{"name":"oregano","quantity":2,"unit":"g"}]',
  1,
  680,
  28,
  65,
  32,
  3,
  5,
  1450,
  '["gluten","milk"]',
  '["high_fructan","moderate_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'lasagna',
  'Lasagna',
  '[{"name":"lasagna noodles","quantity":250,"unit":"g"},{"name":"ground beef","quantity":400,"unit":"g"},{"name":"ricotta cheese","quantity":250,"unit":"g"},{"name":"mozzarella cheese","quantity":200,"unit":"g"},{"name":"parmesan cheese","quantity":50,"unit":"g"},{"name":"marinara sauce","quantity":500,"unit":"ml"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"Italian seasoning","quantity":5,"unit":"g"}]',
  1,
  550,
  32,
  45,
  28,
  3,
  7,
  920,
  '["gluten","milk","egg"]',
  '["high_lactose","high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'spaghetti carbonara',
  'Spaghetti Carbonara',
  '[{"name":"spaghetti","quantity":200,"unit":"g"},{"name":"guanciale","quantity":100,"unit":"g"},{"name":"egg yolks","quantity":4,"unit":"whole"},{"name":"pecorino romano","quantity":50,"unit":"g"},{"name":"parmesan cheese","quantity":30,"unit":"g"},{"name":"black pepper","quantity":3,"unit":"g"}]',
  1,
  720,
  28,
  60,
  40,
  2,
  2,
  780,
  '["gluten","egg","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'spaghetti bolognese',
  'Spaghetti Bolognese',
  '[{"name":"spaghetti","quantity":200,"unit":"g"},{"name":"ground beef","quantity":250,"unit":"g"},{"name":"ground pork","quantity":100,"unit":"g"},{"name":"crushed tomatoes","quantity":400,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"carrot","quantity":50,"unit":"g"},{"name":"celery","quantity":30,"unit":"g"},{"name":"red wine","quantity":100,"unit":"ml"},{"name":"garlic","quantity":2,"unit":"cloves"},{"name":"olive oil","quantity":20,"unit":"ml"},{"name":"parmesan cheese","quantity":30,"unit":"g"}]',
  1,
  680,
  35,
  65,
  28,
  4,
  8,
  720,
  '["gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'cacio e pepe',
  'Cacio e Pepe',
  '[{"name":"spaghetti","quantity":200,"unit":"g"},{"name":"pecorino romano","quantity":100,"unit":"g"},{"name":"black pepper","quantity":5,"unit":"g"},{"name":"pasta water","quantity":100,"unit":"ml"}]',
  1,
  550,
  22,
  58,
  26,
  2,
  1,
  680,
  '["gluten","milk"]',
  '["high_fructan"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'fettuccine alfredo',
  'Fettuccine Alfredo',
  '[{"name":"fettuccine pasta","quantity":200,"unit":"g"},{"name":"butter","quantity":60,"unit":"g"},{"name":"heavy cream","quantity":240,"unit":"ml"},{"name":"parmesan cheese","quantity":100,"unit":"g"},{"name":"garlic","quantity":2,"unit":"cloves"},{"name":"black pepper","quantity":2,"unit":"g"}]',
  1,
  850,
  22,
  65,
  55,
  2,
  3,
  650,
  '["gluten","milk"]',
  '["high_lactose","high_fructan"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pasta alla norma',
  'Pasta alla Norma',
  '[{"name":"rigatoni","quantity":200,"unit":"g"},{"name":"eggplant","quantity":300,"unit":"g"},{"name":"San Marzano tomatoes","quantity":400,"unit":"g"},{"name":"ricotta salata","quantity":60,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"fresh basil","quantity":15,"unit":"g"},{"name":"olive oil","quantity":45,"unit":"ml"}]',
  1,
  520,
  16,
  68,
  20,
  8,
  10,
  480,
  '["gluten","milk"]',
  '["high_fructan","moderate_sorbitol"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pesto pasta',
  'Pesto Pasta',
  '[{"name":"linguine","quantity":200,"unit":"g"},{"name":"fresh basil","quantity":60,"unit":"g"},{"name":"pine nuts","quantity":30,"unit":"g"},{"name":"parmesan cheese","quantity":50,"unit":"g"},{"name":"garlic","quantity":2,"unit":"cloves"},{"name":"extra virgin olive oil","quantity":80,"unit":"ml"},{"name":"sea salt","quantity":2,"unit":"g"}]',
  1,
  680,
  18,
  58,
  42,
  3,
  2,
  420,
  '["gluten","milk","tree nuts"]',
  '["high_fructan"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'risotto alla milanese',
  'Risotto alla Milanese',
  '[{"name":"arborio rice","quantity":200,"unit":"g"},{"name":"beef bone marrow","quantity":30,"unit":"g"},{"name":"saffron threads","quantity":0.2,"unit":"g"},{"name":"white wine","quantity":100,"unit":"ml"},{"name":"chicken broth","quantity":750,"unit":"ml"},{"name":"butter","quantity":50,"unit":"g"},{"name":"parmesan cheese","quantity":60,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"}]',
  1,
  520,
  14,
  62,
  22,
  1,
  2,
  680,
  '["milk"]',
  '["high_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'risotto ai funghi',
  'Risotto ai Funghi',
  '[{"name":"arborio rice","quantity":200,"unit":"g"},{"name":"porcini mushrooms","quantity":100,"unit":"g"},{"name":"cremini mushrooms","quantity":150,"unit":"g"},{"name":"white wine","quantity":100,"unit":"ml"},{"name":"vegetable broth","quantity":750,"unit":"ml"},{"name":"butter","quantity":40,"unit":"g"},{"name":"parmesan cheese","quantity":50,"unit":"g"},{"name":"shallot","quantity":40,"unit":"g"},{"name":"fresh thyme","quantity":5,"unit":"g"}]',
  1,
  480,
  12,
  58,
  20,
  3,
  3,
  580,
  '["milk"]',
  '["high_mannitol","high_fructan"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'osso buco',
  'Osso Buco',
  '[{"name":"veal shanks","quantity":400,"unit":"g"},{"name":"white wine","quantity":200,"unit":"ml"},{"name":"beef broth","quantity":300,"unit":"ml"},{"name":"crushed tomatoes","quantity":200,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"carrot","quantity":60,"unit":"g"},{"name":"celery","quantity":40,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"lemon zest","quantity":5,"unit":"g"},{"name":"parsley","quantity":15,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"}]',
  1,
  420,
  38,
  12,
  22,
  3,
  6,
  620,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken parmigiana',
  'Chicken Parmigiana',
  '[{"name":"chicken breast","quantity":200,"unit":"g"},{"name":"breadcrumbs","quantity":60,"unit":"g"},{"name":"parmesan cheese","quantity":40,"unit":"g"},{"name":"mozzarella cheese","quantity":80,"unit":"g"},{"name":"marinara sauce","quantity":150,"unit":"ml"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"flour","quantity":30,"unit":"g"},{"name":"olive oil","quantity":45,"unit":"ml"},{"name":"fresh basil","quantity":5,"unit":"g"}]',
  1,
  580,
  42,
  32,
  30,
  2,
  5,
  850,
  '["gluten","milk","egg"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'veal parmigiana',
  'Veal Parmigiana',
  '[{"name":"veal cutlet","quantity":200,"unit":"g"},{"name":"breadcrumbs","quantity":60,"unit":"g"},{"name":"parmesan cheese","quantity":40,"unit":"g"},{"name":"mozzarella cheese","quantity":80,"unit":"g"},{"name":"marinara sauce","quantity":150,"unit":"ml"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"flour","quantity":30,"unit":"g"},{"name":"olive oil","quantity":45,"unit":"ml"},{"name":"fresh basil","quantity":5,"unit":"g"}]',
  1,
  560,
  38,
  32,
  30,
  2,
  5,
  820,
  '["gluten","milk","egg"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'eggplant parmigiana',
  'Eggplant Parmigiana',
  '[{"name":"eggplant","quantity":400,"unit":"g"},{"name":"breadcrumbs","quantity":80,"unit":"g"},{"name":"parmesan cheese","quantity":60,"unit":"g"},{"name":"mozzarella cheese","quantity":150,"unit":"g"},{"name":"marinara sauce","quantity":300,"unit":"ml"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"flour","quantity":40,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"},{"name":"fresh basil","quantity":10,"unit":"g"}]',
  1,
  480,
  20,
  38,
  28,
  8,
  10,
  780,
  '["gluten","milk","egg"]',
  '["high_fructan","moderate_sorbitol"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'caprese salad',
  'Caprese Salad',
  '[{"name":"fresh mozzarella","quantity":200,"unit":"g"},{"name":"tomato","quantity":250,"unit":"g"},{"name":"fresh basil","quantity":20,"unit":"g"},{"name":"extra virgin olive oil","quantity":30,"unit":"ml"},{"name":"balsamic glaze","quantity":15,"unit":"ml"},{"name":"sea salt","quantity":2,"unit":"g"},{"name":"black pepper","quantity":1,"unit":"g"}]',
  1,
  380,
  18,
  10,
  30,
  2,
  6,
  520,
  '["milk"]',
  '["moderate_lactose","high_fructose"]',
  '["vegetarian","gluten-free","keto","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bruschetta',
  'Bruschetta',
  '[{"name":"Italian bread","quantity":150,"unit":"g"},{"name":"tomato","quantity":200,"unit":"g"},{"name":"fresh basil","quantity":15,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"extra virgin olive oil","quantity":30,"unit":"ml"},{"name":"balsamic vinegar","quantity":10,"unit":"ml"},{"name":"sea salt","quantity":2,"unit":"g"}]',
  1,
  280,
  6,
  38,
  12,
  3,
  5,
  420,
  '["gluten"]',
  '["high_fructan","high_fructose"]',
  '["vegan","dairy-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'minestrone',
  'Minestrone',
  '[{"name":"cannellini beans","quantity":150,"unit":"g"},{"name":"pasta (ditalini)","quantity":80,"unit":"g"},{"name":"zucchini","quantity":100,"unit":"g"},{"name":"carrot","quantity":80,"unit":"g"},{"name":"celery","quantity":60,"unit":"g"},{"name":"potato","quantity":100,"unit":"g"},{"name":"crushed tomatoes","quantity":200,"unit":"g"},{"name":"vegetable broth","quantity":500,"unit":"ml"},{"name":"onion","quantity":60,"unit":"g"},{"name":"garlic","quantity":2,"unit":"cloves"},{"name":"parmesan rind","quantity":30,"unit":"g"},{"name":"olive oil","quantity":20,"unit":"ml"}]',
  1,
  320,
  14,
  48,
  8,
  10,
  8,
  680,
  '["gluten","milk"]',
  '["high_gos","high_fructan"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tiramisu',
  'Tiramisu',
  '[{"name":"mascarpone cheese","quantity":250,"unit":"g"},{"name":"ladyfinger cookies","quantity":200,"unit":"g"},{"name":"espresso coffee","quantity":200,"unit":"ml"},{"name":"egg yolks","quantity":4,"unit":"whole"},{"name":"sugar","quantity":80,"unit":"g"},{"name":"cocoa powder","quantity":20,"unit":"g"},{"name":"Marsala wine","quantity":30,"unit":"ml"}]',
  1,
  420,
  8,
  45,
  24,
  1,
  32,
  120,
  '["gluten","milk","egg"]',
  '["high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'gelato',
  'Gelato',
  '[{"name":"whole milk","quantity":400,"unit":"ml"},{"name":"heavy cream","quantity":150,"unit":"ml"},{"name":"sugar","quantity":120,"unit":"g"},{"name":"egg yolks","quantity":4,"unit":"whole"},{"name":"vanilla bean","quantity":1,"unit":"whole"}]',
  1,
  280,
  5,
  32,
  15,
  0,
  28,
  60,
  '["milk","egg"]',
  '["high_lactose"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tacos al pastor',
  'Tacos al Pastor',
  '[{"name":"pork shoulder","quantity":300,"unit":"g"},{"name":"corn tortillas","quantity":6,"unit":"pieces"},{"name":"pineapple","quantity":100,"unit":"g"},{"name":"achiote paste","quantity":30,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"cilantro","quantity":15,"unit":"g"},{"name":"lime","quantity":1,"unit":"whole"},{"name":"guajillo chilies","quantity":3,"unit":"pieces"}]',
  1,
  520,
  32,
  45,
  22,
  4,
  12,
  680,
  '[]',
  '["high_fructan","high_fructose"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'carne asada tacos',
  'Carne Asada Tacos',
  '[{"name":"flank steak","quantity":300,"unit":"g"},{"name":"corn tortillas","quantity":6,"unit":"pieces"},{"name":"lime juice","quantity":30,"unit":"ml"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"cilantro","quantity":15,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"jalapeño","quantity":1,"unit":"whole"},{"name":"cumin","quantity":3,"unit":"g"}]',
  1,
  480,
  35,
  38,
  20,
  3,
  3,
  520,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'barbacoa tacos',
  'Barbacoa Tacos',
  '[{"name":"beef cheeks","quantity":350,"unit":"g"},{"name":"corn tortillas","quantity":6,"unit":"pieces"},{"name":"chipotle peppers","quantity":2,"unit":"pieces"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"oregano","quantity":2,"unit":"g"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"lime juice","quantity":30,"unit":"ml"},{"name":"onion","quantity":50,"unit":"g"},{"name":"cilantro","quantity":15,"unit":"g"}]',
  1,
  540,
  38,
  40,
  24,
  4,
  2,
  620,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'birria tacos',
  'Birria Tacos',
  '[{"name":"beef chuck","quantity":400,"unit":"g"},{"name":"corn tortillas","quantity":6,"unit":"pieces"},{"name":"guajillo chilies","quantity":4,"unit":"pieces"},{"name":"ancho chilies","quantity":2,"unit":"pieces"},{"name":"onion","quantity":80,"unit":"g"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"oregano","quantity":2,"unit":"g"},{"name":"queso fresco","quantity":60,"unit":"g"},{"name":"cilantro","quantity":15,"unit":"g"}]',
  1,
  580,
  42,
  42,
  26,
  4,
  4,
  720,
  '["milk"]',
  '["high_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'carnitas',
  'Carnitas',
  '[{"name":"pork shoulder","quantity":500,"unit":"g"},{"name":"lard","quantity":60,"unit":"g"},{"name":"orange juice","quantity":120,"unit":"ml"},{"name":"lime juice","quantity":30,"unit":"ml"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"oregano","quantity":2,"unit":"g"},{"name":"bay leaves","quantity":2,"unit":"pieces"}]',
  1,
  420,
  35,
  8,
  28,
  1,
  5,
  480,
  '[]',
  '["high_fructan","high_fructose"]',
  '["gluten-free","dairy-free","keto","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'enchiladas',
  'Enchiladas',
  '[{"name":"corn tortillas","quantity":8,"unit":"pieces"},{"name":"shredded chicken","quantity":300,"unit":"g"},{"name":"enchilada sauce","quantity":400,"unit":"ml"},{"name":"queso fresco","quantity":100,"unit":"g"},{"name":"sour cream","quantity":60,"unit":"g"},{"name":"onion","quantity":50,"unit":"g"},{"name":"cilantro","quantity":10,"unit":"g"}]',
  1,
  520,
  35,
  45,
  22,
  5,
  6,
  920,
  '["milk"]',
  '["high_fructan","moderate_lactose"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chiles rellenos',
  'Chiles Rellenos',
  '[{"name":"poblano peppers","quantity":4,"unit":"pieces"},{"name":"queso Oaxaca","quantity":200,"unit":"g"},{"name":"egg","quantity":3,"unit":"whole"},{"name":"flour","quantity":30,"unit":"g"},{"name":"tomato sauce","quantity":200,"unit":"ml"},{"name":"onion","quantity":60,"unit":"g"},{"name":"garlic","quantity":2,"unit":"cloves"},{"name":"vegetable oil","quantity":60,"unit":"ml"}]',
  1,
  480,
  22,
  25,
  32,
  4,
  8,
  680,
  '["milk","egg","gluten"]',
  '["high_fructan"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tamales',
  'Tamales',
  '[{"name":"masa harina","quantity":300,"unit":"g"},{"name":"lard","quantity":150,"unit":"g"},{"name":"pork","quantity":250,"unit":"g"},{"name":"dried corn husks","quantity":12,"unit":"pieces"},{"name":"guajillo chilies","quantity":4,"unit":"pieces"},{"name":"chicken broth","quantity":200,"unit":"ml"},{"name":"cumin","quantity":2,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"}]',
  1,
  380,
  15,
  32,
  22,
  3,
  1,
  520,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'mole poblano',
  'Mole Poblano',
  '[{"name":"chicken thighs","quantity":400,"unit":"g"},{"name":"ancho chilies","quantity":4,"unit":"pieces"},{"name":"pasilla chilies","quantity":3,"unit":"pieces"},{"name":"mulato chilies","quantity":2,"unit":"pieces"},{"name":"Mexican chocolate","quantity":50,"unit":"g"},{"name":"almonds","quantity":30,"unit":"g"},{"name":"sesame seeds","quantity":20,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"cinnamon","quantity":2,"unit":"g"},{"name":"cumin","quantity":2,"unit":"g"}]',
  1,
  520,
  35,
  28,
  32,
  6,
  12,
  580,
  '["tree nuts","sesame"]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'cochinita pibil',
  'Cochinita Pibil',
  '[{"name":"pork shoulder","quantity":500,"unit":"g"},{"name":"achiote paste","quantity":60,"unit":"g"},{"name":"sour orange juice","quantity":150,"unit":"ml"},{"name":"banana leaves","quantity":2,"unit":"pieces"},{"name":"habanero pepper","quantity":1,"unit":"whole"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"cumin","quantity":2,"unit":"g"},{"name":"oregano","quantity":2,"unit":"g"},{"name":"pickled red onion","quantity":80,"unit":"g"}]',
  1,
  450,
  38,
  12,
  28,
  2,
  6,
  520,
  '[]',
  '["high_fructan","high_fructose"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pozole',
  'Pozole',
  '[{"name":"pork shoulder","quantity":400,"unit":"g"},{"name":"hominy","quantity":400,"unit":"g"},{"name":"guajillo chilies","quantity":4,"unit":"pieces"},{"name":"ancho chilies","quantity":2,"unit":"pieces"},{"name":"onion","quantity":100,"unit":"g"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"oregano","quantity":3,"unit":"g"},{"name":"cabbage","quantity":100,"unit":"g"},{"name":"radishes","quantity":50,"unit":"g"},{"name":"lime","quantity":2,"unit":"wedges"}]',
  1,
  420,
  32,
  38,
  18,
  6,
  4,
  720,
  '[]',
  '["high_fructan","high_gos"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'menudo',
  'Menudo',
  '[{"name":"beef tripe","quantity":500,"unit":"g"},{"name":"hominy","quantity":400,"unit":"g"},{"name":"guajillo chilies","quantity":6,"unit":"pieces"},{"name":"onion","quantity":80,"unit":"g"},{"name":"garlic","quantity":5,"unit":"cloves"},{"name":"oregano","quantity":3,"unit":"g"},{"name":"bay leaves","quantity":2,"unit":"pieces"},{"name":"lime","quantity":2,"unit":"wedges"},{"name":"cilantro","quantity":15,"unit":"g"}]',
  1,
  380,
  28,
  35,
  14,
  5,
  3,
  680,
  '[]',
  '["high_fructan","high_gos"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'quesadillas',
  'Quesadillas',
  '[{"name":"flour tortillas","quantity":2,"unit":"large"},{"name":"queso Oaxaca","quantity":150,"unit":"g"},{"name":"grilled chicken","quantity":100,"unit":"g"},{"name":"onion","quantity":30,"unit":"g"},{"name":"peppers","quantity":40,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"salsa","quantity":40,"unit":"g"}]',
  1,
  580,
  35,
  42,
  30,
  3,
  4,
  980,
  '["gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'gorditas',
  'Gorditas',
  '[{"name":"masa harina","quantity":200,"unit":"g"},{"name":"carnitas","quantity":150,"unit":"g"},{"name":"refried beans","quantity":80,"unit":"g"},{"name":"queso fresco","quantity":50,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"},{"name":"salsa verde","quantity":40,"unit":"ml"},{"name":"sour cream","quantity":30,"unit":"g"}]',
  1,
  520,
  28,
  48,
  24,
  6,
  3,
  720,
  '["milk"]',
  '["high_gos","high_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sopes',
  'Sopes',
  '[{"name":"masa harina","quantity":200,"unit":"g"},{"name":"refried beans","quantity":100,"unit":"g"},{"name":"shredded chicken","quantity":120,"unit":"g"},{"name":"queso fresco","quantity":60,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"},{"name":"salsa roja","quantity":50,"unit":"ml"},{"name":"sour cream","quantity":30,"unit":"g"}]',
  1,
  480,
  28,
  45,
  20,
  7,
  3,
  680,
  '["milk"]',
  '["high_gos","high_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tostadas',
  'Tostadas',
  '[{"name":"corn tostadas","quantity":4,"unit":"pieces"},{"name":"refried beans","quantity":120,"unit":"g"},{"name":"shredded chicken","quantity":150,"unit":"g"},{"name":"lettuce","quantity":60,"unit":"g"},{"name":"tomato","quantity":80,"unit":"g"},{"name":"queso fresco","quantity":60,"unit":"g"},{"name":"sour cream","quantity":40,"unit":"g"},{"name":"salsa","quantity":50,"unit":"ml"}]',
  1,
  520,
  32,
  48,
  22,
  8,
  5,
  780,
  '["milk"]',
  '["high_gos","high_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'elote',
  'Elote',
  '[{"name":"corn on the cob","quantity":2,"unit":"pieces"},{"name":"mayonnaise","quantity":40,"unit":"g"},{"name":"cotija cheese","quantity":40,"unit":"g"},{"name":"chili powder","quantity":3,"unit":"g"},{"name":"lime juice","quantity":15,"unit":"ml"},{"name":"cilantro","quantity":10,"unit":"g"}]',
  1,
  320,
  8,
  32,
  20,
  3,
  8,
  420,
  '["milk","egg"]',
  '["moderate_sorbitol"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'guacamole',
  'Guacamole',
  '[{"name":"avocado","quantity":300,"unit":"g"},{"name":"lime juice","quantity":30,"unit":"ml"},{"name":"onion","quantity":40,"unit":"g"},{"name":"tomato","quantity":60,"unit":"g"},{"name":"jalapeño","quantity":1,"unit":"whole"},{"name":"cilantro","quantity":15,"unit":"g"},{"name":"garlic","quantity":1,"unit":"clove"},{"name":"sea salt","quantity":3,"unit":"g"}]',
  1,
  280,
  4,
  16,
  24,
  12,
  3,
  480,
  '[]',
  '["moderate_polyol","high_fructan"]',
  '["vegan","vegetarian","gluten-free","dairy-free","keto"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'ceviche',
  'Ceviche',
  '[{"name":"white fish","quantity":300,"unit":"g"},{"name":"lime juice","quantity":150,"unit":"ml"},{"name":"tomato","quantity":100,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"jalapeño","quantity":1,"unit":"whole"},{"name":"cilantro","quantity":20,"unit":"g"},{"name":"cucumber","quantity":80,"unit":"g"},{"name":"avocado","quantity":80,"unit":"g"}]',
  1,
  220,
  28,
  12,
  8,
  4,
  5,
  380,
  '["fish"]',
  '["high_fructan","moderate_polyol"]',
  '["gluten-free","dairy-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'churros',
  'Churros',
  '[{"name":"flour","quantity":150,"unit":"g"},{"name":"water","quantity":200,"unit":"ml"},{"name":"butter","quantity":60,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"sugar","quantity":60,"unit":"g"},{"name":"cinnamon","quantity":5,"unit":"g"},{"name":"vegetable oil","quantity":200,"unit":"ml"},{"name":"chocolate sauce","quantity":60,"unit":"ml"}]',
  1,
  380,
  5,
  45,
  20,
  1,
  22,
  180,
  '["gluten","milk","egg"]',
  '["high_fructan"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kung pao chicken',
  'Kung Pao Chicken',
  '[{"name":"chicken thigh","quantity":300,"unit":"g"},{"name":"peanuts","quantity":50,"unit":"g"},{"name":"dried red chilies","quantity":8,"unit":"pieces"},{"name":"Sichuan peppercorns","quantity":5,"unit":"g"},{"name":"soy sauce","quantity":30,"unit":"ml"},{"name":"rice vinegar","quantity":20,"unit":"ml"},{"name":"shaoxing wine","quantity":15,"unit":"ml"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"green onion","quantity":30,"unit":"g"},{"name":"cornstarch","quantity":15,"unit":"g"}]',
  1,
  480,
  35,
  22,
  28,
  3,
  6,
  980,
  '["peanut","soy"]',
  '["high_fructan","high_gos"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'general tso chicken',
  'General Tso Chicken',
  '[{"name":"chicken thigh","quantity":350,"unit":"g"},{"name":"cornstarch","quantity":60,"unit":"g"},{"name":"soy sauce","quantity":45,"unit":"ml"},{"name":"rice vinegar","quantity":30,"unit":"ml"},{"name":"hoisin sauce","quantity":30,"unit":"ml"},{"name":"brown sugar","quantity":40,"unit":"g"},{"name":"ginger","quantity":15,"unit":"g"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"dried red chilies","quantity":6,"unit":"pieces"},{"name":"vegetable oil","quantity":80,"unit":"ml"},{"name":"sesame oil","quantity":10,"unit":"ml"}]',
  1,
  620,
  32,
  52,
  32,
  1,
  28,
  1350,
  '["soy","sesame"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sweet and sour pork',
  'Sweet and Sour Pork',
  '[{"name":"pork loin","quantity":350,"unit":"g"},{"name":"pineapple chunks","quantity":150,"unit":"g"},{"name":"bell peppers","quantity":100,"unit":"g"},{"name":"cornstarch","quantity":50,"unit":"g"},{"name":"rice vinegar","quantity":60,"unit":"ml"},{"name":"ketchup","quantity":45,"unit":"ml"},{"name":"sugar","quantity":50,"unit":"g"},{"name":"soy sauce","quantity":20,"unit":"ml"},{"name":"vegetable oil","quantity":100,"unit":"ml"}]',
  1,
  580,
  28,
  55,
  26,
  2,
  38,
  680,
  '["soy"]',
  '["high_fructose","high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'twice cooked pork',
  'Twice Cooked Pork',
  '[{"name":"pork belly","quantity":350,"unit":"g"},{"name":"leeks","quantity":100,"unit":"g"},{"name":"bell peppers","quantity":80,"unit":"g"},{"name":"doubanjiang","quantity":30,"unit":"g"},{"name":"soy sauce","quantity":20,"unit":"ml"},{"name":"shaoxing wine","quantity":15,"unit":"ml"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"sugar","quantity":10,"unit":"g"}]',
  1,
  520,
  25,
  15,
  40,
  2,
  8,
  920,
  '["soy"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'char siu',
  'Char Siu',
  '[{"name":"pork shoulder","quantity":500,"unit":"g"},{"name":"hoisin sauce","quantity":60,"unit":"ml"},{"name":"honey","quantity":45,"unit":"ml"},{"name":"soy sauce","quantity":30,"unit":"ml"},{"name":"five spice powder","quantity":5,"unit":"g"},{"name":"shaoxing wine","quantity":30,"unit":"ml"},{"name":"red food coloring","quantity":2,"unit":"ml"},{"name":"garlic","quantity":4,"unit":"cloves"}]',
  1,
  380,
  35,
  22,
  16,
  1,
  18,
  850,
  '["soy"]',
  '["high_fructan","high_fructose"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'mapo tofu',
  'Mapo Tofu',
  '[{"name":"silken tofu","quantity":400,"unit":"g"},{"name":"ground pork","quantity":150,"unit":"g"},{"name":"doubanjiang","quantity":40,"unit":"g"},{"name":"Sichuan peppercorns","quantity":5,"unit":"g"},{"name":"fermented black beans","quantity":15,"unit":"g"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"green onion","quantity":30,"unit":"g"},{"name":"soy sauce","quantity":15,"unit":"ml"},{"name":"cornstarch","quantity":10,"unit":"g"}]',
  1,
  320,
  22,
  12,
  22,
  2,
  3,
  980,
  '["soy"]',
  '["high_fructan","high_gos"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'peking duck',
  'Peking Duck',
  '[{"name":"whole duck","quantity":2000,"unit":"g"},{"name":"maltose","quantity":60,"unit":"ml"},{"name":"rice vinegar","quantity":30,"unit":"ml"},{"name":"five spice powder","quantity":5,"unit":"g"},{"name":"Mandarin pancakes","quantity":12,"unit":"pieces"},{"name":"hoisin sauce","quantity":80,"unit":"ml"},{"name":"green onion","quantity":60,"unit":"g"},{"name":"cucumber","quantity":100,"unit":"g"}]',
  1,
  680,
  45,
  35,
  40,
  2,
  15,
  720,
  '["gluten","soy"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'hot pot',
  'Hot Pot',
  '[{"name":"beef slices","quantity":200,"unit":"g"},{"name":"lamb slices","quantity":150,"unit":"g"},{"name":"tofu","quantity":150,"unit":"g"},{"name":"napa cabbage","quantity":200,"unit":"g"},{"name":"mushrooms","quantity":150,"unit":"g"},{"name":"glass noodles","quantity":100,"unit":"g"},{"name":"hot pot broth","quantity":1000,"unit":"ml"},{"name":"Sichuan peppercorns","quantity":10,"unit":"g"},{"name":"dried chilies","quantity":15,"unit":"g"},{"name":"sesame dipping sauce","quantity":60,"unit":"ml"}]',
  1,
  520,
  42,
  35,
  25,
  5,
  4,
  1200,
  '["soy","sesame"]',
  '["high_mannitol","high_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'xiaolongbao',
  'Xiaolongbao',
  '[{"name":"pork","quantity":300,"unit":"g"},{"name":"pork gelatin","quantity":100,"unit":"g"},{"name":"dumpling wrapper","quantity":250,"unit":"g"},{"name":"ginger","quantity":15,"unit":"g"},{"name":"green onion","quantity":30,"unit":"g"},{"name":"soy sauce","quantity":20,"unit":"ml"},{"name":"sesame oil","quantity":10,"unit":"ml"},{"name":"shaoxing wine","quantity":15,"unit":"ml"}]',
  1,
  420,
  25,
  42,
  18,
  2,
  2,
  780,
  '["gluten","soy","sesame"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'jiaozi',
  'Jiaozi',
  '[{"name":"ground pork","quantity":300,"unit":"g"},{"name":"napa cabbage","quantity":200,"unit":"g"},{"name":"dumpling wrapper","quantity":250,"unit":"g"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"green onion","quantity":40,"unit":"g"},{"name":"soy sauce","quantity":25,"unit":"ml"},{"name":"sesame oil","quantity":15,"unit":"ml"}]',
  1,
  380,
  22,
  40,
  15,
  3,
  2,
  720,
  '["gluten","soy","sesame"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');
