INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'rotkohl red cabbage',
  'Rotkohl (Red Cabbage)',
  '[{"name":"red cabbage","quantity":500,"unit":"g"},{"name":"apple","quantity":100,"unit":"g"},{"name":"red wine vinegar","quantity":40,"unit":"ml"},{"name":"sugar","quantity":30,"unit":"g"},{"name":"cloves","quantity":3,"unit":"pieces"},{"name":"bay leaf","quantity":1,"unit":"piece"}]',
  1,
  120,
  3,
  26,
  1,
  5,
  18,
  180,
  '[]',
  '["high_fructan","high_polyol"]',
  '["vegan","gluten-free","dairy-free","low-fat"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'black forest cake',
  'Black Forest Cake',
  '[{"name":"chocolate sponge","quantity":400,"unit":"g"},{"name":"cherries","quantity":300,"unit":"g"},{"name":"whipped cream","quantity":500,"unit":"ml"},{"name":"kirsch","quantity":60,"unit":"ml"},{"name":"chocolate shavings","quantity":80,"unit":"g"}]',
  1,
  420,
  6,
  48,
  24,
  2,
  36,
  120,
  '["wheat","milk","egg"]',
  '["high_lactose","high_polyol"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'apple strudel',
  'Apple Strudel',
  '[{"name":"apples","quantity":600,"unit":"g"},{"name":"strudel dough","quantity":200,"unit":"g"},{"name":"breadcrumbs","quantity":60,"unit":"g"},{"name":"butter","quantity":80,"unit":"g"},{"name":"sugar","quantity":80,"unit":"g"},{"name":"cinnamon","quantity":5,"unit":"g"},{"name":"raisins","quantity":60,"unit":"g"}]',
  1,
  340,
  4,
  52,
  14,
  3,
  32,
  180,
  '["wheat","milk"]',
  '["high_fructan","high_polyol","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'berliner jam donut',
  'Berliner (Jam Donut)',
  '[{"name":"flour","quantity":400,"unit":"g"},{"name":"yeast","quantity":15,"unit":"g"},{"name":"butter","quantity":60,"unit":"g"},{"name":"eggs","quantity":2,"unit":"pieces"},{"name":"jam","quantity":150,"unit":"g"},{"name":"powdered sugar","quantity":60,"unit":"g"},{"name":"vegetable oil","quantity":500,"unit":"ml"}]',
  1,
  320,
  6,
  46,
  14,
  1,
  22,
  140,
  '["wheat","egg","milk"]',
  '["high_fructan","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'stollen',
  'Stollen',
  '[{"name":"flour","quantity":500,"unit":"g"},{"name":"butter","quantity":200,"unit":"g"},{"name":"marzipan","quantity":150,"unit":"g"},{"name":"raisins","quantity":150,"unit":"g"},{"name":"candied citrus peel","quantity":100,"unit":"g"},{"name":"almonds","quantity":80,"unit":"g"},{"name":"powdered sugar","quantity":60,"unit":"g"}]',
  1,
  380,
  6,
  52,
  18,
  2,
  28,
  160,
  '["wheat","milk","tree_nut"]',
  '["high_fructan","high_fructose","high_polyol"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'fish and chips',
  'Fish and Chips',
  '[{"name":"cod fillet","quantity":300,"unit":"g"},{"name":"flour","quantity":150,"unit":"g"},{"name":"beer","quantity":200,"unit":"ml"},{"name":"potatoes","quantity":400,"unit":"g"},{"name":"vegetable oil","quantity":500,"unit":"ml"},{"name":"mushy peas","quantity":100,"unit":"g"},{"name":"tartar sauce","quantity":40,"unit":"g"}]',
  1,
  820,
  38,
  72,
  42,
  6,
  3,
  680,
  '["fish","wheat","egg"]',
  '["high_fructan","high_gos"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'full english breakfast',
  'Full English Breakfast',
  '[{"name":"bacon","quantity":100,"unit":"g"},{"name":"sausages","quantity":120,"unit":"g"},{"name":"eggs","quantity":2,"unit":"pieces"},{"name":"baked beans","quantity":150,"unit":"g"},{"name":"mushrooms","quantity":80,"unit":"g"},{"name":"tomatoes","quantity":100,"unit":"g"},{"name":"black pudding","quantity":60,"unit":"g"},{"name":"toast","quantity":2,"unit":"slices"},{"name":"butter","quantity":20,"unit":"g"}]',
  1,
  920,
  42,
  48,
  62,
  8,
  12,
  1680,
  '["wheat","egg","milk"]',
  '["high_fructan","high_gos","high_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sunday roast',
  'Sunday Roast',
  '[{"name":"roast beef","quantity":300,"unit":"g"},{"name":"roast potatoes","quantity":200,"unit":"g"},{"name":"Yorkshire pudding","quantity":100,"unit":"g"},{"name":"carrots","quantity":80,"unit":"g"},{"name":"parsnips","quantity":80,"unit":"g"},{"name":"Brussels sprouts","quantity":80,"unit":"g"},{"name":"gravy","quantity":100,"unit":"ml"},{"name":"horseradish sauce","quantity":20,"unit":"g"}]',
  1,
  780,
  52,
  54,
  38,
  8,
  10,
  720,
  '["wheat","egg","milk"]',
  '["high_fructan","high_polyol","high_gos"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'shepherd s pie',
  'Shepherd''s Pie',
  '[{"name":"ground lamb","quantity":500,"unit":"g"},{"name":"mashed potatoes","quantity":400,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"carrots","quantity":100,"unit":"g"},{"name":"peas","quantity":80,"unit":"g"},{"name":"beef stock","quantity":200,"unit":"ml"},{"name":"Worcestershire sauce","quantity":15,"unit":"ml"},{"name":"butter","quantity":40,"unit":"g"}]',
  1,
  580,
  35,
  42,
  32,
  6,
  8,
  680,
  '["milk","fish"]',
  '["high_fructan","high_gos"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'cottage pie',
  'Cottage Pie',
  '[{"name":"ground beef","quantity":500,"unit":"g"},{"name":"mashed potatoes","quantity":400,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"carrots","quantity":100,"unit":"g"},{"name":"peas","quantity":80,"unit":"g"},{"name":"beef stock","quantity":200,"unit":"ml"},{"name":"tomato paste","quantity":30,"unit":"g"},{"name":"butter","quantity":40,"unit":"g"}]',
  1,
  560,
  38,
  42,
  28,
  6,
  8,
  720,
  '["milk"]',
  '["high_fructan","high_gos"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bangers and mash',
  'Bangers and Mash',
  '[{"name":"pork sausages","quantity":300,"unit":"g"},{"name":"mashed potatoes","quantity":350,"unit":"g"},{"name":"onion gravy","quantity":150,"unit":"ml"},{"name":"butter","quantity":40,"unit":"g"},{"name":"milk","quantity":60,"unit":"ml"}]',
  1,
  680,
  28,
  48,
  42,
  4,
  6,
  1020,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'beef wellington',
  'Beef Wellington',
  '[{"name":"beef tenderloin","quantity":500,"unit":"g"},{"name":"puff pastry","quantity":400,"unit":"g"},{"name":"mushroom duxelles","quantity":200,"unit":"g"},{"name":"pâté","quantity":80,"unit":"g"},{"name":"egg wash","quantity":1,"unit":"piece"},{"name":"Dijon mustard","quantity":20,"unit":"g"}]',
  1,
  720,
  48,
  38,
  44,
  2,
  2,
  620,
  '["wheat","egg","milk"]',
  '["high_fructan","high_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken tikka masala uk',
  'Chicken Tikka Masala (UK)',
  '[{"name":"chicken breast","quantity":400,"unit":"g"},{"name":"tikka masala sauce","quantity":300,"unit":"ml"},{"name":"yogurt","quantity":100,"unit":"g"},{"name":"cream","quantity":100,"unit":"ml"},{"name":"onion","quantity":100,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"basmati rice","quantity":200,"unit":"g"}]',
  1,
  620,
  45,
  52,
  26,
  3,
  10,
  780,
  '["milk"]',
  '["high_fructan","high_lactose"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'steak and ale pie',
  'Steak and Ale Pie',
  '[{"name":"beef chuck","quantity":500,"unit":"g"},{"name":"puff pastry","quantity":300,"unit":"g"},{"name":"ale","quantity":300,"unit":"ml"},{"name":"onion","quantity":100,"unit":"g"},{"name":"carrots","quantity":80,"unit":"g"},{"name":"mushrooms","quantity":100,"unit":"g"},{"name":"beef stock","quantity":200,"unit":"ml"},{"name":"flour","quantity":30,"unit":"g"}]',
  1,
  680,
  42,
  48,
  36,
  4,
  6,
  720,
  '["wheat","milk"]',
  '["high_fructan","high_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'cornish pasty',
  'Cornish Pasty',
  '[{"name":"beef skirt","quantity":250,"unit":"g"},{"name":"shortcrust pastry","quantity":300,"unit":"g"},{"name":"potatoes","quantity":150,"unit":"g"},{"name":"swede","quantity":100,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"butter","quantity":20,"unit":"g"}]',
  1,
  580,
  28,
  52,
  30,
  4,
  4,
  620,
  '["wheat","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'scotch egg',
  'Scotch Egg',
  '[{"name":"hard-boiled eggs","quantity":4,"unit":"pieces"},{"name":"sausage meat","quantity":400,"unit":"g"},{"name":"breadcrumbs","quantity":100,"unit":"g"},{"name":"flour","quantity":50,"unit":"g"},{"name":"egg wash","quantity":2,"unit":"pieces"},{"name":"vegetable oil","quantity":500,"unit":"ml"}]',
  1,
  380,
  22,
  18,
  26,
  1,
  1,
  580,
  '["wheat","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'yorkshire pudding',
  'Yorkshire Pudding',
  '[{"name":"flour","quantity":150,"unit":"g"},{"name":"eggs","quantity":3,"unit":"pieces"},{"name":"milk","quantity":200,"unit":"ml"},{"name":"beef dripping","quantity":40,"unit":"g"}]',
  1,
  180,
  7,
  22,
  8,
  1,
  2,
  120,
  '["wheat","egg","milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'ploughman s lunch',
  'Ploughman''s Lunch',
  '[{"name":"cheddar cheese","quantity":100,"unit":"g"},{"name":"crusty bread","quantity":100,"unit":"g"},{"name":"pickled onions","quantity":60,"unit":"g"},{"name":"Branston pickle","quantity":40,"unit":"g"},{"name":"ham","quantity":80,"unit":"g"},{"name":"apple","quantity":1,"unit":"piece"},{"name":"butter","quantity":20,"unit":"g"}]',
  1,
  620,
  28,
  48,
  36,
  4,
  18,
  1280,
  '["wheat","milk"]',
  '["high_fructan","high_lactose","high_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'welsh rarebit',
  'Welsh Rarebit',
  '[{"name":"cheddar cheese","quantity":200,"unit":"g"},{"name":"toast","quantity":2,"unit":"slices"},{"name":"beer","quantity":60,"unit":"ml"},{"name":"Worcestershire sauce","quantity":10,"unit":"ml"},{"name":"mustard","quantity":10,"unit":"g"},{"name":"egg yolk","quantity":1,"unit":"piece"}]',
  1,
  480,
  24,
  28,
  32,
  2,
  3,
  920,
  '["wheat","milk","egg","fish"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tea sandwiches',
  'Tea Sandwiches',
  '[{"name":"white bread","quantity":8,"unit":"slices"},{"name":"cucumber","quantity":100,"unit":"g"},{"name":"smoked salmon","quantity":80,"unit":"g"},{"name":"egg salad","quantity":100,"unit":"g"},{"name":"cream cheese","quantity":60,"unit":"g"},{"name":"butter","quantity":40,"unit":"g"}]',
  1,
  420,
  18,
  38,
  24,
  2,
  4,
  680,
  '["wheat","fish","egg","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sticky toffee pudding',
  'Sticky Toffee Pudding',
  '[{"name":"dates","quantity":200,"unit":"g"},{"name":"flour","quantity":180,"unit":"g"},{"name":"butter","quantity":100,"unit":"g"},{"name":"brown sugar","quantity":150,"unit":"g"},{"name":"eggs","quantity":2,"unit":"pieces"},{"name":"toffee sauce","quantity":200,"unit":"ml"},{"name":"cream","quantity":100,"unit":"ml"}]',
  1,
  520,
  6,
  72,
  24,
  3,
  52,
  280,
  '["wheat","egg","milk"]',
  '["high_fructan","high_fructose","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'trifle',
  'Trifle',
  '[{"name":"sponge cake","quantity":200,"unit":"g"},{"name":"custard","quantity":300,"unit":"ml"},{"name":"whipped cream","quantity":200,"unit":"ml"},{"name":"mixed berries","quantity":200,"unit":"g"},{"name":"sherry","quantity":60,"unit":"ml"},{"name":"jam","quantity":60,"unit":"g"}]',
  1,
  420,
  8,
  52,
  20,
  2,
  38,
  140,
  '["wheat","egg","milk"]',
  '["high_fructan","high_lactose","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'scones with clotted cream',
  'Scones with Clotted Cream',
  '[{"name":"flour","quantity":350,"unit":"g"},{"name":"butter","quantity":80,"unit":"g"},{"name":"milk","quantity":150,"unit":"ml"},{"name":"clotted cream","quantity":100,"unit":"g"},{"name":"strawberry jam","quantity":80,"unit":"g"},{"name":"sugar","quantity":40,"unit":"g"}]',
  1,
  480,
  8,
  58,
  26,
  2,
  22,
  380,
  '["wheat","milk"]',
  '["high_fructan","high_lactose","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'eton mess',
  'Eton Mess',
  '[{"name":"meringue","quantity":100,"unit":"g"},{"name":"whipped cream","quantity":300,"unit":"ml"},{"name":"strawberries","quantity":300,"unit":"g"},{"name":"vanilla extract","quantity":5,"unit":"ml"}]',
  1,
  380,
  4,
  42,
  22,
  2,
  38,
  60,
  '["egg","milk"]',
  '["high_lactose","high_fructose"]',
  '["gluten-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'banoffee pie',
  'Banoffee Pie',
  '[{"name":"digestive biscuits","quantity":250,"unit":"g"},{"name":"butter","quantity":120,"unit":"g"},{"name":"dulce de leche","quantity":400,"unit":"g"},{"name":"bananas","quantity":3,"unit":"pieces"},{"name":"whipped cream","quantity":300,"unit":"ml"},{"name":"dark chocolate","quantity":30,"unit":"g"}]',
  1,
  520,
  6,
  62,
  28,
  2,
  48,
  320,
  '["wheat","milk"]',
  '["high_fructan","high_lactose","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');
