INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'turkish tea',
  'Turkish Tea',
  '[{"name":"black tea","quantity":15,"unit":"g"},{"name":"sugar","quantity":15,"unit":"g"},{"name":"hot water","quantity":300,"unit":"ml"}]',
  1,
  60,
  0,
  15,
  0,
  0,
  15,
  5,
  '[]',
  '[]',
  '["vegan","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'gyro',
  'Gyro',
  '[{"name":"pork shoulder","quantity":400,"unit":"g"},{"name":"pita bread","quantity":2,"unit":"pieces"},{"name":"tzatziki","quantity":80,"unit":"ml"},{"name":"tomatoes","quantity":80,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"paprika","quantity":5,"unit":"g"},{"name":"oregano","quantity":3,"unit":"g"},{"name":"french fries","quantity":100,"unit":"g"}]',
  1,
  620,
  38,
  48,
  32,
  3,
  5,
  820,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'souvlaki',
  'Souvlaki',
  '[{"name":"chicken breast","quantity":400,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"lemon juice","quantity":30,"unit":"ml"},{"name":"oregano","quantity":5,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"pita bread","quantity":2,"unit":"pieces"},{"name":"tzatziki","quantity":60,"unit":"ml"}]',
  1,
  480,
  45,
  32,
  20,
  2,
  4,
  620,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'moussaka',
  'Moussaka',
  '[{"name":"eggplant","quantity":400,"unit":"g"},{"name":"ground lamb","quantity":300,"unit":"g"},{"name":"potatoes","quantity":200,"unit":"g"},{"name":"tomato sauce","quantity":200,"unit":"ml"},{"name":"béchamel sauce","quantity":250,"unit":"ml"},{"name":"onion","quantity":100,"unit":"g"},{"name":"cinnamon","quantity":3,"unit":"g"},{"name":"parmesan","quantity":50,"unit":"g"}]',
  1,
  520,
  28,
  32,
  34,
  6,
  10,
  680,
  '["milk","wheat"]',
  '["high_fructan","high_lactose","high_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pastitsio',
  'Pastitsio',
  '[{"name":"bucatini pasta","quantity":400,"unit":"g"},{"name":"ground beef","quantity":400,"unit":"g"},{"name":"tomato sauce","quantity":200,"unit":"ml"},{"name":"béchamel sauce","quantity":300,"unit":"ml"},{"name":"onion","quantity":100,"unit":"g"},{"name":"cinnamon","quantity":3,"unit":"g"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"cheese","quantity":80,"unit":"g"}]',
  1,
  580,
  32,
  52,
  28,
  3,
  8,
  720,
  '["wheat","milk","egg"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kleftiko',
  'Kleftiko',
  '[{"name":"lamb shoulder","quantity":800,"unit":"g"},{"name":"potatoes","quantity":400,"unit":"g"},{"name":"garlic","quantity":20,"unit":"g"},{"name":"lemon juice","quantity":50,"unit":"ml"},{"name":"oregano","quantity":8,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"},{"name":"feta cheese","quantity":80,"unit":"g"}]',
  1,
  620,
  48,
  28,
  38,
  3,
  2,
  580,
  '["milk"]',
  '["high_fructan","high_lactose"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bifteki',
  'Bifteki',
  '[{"name":"ground beef","quantity":400,"unit":"g"},{"name":"feta cheese","quantity":80,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"breadcrumbs","quantity":40,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"oregano","quantity":5,"unit":"g"},{"name":"mint","quantity":10,"unit":"g"}]',
  1,
  420,
  35,
  12,
  28,
  1,
  2,
  580,
  '["wheat","milk","egg"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'spanakopita',
  'Spanakopita',
  '[{"name":"phyllo dough","quantity":300,"unit":"g"},{"name":"spinach","quantity":500,"unit":"g"},{"name":"feta cheese","quantity":200,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"dill","quantity":20,"unit":"g"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"olive oil","quantity":60,"unit":"ml"}]',
  1,
  380,
  14,
  28,
  26,
  4,
  3,
  620,
  '["wheat","milk","egg"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tiropita',
  'Tiropita',
  '[{"name":"phyllo dough","quantity":300,"unit":"g"},{"name":"feta cheese","quantity":300,"unit":"g"},{"name":"ricotta cheese","quantity":150,"unit":"g"},{"name":"egg","quantity":3,"unit":"whole"},{"name":"butter","quantity":80,"unit":"g"},{"name":"mint","quantity":10,"unit":"g"}]',
  1,
  420,
  18,
  26,
  30,
  1,
  2,
  720,
  '["wheat","milk","egg"]',
  '["high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'greek salad',
  'Greek Salad',
  '[{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"cucumber","quantity":150,"unit":"g"},{"name":"red onion","quantity":60,"unit":"g"},{"name":"feta cheese","quantity":100,"unit":"g"},{"name":"kalamata olives","quantity":60,"unit":"g"},{"name":"bell peppers","quantity":80,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"oregano","quantity":3,"unit":"g"}]',
  1,
  320,
  10,
  14,
  26,
  4,
  8,
  680,
  '["milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tzatziki',
  'Tzatziki',
  '[{"name":"greek yogurt","quantity":400,"unit":"g"},{"name":"cucumber","quantity":150,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"dill","quantity":15,"unit":"g"},{"name":"lemon juice","quantity":20,"unit":"ml"}]',
  1,
  180,
  12,
  10,
  12,
  1,
  8,
  420,
  '["milk"]',
  '["high_lactose","high_fructan"]',
  '["vegetarian","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'greek dolmades',
  'Greek Dolmades',
  '[{"name":"grape leaves","quantity":30,"unit":"leaves"},{"name":"rice","quantity":200,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"dill","quantity":20,"unit":"g"},{"name":"mint","quantity":15,"unit":"g"},{"name":"pine nuts","quantity":30,"unit":"g"},{"name":"lemon juice","quantity":50,"unit":"ml"},{"name":"olive oil","quantity":60,"unit":"ml"}]',
  1,
  280,
  5,
  38,
  12,
  3,
  3,
  380,
  '["tree_nut"]',
  '["high_fructan"]',
  '["vegan","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'saganaki',
  'Saganaki',
  '[{"name":"kefalograviera cheese","quantity":200,"unit":"g"},{"name":"flour","quantity":30,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"lemon juice","quantity":20,"unit":"ml"}]',
  1,
  420,
  22,
  8,
  34,
  0,
  1,
  680,
  '["milk","wheat"]',
  '["high_lactose"]',
  '["vegetarian","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'greek calamari',
  'Greek Calamari',
  '[{"name":"squid","quantity":400,"unit":"g"},{"name":"flour","quantity":100,"unit":"g"},{"name":"olive oil","quantity":150,"unit":"ml"},{"name":"lemon juice","quantity":40,"unit":"ml"},{"name":"oregano","quantity":3,"unit":"g"}]',
  1,
  380,
  28,
  26,
  20,
  1,
  1,
  520,
  '["wheat","mollusk"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'grilled octopus',
  'Grilled Octopus',
  '[{"name":"octopus","quantity":500,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"},{"name":"red wine vinegar","quantity":30,"unit":"ml"},{"name":"oregano","quantity":5,"unit":"g"},{"name":"lemon juice","quantity":40,"unit":"ml"}]',
  1,
  280,
  36,
  4,
  14,
  0,
  1,
  520,
  '["mollusk"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'avgolemono soup',
  'Avgolemono Soup',
  '[{"name":"chicken broth","quantity":1000,"unit":"ml"},{"name":"chicken breast","quantity":200,"unit":"g"},{"name":"orzo pasta","quantity":100,"unit":"g"},{"name":"eggs","quantity":3,"unit":"whole"},{"name":"lemon juice","quantity":80,"unit":"ml"},{"name":"dill","quantity":15,"unit":"g"}]',
  1,
  320,
  28,
  28,
  12,
  1,
  2,
  680,
  '["wheat","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'fasolada',
  'Fasolada',
  '[{"name":"white beans","quantity":300,"unit":"g"},{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"carrots","quantity":100,"unit":"g"},{"name":"celery","quantity":80,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"}]',
  1,
  320,
  16,
  48,
  10,
  14,
  8,
  380,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'greek baklava',
  'Greek Baklava',
  '[{"name":"phyllo dough","quantity":400,"unit":"g"},{"name":"walnuts","quantity":300,"unit":"g"},{"name":"butter","quantity":200,"unit":"g"},{"name":"honey","quantity":200,"unit":"g"},{"name":"cinnamon","quantity":5,"unit":"g"}]',
  1,
  480,
  8,
  52,
  28,
  2,
  35,
  180,
  '["wheat","milk","tree_nut"]',
  '["high_fructan","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'loukoumades',
  'Loukoumades',
  '[{"name":"flour","quantity":300,"unit":"g"},{"name":"yeast","quantity":7,"unit":"g"},{"name":"honey","quantity":100,"unit":"g"},{"name":"vegetable oil","quantity":200,"unit":"ml"},{"name":"cinnamon","quantity":5,"unit":"g"},{"name":"walnuts","quantity":40,"unit":"g"}]',
  1,
  380,
  6,
  58,
  14,
  2,
  28,
  120,
  '["wheat","tree_nut"]',
  '["high_fructan","high_fructose"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'galaktoboureko',
  'Galaktoboureko',
  '[{"name":"phyllo dough","quantity":300,"unit":"g"},{"name":"milk","quantity":1000,"unit":"ml"},{"name":"semolina","quantity":150,"unit":"g"},{"name":"sugar","quantity":200,"unit":"g"},{"name":"eggs","quantity":4,"unit":"whole"},{"name":"butter","quantity":100,"unit":"g"},{"name":"vanilla","quantity":5,"unit":"ml"}]',
  1,
  420,
  10,
  58,
  18,
  1,
  38,
  220,
  '["wheat","milk","egg"]',
  '["high_lactose","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'feta and olives mezze',
  'Feta and Olives Mezze',
  '[{"name":"feta cheese","quantity":200,"unit":"g"},{"name":"kalamata olives","quantity":100,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"oregano","quantity":3,"unit":"g"},{"name":"pita bread","quantity":100,"unit":"g"}]',
  1,
  420,
  16,
  24,
  32,
  3,
  4,
  920,
  '["milk","wheat"]',
  '["high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'croissant',
  'Croissant',
  '[{"name":"flour","quantity":500,"unit":"g"},{"name":"butter","quantity":280,"unit":"g"},{"name":"milk","quantity":140,"unit":"ml"},{"name":"sugar","quantity":50,"unit":"g"},{"name":"yeast","quantity":10,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"}]',
  1,
  320,
  6,
  36,
  18,
  1,
  6,
  320,
  '["wheat","milk","egg"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'baguette with butter',
  'Baguette with Butter',
  '[{"name":"baguette","quantity":150,"unit":"g"},{"name":"butter","quantity":40,"unit":"g"}]',
  1,
  420,
  10,
  58,
  16,
  2,
  2,
  580,
  '["wheat","milk"]',
  '["high_fructan"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'french onion soup',
  'French Onion Soup',
  '[{"name":"onions","quantity":600,"unit":"g"},{"name":"beef broth","quantity":1000,"unit":"ml"},{"name":"baguette","quantity":100,"unit":"g"},{"name":"gruyère cheese","quantity":150,"unit":"g"},{"name":"butter","quantity":50,"unit":"g"},{"name":"white wine","quantity":100,"unit":"ml"}]',
  1,
  420,
  18,
  38,
  22,
  4,
  12,
  920,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bouillabaisse',
  'Bouillabaisse',
  '[{"name":"mixed fish","quantity":600,"unit":"g"},{"name":"mussels","quantity":200,"unit":"g"},{"name":"shrimp","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"fennel","quantity":100,"unit":"g"},{"name":"saffron","quantity":0.5,"unit":"g"},{"name":"garlic","quantity":20,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"}]',
  1,
  380,
  42,
  14,
  16,
  3,
  6,
  720,
  '["fish","shellfish","mollusk"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'coq au vin',
  'Coq au Vin',
  '[{"name":"chicken","quantity":1200,"unit":"g"},{"name":"red wine","quantity":500,"unit":"ml"},{"name":"bacon","quantity":150,"unit":"g"},{"name":"mushrooms","quantity":200,"unit":"g"},{"name":"pearl onions","quantity":150,"unit":"g"},{"name":"carrots","quantity":100,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"butter","quantity":50,"unit":"g"}]',
  1,
  520,
  42,
  12,
  32,
  2,
  6,
  680,
  '["milk"]',
  '["high_fructan","high_polyol"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'beef bourguignon',
  'Beef Bourguignon',
  '[{"name":"beef chuck","quantity":800,"unit":"g"},{"name":"red wine","quantity":500,"unit":"ml"},{"name":"bacon","quantity":150,"unit":"g"},{"name":"mushrooms","quantity":200,"unit":"g"},{"name":"pearl onions","quantity":150,"unit":"g"},{"name":"carrots","quantity":150,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"beef broth","quantity":250,"unit":"ml"}]',
  1,
  580,
  48,
  16,
  32,
  3,
  8,
  720,
  '[]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'steak frites',
  'Steak Frites',
  '[{"name":"ribeye steak","quantity":300,"unit":"g"},{"name":"potatoes","quantity":300,"unit":"g"},{"name":"butter","quantity":50,"unit":"g"},{"name":"shallots","quantity":40,"unit":"g"},{"name":"red wine","quantity":100,"unit":"ml"},{"name":"vegetable oil","quantity":150,"unit":"ml"}]',
  1,
  720,
  45,
  42,
  44,
  4,
  2,
  480,
  '["milk"]',
  '["high_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'duck confit',
  'Duck Confit',
  '[{"name":"duck legs","quantity":600,"unit":"g"},{"name":"duck fat","quantity":400,"unit":"g"},{"name":"garlic","quantity":20,"unit":"g"},{"name":"thyme","quantity":10,"unit":"g"},{"name":"bay leaves","quantity":3,"unit":"leaves"},{"name":"coarse salt","quantity":30,"unit":"g"}]',
  1,
  580,
  38,
  2,
  48,
  0,
  0,
  620,
  '[]',
  '["high_fructan"]',
  '["dairy-free","gluten-free","low-carb","keto-friendly"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'cassoulet',
  'Cassoulet',
  '[{"name":"white beans","quantity":400,"unit":"g"},{"name":"duck confit","quantity":300,"unit":"g"},{"name":"toulouse sausage","quantity":200,"unit":"g"},{"name":"pork belly","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":150,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"}]',
  1,
  680,
  42,
  48,
  38,
  12,
  6,
  920,
  '["wheat"]',
  '["high_gos","high_fructan"]',
  '["dairy-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'ratatouille',
  'Ratatouille',
  '[{"name":"eggplant","quantity":200,"unit":"g"},{"name":"zucchini","quantity":200,"unit":"g"},{"name":"bell peppers","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":300,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"},{"name":"herbes de provence","quantity":10,"unit":"g"}]',
  1,
  220,
  4,
  22,
  14,
  7,
  14,
  280,
  '[]',
  '["high_fructan","high_polyol"]',
  '["vegan","dairy-free","gluten-free","low-calorie"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'quiche lorraine',
  'Quiche Lorraine',
  '[{"name":"pie crust","quantity":200,"unit":"g"},{"name":"bacon","quantity":150,"unit":"g"},{"name":"gruyère cheese","quantity":150,"unit":"g"},{"name":"eggs","quantity":3,"unit":"whole"},{"name":"heavy cream","quantity":200,"unit":"ml"},{"name":"milk","quantity":100,"unit":"ml"}]',
  1,
  480,
  18,
  24,
  36,
  1,
  3,
  680,
  '["wheat","milk","egg"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'nicoise salad',
  'Niçoise Salad',
  '[{"name":"tuna","quantity":200,"unit":"g"},{"name":"green beans","quantity":150,"unit":"g"},{"name":"potatoes","quantity":150,"unit":"g"},{"name":"eggs","quantity":2,"unit":"whole"},{"name":"tomatoes","quantity":150,"unit":"g"},{"name":"niçoise olives","quantity":60,"unit":"g"},{"name":"anchovies","quantity":30,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"}]',
  1,
  420,
  32,
  24,
  24,
  5,
  5,
  680,
  '["fish","egg"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sweet crepes',
  'Sweet Crêpes',
  '[{"name":"flour","quantity":250,"unit":"g"},{"name":"eggs","quantity":3,"unit":"whole"},{"name":"milk","quantity":500,"unit":"ml"},{"name":"butter","quantity":50,"unit":"g"},{"name":"sugar","quantity":30,"unit":"g"},{"name":"nutella","quantity":60,"unit":"g"},{"name":"strawberries","quantity":80,"unit":"g"}]',
  1,
  380,
  10,
  52,
  16,
  2,
  24,
  180,
  '["wheat","milk","egg","tree_nut"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'savory galette',
  'Savory Galette',
  '[{"name":"buckwheat flour","quantity":200,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"ham","quantity":80,"unit":"g"},{"name":"gruyère cheese","quantity":80,"unit":"g"},{"name":"butter","quantity":30,"unit":"g"}]',
  1,
  420,
  22,
  38,
  22,
  4,
  2,
  680,
  '["egg","milk"]',
  '["high_lactose"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'escargots',
  'Escargots',
  '[{"name":"snails","quantity":12,"unit":"pieces"},{"name":"butter","quantity":100,"unit":"g"},{"name":"garlic","quantity":30,"unit":"g"},{"name":"parsley","quantity":30,"unit":"g"},{"name":"shallots","quantity":30,"unit":"g"}]',
  1,
  320,
  14,
  4,
  28,
  1,
  1,
  480,
  '["milk","mollusk"]',
  '["high_fructan"]',
  '["gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'creme brulee',
  'Crème Brûlée',
  '[{"name":"heavy cream","quantity":500,"unit":"ml"},{"name":"egg yolks","quantity":6,"unit":"whole"},{"name":"sugar","quantity":100,"unit":"g"},{"name":"vanilla bean","quantity":1,"unit":"piece"}]',
  1,
  380,
  6,
  28,
  28,
  0,
  26,
  60,
  '["milk","egg"]',
  '["high_lactose"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'macarons',
  'Macarons',
  '[{"name":"almond flour","quantity":150,"unit":"g"},{"name":"powdered sugar","quantity":150,"unit":"g"},{"name":"egg whites","quantity":100,"unit":"g"},{"name":"sugar","quantity":150,"unit":"g"},{"name":"butter","quantity":100,"unit":"g"}]',
  1,
  180,
  3,
  28,
  8,
  1,
  24,
  20,
  '["tree_nut","egg","milk"]',
  '["high_gos"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tarte tatin',
  'Tarte Tatin',
  '[{"name":"apples","quantity":800,"unit":"g"},{"name":"puff pastry","quantity":250,"unit":"g"},{"name":"butter","quantity":100,"unit":"g"},{"name":"sugar","quantity":150,"unit":"g"},{"name":"cinnamon","quantity":3,"unit":"g"}]',
  1,
  380,
  4,
  52,
  18,
  3,
  38,
  180,
  '["wheat","milk"]',
  '["high_fructose","high_polyol"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'profiteroles',
  'Profiteroles',
  '[{"name":"choux pastry","quantity":200,"unit":"g"},{"name":"vanilla ice cream","quantity":300,"unit":"g"},{"name":"chocolate sauce","quantity":150,"unit":"ml"},{"name":"whipped cream","quantity":100,"unit":"ml"}]',
  1,
  420,
  8,
  48,
  24,
  2,
  36,
  180,
  '["wheat","milk","egg"]',
  '["high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'french cheese plate',
  'French Cheese Plate',
  '[{"name":"brie","quantity":80,"unit":"g"},{"name":"camembert","quantity":80,"unit":"g"},{"name":"roquefort","quantity":60,"unit":"g"},{"name":"comté","quantity":60,"unit":"g"},{"name":"grapes","quantity":80,"unit":"g"},{"name":"walnuts","quantity":40,"unit":"g"},{"name":"baguette","quantity":100,"unit":"g"}]',
  1,
  580,
  28,
  28,
  42,
  2,
  8,
  980,
  '["milk","wheat","tree_nut"]',
  '["high_lactose","high_fructan"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'paella',
  'Paella',
  '[{"name":"bomba rice","quantity":300,"unit":"g"},{"name":"chicken thighs","quantity":300,"unit":"g"},{"name":"shrimp","quantity":200,"unit":"g"},{"name":"mussels","quantity":150,"unit":"g"},{"name":"chorizo","quantity":100,"unit":"g"},{"name":"saffron","quantity":0.5,"unit":"g"},{"name":"bell peppers","quantity":100,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"},{"name":"chicken broth","quantity":600,"unit":"ml"}]',
  1,
  580,
  38,
  52,
  24,
  3,
  5,
  920,
  '["shellfish","mollusk"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tortilla espanola',
  'Tortilla Española',
  '[{"name":"eggs","quantity":6,"unit":"whole"},{"name":"potatoes","quantity":500,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"olive oil","quantity":200,"unit":"ml"},{"name":"salt","quantity":5,"unit":"g"}]',
  1,
  320,
  12,
  28,
  20,
  3,
  3,
  380,
  '["egg"]',
  '["high_fructan"]',
  '["vegetarian","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'fabada asturiana',
  'Fabada Asturiana',
  '[{"name":"white beans","quantity":400,"unit":"g"},{"name":"chorizo","quantity":150,"unit":"g"},{"name":"morcilla","quantity":100,"unit":"g"},{"name":"pork shoulder","quantity":200,"unit":"g"},{"name":"saffron","quantity":0.3,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"}]',
  1,
  620,
  38,
  48,
  32,
  14,
  4,
  920,
  '[]',
  '["high_gos","high_fructan"]',
  '["dairy-free","gluten-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bacalao a la vizcaina',
  'Bacalao a la Vizcaína',
  '[{"name":"salt cod","quantity":500,"unit":"g"},{"name":"dried peppers","quantity":100,"unit":"g"},{"name":"onion","quantity":200,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"olive oil","quantity":80,"unit":"ml"}]',
  1,
  380,
  42,
  16,
  18,
  3,
  8,
  1200,
  '["fish"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'conejo al ajillo',
  'Conejo al Ajillo',
  '[{"name":"rabbit","quantity":800,"unit":"g"},{"name":"garlic","quantity":40,"unit":"g"},{"name":"white wine","quantity":150,"unit":"ml"},{"name":"olive oil","quantity":80,"unit":"ml"},{"name":"rosemary","quantity":10,"unit":"g"}]',
  1,
  420,
  48,
  4,
  24,
  1,
  1,
  420,
  '[]',
  '["high_fructan"]',
  '["dairy-free","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'patatas bravas',
  'Patatas Bravas',
  '[{"name":"potatoes","quantity":500,"unit":"g"},{"name":"tomato sauce","quantity":150,"unit":"ml"},{"name":"mayonnaise","quantity":60,"unit":"ml"},{"name":"paprika","quantity":10,"unit":"g"},{"name":"cayenne","quantity":3,"unit":"g"},{"name":"olive oil","quantity":100,"unit":"ml"}]',
  1,
  380,
  5,
  42,
  22,
  4,
  5,
  480,
  '["egg"]',
  '["high_fructan"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'jamon iberico',
  'Jamón Ibérico',
  '[{"name":"ibérico ham","quantity":100,"unit":"g"},{"name":"bread","quantity":60,"unit":"g"},{"name":"olive oil","quantity":15,"unit":"ml"}]',
  1,
  320,
  24,
  18,
  18,
  1,
  1,
  1100,
  '["wheat"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'croquetas',
  'Croquetas',
  '[{"name":"flour","quantity":60,"unit":"g"},{"name":"butter","quantity":60,"unit":"g"},{"name":"milk","quantity":400,"unit":"ml"},{"name":"serrano ham","quantity":100,"unit":"g"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"breadcrumbs","quantity":100,"unit":"g"},{"name":"vegetable oil","quantity":200,"unit":"ml"}]',
  1,
  280,
  12,
  22,
  18,
  1,
  3,
  520,
  '["wheat","milk","egg"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pimientos de padron',
  'Pimientos de Padrón',
  '[{"name":"padrón peppers","quantity":250,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"sea salt","quantity":5,"unit":"g"}]',
  1,
  120,
  2,
  6,
  10,
  2,
  3,
  480,
  '[]',
  '[]',
  '["vegan","dairy-free","gluten-free","low-calorie","keto-friendly"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');
