INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'wonton soup',
  'Wonton Soup',
  '[{"name":"ground pork","quantity":200,"unit":"g"},{"name":"shrimp","quantity":100,"unit":"g"},{"name":"wonton wrappers","quantity":200,"unit":"g"},{"name":"chicken broth","quantity":800,"unit":"ml"},{"name":"bok choy","quantity":100,"unit":"g"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"green onion","quantity":30,"unit":"g"},{"name":"sesame oil","quantity":10,"unit":"ml"}]',
  1,
  320,
  25,
  32,
  12,
  2,
  2,
  920,
  '["gluten","shellfish","soy","sesame"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chow mein',
  'Chow Mein',
  '[{"name":"egg noodles","quantity":250,"unit":"g"},{"name":"chicken breast","quantity":150,"unit":"g"},{"name":"bean sprouts","quantity":100,"unit":"g"},{"name":"cabbage","quantity":100,"unit":"g"},{"name":"carrot","quantity":50,"unit":"g"},{"name":"soy sauce","quantity":30,"unit":"ml"},{"name":"oyster sauce","quantity":20,"unit":"ml"},{"name":"sesame oil","quantity":10,"unit":"ml"},{"name":"garlic","quantity":3,"unit":"cloves"}]',
  1,
  480,
  28,
  58,
  16,
  4,
  6,
  1050,
  '["gluten","egg","soy","shellfish","sesame"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'lo mein',
  'Lo Mein',
  '[{"name":"lo mein noodles","quantity":250,"unit":"g"},{"name":"beef","quantity":150,"unit":"g"},{"name":"bok choy","quantity":100,"unit":"g"},{"name":"mushrooms","quantity":80,"unit":"g"},{"name":"soy sauce","quantity":40,"unit":"ml"},{"name":"oyster sauce","quantity":25,"unit":"ml"},{"name":"sesame oil","quantity":15,"unit":"ml"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"ginger","quantity":10,"unit":"g"}]',
  1,
  520,
  30,
  60,
  18,
  3,
  5,
  1120,
  '["gluten","soy","shellfish","sesame"]',
  '["high_fructan","high_mannitol"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'dan dan noodles',
  'Dan Dan Noodles',
  '[{"name":"wheat noodles","quantity":250,"unit":"g"},{"name":"ground pork","quantity":150,"unit":"g"},{"name":"preserved vegetables","quantity":30,"unit":"g"},{"name":"sesame paste","quantity":40,"unit":"g"},{"name":"chili oil","quantity":30,"unit":"ml"},{"name":"soy sauce","quantity":25,"unit":"ml"},{"name":"Sichuan peppercorns","quantity":5,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"green onion","quantity":20,"unit":"g"}]',
  1,
  580,
  28,
  55,
  28,
  3,
  4,
  1080,
  '["gluten","soy","sesame"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'yangzhou fried rice',
  'Yangzhou Fried Rice',
  '[{"name":"jasmine rice","quantity":400,"unit":"g"},{"name":"char siu pork","quantity":100,"unit":"g"},{"name":"shrimp","quantity":100,"unit":"g"},{"name":"egg","quantity":3,"unit":"whole"},{"name":"peas","quantity":50,"unit":"g"},{"name":"carrot","quantity":50,"unit":"g"},{"name":"green onion","quantity":30,"unit":"g"},{"name":"soy sauce","quantity":20,"unit":"ml"},{"name":"sesame oil","quantity":10,"unit":"ml"}]',
  1,
  520,
  28,
  65,
  16,
  3,
  4,
  820,
  '["shellfish","egg","soy","sesame"]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'beef with broccoli',
  'Beef with Broccoli',
  '[{"name":"beef sirloin","quantity":300,"unit":"g"},{"name":"broccoli florets","quantity":250,"unit":"g"},{"name":"soy sauce","quantity":45,"unit":"ml"},{"name":"oyster sauce","quantity":30,"unit":"ml"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"ginger","quantity":15,"unit":"g"},{"name":"cornstarch","quantity":15,"unit":"g"},{"name":"sesame oil","quantity":10,"unit":"ml"}]',
  1,
  420,
  38,
  22,
  22,
  5,
  6,
  1180,
  '["soy","shellfish","sesame"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sichuan boiled fish',
  'Sichuan Boiled Fish',
  '[{"name":"white fish fillets","quantity":400,"unit":"g"},{"name":"dried chilies","quantity":30,"unit":"g"},{"name":"Sichuan peppercorns","quantity":15,"unit":"g"},{"name":"doubanjiang","quantity":40,"unit":"g"},{"name":"bean sprouts","quantity":150,"unit":"g"},{"name":"napa cabbage","quantity":150,"unit":"g"},{"name":"garlic","quantity":6,"unit":"cloves"},{"name":"ginger","quantity":15,"unit":"g"},{"name":"vegetable oil","quantity":100,"unit":"ml"}]',
  1,
  480,
  38,
  12,
  32,
  3,
  4,
  1050,
  '["fish","soy"]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'egg foo young',
  'Egg Foo Young',
  '[{"name":"egg","quantity":6,"unit":"whole"},{"name":"bean sprouts","quantity":100,"unit":"g"},{"name":"char siu pork","quantity":80,"unit":"g"},{"name":"green onion","quantity":30,"unit":"g"},{"name":"mushrooms","quantity":60,"unit":"g"},{"name":"soy sauce","quantity":20,"unit":"ml"},{"name":"oyster sauce","quantity":30,"unit":"ml"},{"name":"chicken broth","quantity":150,"unit":"ml"},{"name":"cornstarch","quantity":10,"unit":"g"}]',
  1,
  380,
  28,
  15,
  24,
  2,
  4,
  920,
  '["egg","soy","shellfish"]',
  '["high_fructan","high_mannitol"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'spring rolls',
  'Spring Rolls',
  '[{"name":"spring roll wrappers","quantity":200,"unit":"g"},{"name":"cabbage","quantity":150,"unit":"g"},{"name":"carrot","quantity":80,"unit":"g"},{"name":"bean sprouts","quantity":80,"unit":"g"},{"name":"ground pork","quantity":100,"unit":"g"},{"name":"glass noodles","quantity":50,"unit":"g"},{"name":"soy sauce","quantity":15,"unit":"ml"},{"name":"vegetable oil","quantity":200,"unit":"ml"}]',
  1,
  320,
  12,
  35,
  16,
  3,
  4,
  580,
  '["gluten","soy"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'mooncakes',
  'Mooncakes',
  '[{"name":"lotus seed paste","quantity":300,"unit":"g"},{"name":"flour","quantity":200,"unit":"g"},{"name":"golden syrup","quantity":100,"unit":"ml"},{"name":"vegetable oil","quantity":50,"unit":"ml"},{"name":"salted egg yolks","quantity":4,"unit":"pieces"},{"name":"lye water","quantity":5,"unit":"ml"}]',
  1,
  450,
  8,
  65,
  18,
  2,
  42,
  280,
  '["gluten","egg"]',
  '["high_fructan"]',
  '["dairy-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'nigiri sushi',
  'Nigiri Sushi',
  '[{"name":"sushi rice","quantity":200,"unit":"g"},{"name":"fresh salmon","quantity":80,"unit":"g"},{"name":"fresh tuna","quantity":80,"unit":"g"},{"name":"shrimp","quantity":60,"unit":"g"},{"name":"rice vinegar","quantity":30,"unit":"ml"},{"name":"sugar","quantity":15,"unit":"g"},{"name":"wasabi","quantity":5,"unit":"g"},{"name":"soy sauce","quantity":30,"unit":"ml"},{"name":"pickled ginger","quantity":20,"unit":"g"}]',
  1,
  380,
  28,
  48,
  8,
  1,
  8,
  720,
  '["fish","shellfish","soy"]',
  '["low"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sashimi',
  'Sashimi',
  '[{"name":"fresh salmon","quantity":100,"unit":"g"},{"name":"fresh tuna","quantity":100,"unit":"g"},{"name":"yellowtail","quantity":80,"unit":"g"},{"name":"wasabi","quantity":8,"unit":"g"},{"name":"soy sauce","quantity":30,"unit":"ml"},{"name":"pickled ginger","quantity":20,"unit":"g"},{"name":"daikon radish","quantity":50,"unit":"g"},{"name":"shiso leaves","quantity":5,"unit":"pieces"}]',
  1,
  280,
  42,
  6,
  10,
  1,
  3,
  680,
  '["fish","soy"]',
  '["low"]',
  '["dairy-free","gluten-free","keto","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'maki rolls',
  'Maki Rolls',
  '[{"name":"sushi rice","quantity":250,"unit":"g"},{"name":"nori sheets","quantity":4,"unit":"pieces"},{"name":"fresh salmon","quantity":100,"unit":"g"},{"name":"cucumber","quantity":80,"unit":"g"},{"name":"avocado","quantity":80,"unit":"g"},{"name":"cream cheese","quantity":50,"unit":"g"},{"name":"rice vinegar","quantity":30,"unit":"ml"},{"name":"sesame seeds","quantity":10,"unit":"g"},{"name":"soy sauce","quantity":30,"unit":"ml"}]',
  1,
  450,
  22,
  55,
  16,
  4,
  6,
  780,
  '["fish","milk","soy","sesame"]',
  '["moderate_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tonkotsu ramen',
  'Tonkotsu Ramen',
  '[{"name":"ramen noodles","quantity":200,"unit":"g"},{"name":"pork belly","quantity":100,"unit":"g"},{"name":"tonkotsu broth","quantity":500,"unit":"ml"},{"name":"soft-boiled egg","quantity":1,"unit":"whole"},{"name":"green onion","quantity":20,"unit":"g"},{"name":"nori","quantity":2,"unit":"sheets"},{"name":"bamboo shoots","quantity":30,"unit":"g"},{"name":"garlic oil","quantity":10,"unit":"ml"},{"name":"sesame seeds","quantity":5,"unit":"g"}]',
  1,
  680,
  35,
  65,
  32,
  3,
  4,
  1450,
  '["gluten","egg","sesame"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'shoyu ramen',
  'Shoyu Ramen',
  '[{"name":"ramen noodles","quantity":200,"unit":"g"},{"name":"chashu pork","quantity":80,"unit":"g"},{"name":"soy sauce broth","quantity":500,"unit":"ml"},{"name":"soft-boiled egg","quantity":1,"unit":"whole"},{"name":"green onion","quantity":20,"unit":"g"},{"name":"nori","quantity":2,"unit":"sheets"},{"name":"bamboo shoots","quantity":30,"unit":"g"},{"name":"corn","quantity":30,"unit":"g"}]',
  1,
  580,
  32,
  68,
  20,
  3,
  5,
  1380,
  '["gluten","egg","soy"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'udon',
  'Udon',
  '[{"name":"udon noodles","quantity":250,"unit":"g"},{"name":"dashi broth","quantity":400,"unit":"ml"},{"name":"soy sauce","quantity":30,"unit":"ml"},{"name":"mirin","quantity":20,"unit":"ml"},{"name":"green onion","quantity":20,"unit":"g"},{"name":"tempura flakes","quantity":20,"unit":"g"},{"name":"kamaboko","quantity":30,"unit":"g"}]',
  1,
  420,
  14,
  78,
  6,
  3,
  8,
  1120,
  '["gluten","fish","soy"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'soba',
  'Soba',
  '[{"name":"soba noodles","quantity":200,"unit":"g"},{"name":"dashi broth","quantity":300,"unit":"ml"},{"name":"soy sauce","quantity":30,"unit":"ml"},{"name":"mirin","quantity":20,"unit":"ml"},{"name":"green onion","quantity":20,"unit":"g"},{"name":"wasabi","quantity":5,"unit":"g"},{"name":"nori","quantity":1,"unit":"sheet"}]',
  1,
  350,
  14,
  68,
  3,
  4,
  6,
  980,
  '["gluten","fish","soy"]',
  '["high_fructan"]',
  '["dairy-free","vegan"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tempura',
  'Tempura',
  '[{"name":"shrimp","quantity":150,"unit":"g"},{"name":"sweet potato","quantity":80,"unit":"g"},{"name":"eggplant","quantity":60,"unit":"g"},{"name":"green beans","quantity":50,"unit":"g"},{"name":"tempura flour","quantity":100,"unit":"g"},{"name":"ice water","quantity":150,"unit":"ml"},{"name":"vegetable oil","quantity":200,"unit":"ml"},{"name":"tentsuyu sauce","quantity":60,"unit":"ml"},{"name":"daikon","quantity":30,"unit":"g"}]',
  1,
  480,
  22,
  45,
  24,
  4,
  6,
  680,
  '["shellfish","gluten","soy"]',
  '["high_fructan","moderate_sorbitol"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tonkatsu',
  'Tonkatsu',
  '[{"name":"pork loin","quantity":200,"unit":"g"},{"name":"panko breadcrumbs","quantity":80,"unit":"g"},{"name":"flour","quantity":30,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"cabbage","quantity":100,"unit":"g"},{"name":"tonkatsu sauce","quantity":40,"unit":"ml"},{"name":"vegetable oil","quantity":100,"unit":"ml"},{"name":"rice","quantity":150,"unit":"g"}]',
  1,
  720,
  35,
  65,
  35,
  3,
  8,
  820,
  '["gluten","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken karaage',
  'Chicken Karaage',
  '[{"name":"chicken thigh","quantity":300,"unit":"g"},{"name":"soy sauce","quantity":30,"unit":"ml"},{"name":"sake","quantity":20,"unit":"ml"},{"name":"ginger","quantity":15,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"potato starch","quantity":60,"unit":"g"},{"name":"vegetable oil","quantity":200,"unit":"ml"},{"name":"lemon","quantity":1,"unit":"wedge"}]',
  1,
  450,
  32,
  25,
  26,
  1,
  2,
  780,
  '["soy"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'yakitori',
  'Yakitori',
  '[{"name":"chicken thigh","quantity":300,"unit":"g"},{"name":"chicken skin","quantity":50,"unit":"g"},{"name":"green onion","quantity":60,"unit":"g"},{"name":"tare sauce","quantity":60,"unit":"ml"},{"name":"soy sauce","quantity":30,"unit":"ml"},{"name":"mirin","quantity":30,"unit":"ml"},{"name":"sake","quantity":20,"unit":"ml"},{"name":"shichimi togarashi","quantity":3,"unit":"g"}]',
  1,
  380,
  35,
  18,
  18,
  1,
  12,
  920,
  '["soy"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'teriyaki chicken',
  'Teriyaki Chicken',
  '[{"name":"chicken thigh","quantity":300,"unit":"g"},{"name":"soy sauce","quantity":60,"unit":"ml"},{"name":"mirin","quantity":40,"unit":"ml"},{"name":"sake","quantity":30,"unit":"ml"},{"name":"sugar","quantity":25,"unit":"g"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"garlic","quantity":2,"unit":"cloves"},{"name":"sesame seeds","quantity":5,"unit":"g"}]',
  1,
  420,
  35,
  28,
  18,
  0,
  22,
  1380,
  '["soy","sesame"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'gyudon',
  'Gyudon',
  '[{"name":"beef sirloin","quantity":200,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"rice","quantity":200,"unit":"g"},{"name":"dashi broth","quantity":100,"unit":"ml"},{"name":"soy sauce","quantity":40,"unit":"ml"},{"name":"mirin","quantity":30,"unit":"ml"},{"name":"sake","quantity":20,"unit":"ml"},{"name":"pickled ginger","quantity":15,"unit":"g"}]',
  1,
  580,
  32,
  65,
  20,
  2,
  10,
  980,
  '["soy","fish"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sukiyaki',
  'Sukiyaki',
  '[{"name":"beef ribeye","quantity":300,"unit":"g"},{"name":"tofu","quantity":150,"unit":"g"},{"name":"napa cabbage","quantity":150,"unit":"g"},{"name":"shiitake mushrooms","quantity":80,"unit":"g"},{"name":"shirataki noodles","quantity":100,"unit":"g"},{"name":"green onion","quantity":60,"unit":"g"},{"name":"soy sauce","quantity":80,"unit":"ml"},{"name":"mirin","quantity":60,"unit":"ml"},{"name":"sugar","quantity":40,"unit":"g"},{"name":"raw egg","quantity":1,"unit":"whole"}]',
  1,
  620,
  42,
  35,
  35,
  4,
  25,
  1250,
  '["soy","egg"]',
  '["high_fructan","high_mannitol"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'shabu shabu',
  'Shabu Shabu',
  '[{"name":"beef ribeye","quantity":250,"unit":"g"},{"name":"tofu","quantity":150,"unit":"g"},{"name":"napa cabbage","quantity":150,"unit":"g"},{"name":"enoki mushrooms","quantity":100,"unit":"g"},{"name":"shirataki noodles","quantity":100,"unit":"g"},{"name":"kombu dashi","quantity":600,"unit":"ml"},{"name":"ponzu sauce","quantity":60,"unit":"ml"},{"name":"sesame dipping sauce","quantity":60,"unit":"ml"}]',
  1,
  520,
  40,
  22,
  30,
  4,
  6,
  980,
  '["soy","sesame","fish"]',
  '["high_fructan","high_mannitol"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'okonomiyaki',
  'Okonomiyaki',
  '[{"name":"flour","quantity":100,"unit":"g"},{"name":"cabbage","quantity":200,"unit":"g"},{"name":"pork belly","quantity":100,"unit":"g"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"dashi broth","quantity":100,"unit":"ml"},{"name":"okonomiyaki sauce","quantity":50,"unit":"ml"},{"name":"mayonnaise","quantity":30,"unit":"g"},{"name":"bonito flakes","quantity":10,"unit":"g"},{"name":"aonori","quantity":5,"unit":"g"}]',
  1,
  520,
  22,
  45,
  28,
  4,
  12,
  920,
  '["gluten","egg","fish"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'takoyaki',
  'Takoyaki',
  '[{"name":"takoyaki batter","quantity":200,"unit":"g"},{"name":"octopus","quantity":100,"unit":"g"},{"name":"green onion","quantity":30,"unit":"g"},{"name":"pickled ginger","quantity":20,"unit":"g"},{"name":"tenkasu","quantity":20,"unit":"g"},{"name":"takoyaki sauce","quantity":40,"unit":"ml"},{"name":"mayonnaise","quantity":20,"unit":"g"},{"name":"bonito flakes","quantity":10,"unit":"g"},{"name":"aonori","quantity":5,"unit":"g"}]',
  1,
  380,
  18,
  42,
  16,
  2,
  8,
  780,
  '["gluten","egg","shellfish","fish"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'onigiri',
  'Onigiri',
  '[{"name":"sushi rice","quantity":200,"unit":"g"},{"name":"nori","quantity":2,"unit":"sheets"},{"name":"salmon flakes","quantity":50,"unit":"g"},{"name":"umeboshi","quantity":2,"unit":"pieces"},{"name":"salt","quantity":3,"unit":"g"},{"name":"sesame seeds","quantity":5,"unit":"g"}]',
  1,
  280,
  12,
  48,
  4,
  1,
  2,
  580,
  '["fish","sesame"]',
  '["low"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'gyoza',
  'Gyoza',
  '[{"name":"ground pork","quantity":250,"unit":"g"},{"name":"cabbage","quantity":150,"unit":"g"},{"name":"gyoza wrappers","quantity":200,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"green onion","quantity":30,"unit":"g"},{"name":"soy sauce","quantity":20,"unit":"ml"},{"name":"sesame oil","quantity":15,"unit":"ml"},{"name":"rice vinegar","quantity":20,"unit":"ml"}]',
  1,
  420,
  24,
  42,
  18,
  3,
  3,
  720,
  '["gluten","soy","sesame"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'miso soup',
  'Miso Soup',
  '[{"name":"dashi broth","quantity":400,"unit":"ml"},{"name":"miso paste","quantity":40,"unit":"g"},{"name":"silken tofu","quantity":100,"unit":"g"},{"name":"wakame seaweed","quantity":5,"unit":"g"},{"name":"green onion","quantity":15,"unit":"g"}]',
  1,
  80,
  6,
  8,
  3,
  2,
  3,
  820,
  '["soy","fish"]',
  '["high_gos","high_fructan"]',
  '["vegetarian","gluten-free","dairy-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'matcha dessert',
  'Matcha Dessert',
  '[{"name":"matcha powder","quantity":10,"unit":"g"},{"name":"heavy cream","quantity":200,"unit":"ml"},{"name":"sugar","quantity":60,"unit":"g"},{"name":"milk","quantity":150,"unit":"ml"},{"name":"gelatin","quantity":5,"unit":"g"},{"name":"red bean paste","quantity":50,"unit":"g"}]',
  1,
  320,
  6,
  38,
  18,
  2,
  32,
  60,
  '["milk"]',
  '["high_lactose","high_gos"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'spaghetti and meatballs',
  'Spaghetti and Meatballs',
  '[{"name":"spaghetti","quantity":200,"unit":"g"},{"name":"ground beef","quantity":300,"unit":"g"},{"name":"breadcrumbs","quantity":30,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"parmesan cheese","quantity":30,"unit":"g"},{"name":"marinara sauce","quantity":250,"unit":"ml"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"olive oil","quantity":15,"unit":"ml"},{"name":"basil","quantity":5,"unit":"g"}]',
  1,
  650,
  35,
  70,
  25,
  4,
  8,
  850,
  '["gluten","egg","milk"]',
  '["high_fructan","moderate_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'penne arrabbiata',
  'Penne Arrabbiata',
  '[{"name":"penne pasta","quantity":200,"unit":"g"},{"name":"crushed tomatoes","quantity":400,"unit":"g"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"red chili flakes","quantity":5,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"parsley","quantity":10,"unit":"g"}]',
  1,
  420,
  12,
  72,
  10,
  4,
  6,
  320,
  '["gluten"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'classic cheeseburger',
  'Classic Cheeseburger',
  '[{"name":"ground beef patty","quantity":150,"unit":"g"},{"name":"hamburger bun","quantity":1,"unit":"whole"},{"name":"cheddar cheese","quantity":30,"unit":"g"},{"name":"lettuce","quantity":20,"unit":"g"},{"name":"tomato","quantity":30,"unit":"g"},{"name":"onion","quantity":20,"unit":"g"},{"name":"pickles","quantity":15,"unit":"g"},{"name":"ketchup","quantity":15,"unit":"ml"},{"name":"mustard","quantity":10,"unit":"ml"}]',
  1,
  550,
  32,
  35,
  32,
  2,
  8,
  850,
  '["gluten","milk"]',
  '["high_fructan","moderate_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bacon cheeseburger',
  'Bacon Cheeseburger',
  '[{"name":"ground beef patty","quantity":150,"unit":"g"},{"name":"hamburger bun","quantity":1,"unit":"whole"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"cheddar cheese","quantity":30,"unit":"g"},{"name":"lettuce","quantity":20,"unit":"g"},{"name":"tomato","quantity":30,"unit":"g"},{"name":"onion","quantity":20,"unit":"g"}]',
  1,
  680,
  38,
  35,
  42,
  2,
  6,
  1150,
  '["gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pad thai',
  'Pad Thai',
  '[{"name":"rice noodles","quantity":200,"unit":"g"},{"name":"shrimp","quantity":150,"unit":"g"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"tofu","quantity":100,"unit":"g"},{"name":"bean sprouts","quantity":80,"unit":"g"},{"name":"peanuts","quantity":30,"unit":"g"},{"name":"green onion","quantity":20,"unit":"g"},{"name":"fish sauce","quantity":30,"unit":"ml"},{"name":"tamarind paste","quantity":20,"unit":"g"},{"name":"palm sugar","quantity":15,"unit":"g"},{"name":"lime","quantity":1,"unit":"wedge"}]',
  1,
  580,
  28,
  65,
  22,
  3,
  12,
  1200,
  '["shellfish","peanut","egg","soy","fish"]',
  '["high_fructan","high_gos"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken burrito',
  'Chicken Burrito',
  '[{"name":"flour tortilla","quantity":1,"unit":"large"},{"name":"grilled chicken","quantity":150,"unit":"g"},{"name":"rice","quantity":100,"unit":"g"},{"name":"black beans","quantity":80,"unit":"g"},{"name":"cheddar cheese","quantity":40,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"guacamole","quantity":50,"unit":"g"},{"name":"salsa","quantity":50,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"}]',
  1,
  720,
  42,
  68,
  28,
  8,
  4,
  1250,
  '["gluten","milk"]',
  '["high_gos","moderate_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'beef tacos',
  'Beef Tacos',
  '[{"name":"corn tortillas","quantity":3,"unit":"pieces"},{"name":"ground beef","quantity":150,"unit":"g"},{"name":"taco seasoning","quantity":15,"unit":"g"},{"name":"cheddar cheese","quantity":40,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"},{"name":"tomato","quantity":40,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"salsa","quantity":40,"unit":"g"}]',
  1,
  480,
  28,
  35,
  26,
  4,
  4,
  820,
  '["milk"]',
  '["moderate_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken quesadilla',
  'Chicken Quesadilla',
  '[{"name":"flour tortilla","quantity":2,"unit":"large"},{"name":"grilled chicken","quantity":120,"unit":"g"},{"name":"cheddar cheese","quantity":80,"unit":"g"},{"name":"peppers","quantity":40,"unit":"g"},{"name":"onion","quantity":30,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"salsa","quantity":40,"unit":"g"}]',
  1,
  580,
  35,
  42,
  30,
  3,
  4,
  980,
  '["gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'caesar salad',
  'Caesar Salad',
  '[{"name":"romaine lettuce","quantity":200,"unit":"g"},{"name":"parmesan cheese","quantity":40,"unit":"g"},{"name":"croutons","quantity":40,"unit":"g"},{"name":"caesar dressing","quantity":60,"unit":"ml"},{"name":"lemon juice","quantity":15,"unit":"ml"},{"name":"anchovy paste","quantity":5,"unit":"g"}]',
  1,
  380,
  12,
  18,
  30,
  4,
  3,
  780,
  '["gluten","milk","egg","fish"]',
  '["low"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken caesar salad',
  'Chicken Caesar Salad',
  '[{"name":"romaine lettuce","quantity":200,"unit":"g"},{"name":"grilled chicken breast","quantity":150,"unit":"g"},{"name":"parmesan cheese","quantity":40,"unit":"g"},{"name":"croutons","quantity":40,"unit":"g"},{"name":"caesar dressing","quantity":60,"unit":"ml"},{"name":"lemon juice","quantity":15,"unit":"ml"}]',
  1,
  520,
  42,
  18,
  32,
  4,
  3,
  920,
  '["gluten","milk","egg","fish"]',
  '["low"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'greek salad',
  'Greek Salad',
  '[{"name":"cucumber","quantity":100,"unit":"g"},{"name":"tomato","quantity":120,"unit":"g"},{"name":"red onion","quantity":40,"unit":"g"},{"name":"kalamata olives","quantity":40,"unit":"g"},{"name":"feta cheese","quantity":60,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"oregano","quantity":2,"unit":"g"},{"name":"red wine vinegar","quantity":15,"unit":"ml"}]',
  1,
  320,
  8,
  12,
  28,
  3,
  6,
  680,
  '["milk"]',
  '["high_fructan","moderate_polyol"]',
  '["vegetarian","gluten-free","keto"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'cobb salad',
  'Cobb Salad',
  '[{"name":"mixed greens","quantity":150,"unit":"g"},{"name":"grilled chicken","quantity":120,"unit":"g"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"hard-boiled egg","quantity":2,"unit":"whole"},{"name":"avocado","quantity":80,"unit":"g"},{"name":"tomato","quantity":60,"unit":"g"},{"name":"blue cheese","quantity":40,"unit":"g"},{"name":"red wine vinaigrette","quantity":45,"unit":"ml"}]',
  1,
  580,
  38,
  14,
  42,
  6,
  4,
  920,
  '["egg","milk"]',
  '["moderate_polyol"]',
  '["gluten-free","keto"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'club sandwich',
  'Club Sandwich',
  '[{"name":"white bread","quantity":3,"unit":"slices"},{"name":"turkey breast","quantity":80,"unit":"g"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"},{"name":"tomato","quantity":40,"unit":"g"},{"name":"mayonnaise","quantity":30,"unit":"g"}]',
  1,
  520,
  28,
  38,
  28,
  3,
  5,
  1150,
  '["gluten","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'blt sandwich',
  'BLT Sandwich',
  '[{"name":"white bread","quantity":2,"unit":"slices"},{"name":"bacon","quantity":60,"unit":"g"},{"name":"lettuce","quantity":40,"unit":"g"},{"name":"tomato","quantity":60,"unit":"g"},{"name":"mayonnaise","quantity":30,"unit":"g"}]',
  1,
  450,
  18,
  28,
  30,
  2,
  4,
  980,
  '["gluten","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'grilled cheese sandwich',
  'Grilled Cheese Sandwich',
  '[{"name":"white bread","quantity":2,"unit":"slices"},{"name":"cheddar cheese","quantity":60,"unit":"g"},{"name":"butter","quantity":20,"unit":"g"}]',
  1,
  420,
  15,
  28,
  28,
  1,
  3,
  680,
  '["gluten","milk"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'eggs benedict',
  'Eggs Benedict',
  '[{"name":"English muffin","quantity":1,"unit":"whole"},{"name":"Canadian bacon","quantity":60,"unit":"g"},{"name":"poached egg","quantity":2,"unit":"whole"},{"name":"hollandaise sauce","quantity":60,"unit":"ml"}]',
  1,
  580,
  25,
  28,
  42,
  2,
  2,
  1150,
  '["gluten","egg","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pancakes',
  'Pancakes',
  '[{"name":"all-purpose flour","quantity":150,"unit":"g"},{"name":"milk","quantity":240,"unit":"ml"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"butter","quantity":30,"unit":"g"},{"name":"maple syrup","quantity":60,"unit":"ml"},{"name":"baking powder","quantity":5,"unit":"g"}]',
  1,
  520,
  12,
  82,
  16,
  2,
  35,
  580,
  '["gluten","milk","egg"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'french toast',
  'French Toast',
  '[{"name":"brioche bread","quantity":3,"unit":"slices"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"milk","quantity":60,"unit":"ml"},{"name":"cinnamon","quantity":2,"unit":"g"},{"name":"vanilla extract","quantity":5,"unit":"ml"},{"name":"butter","quantity":20,"unit":"g"},{"name":"maple syrup","quantity":45,"unit":"ml"},{"name":"powdered sugar","quantity":15,"unit":"g"}]',
  1,
  580,
  15,
  72,
  25,
  2,
  42,
  420,
  '["gluten","milk","egg"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'avocado toast',
  'Avocado Toast',
  '[{"name":"sourdough bread","quantity":2,"unit":"slices"},{"name":"avocado","quantity":150,"unit":"g"},{"name":"lemon juice","quantity":10,"unit":"ml"},{"name":"red pepper flakes","quantity":1,"unit":"g"},{"name":"sea salt","quantity":2,"unit":"g"},{"name":"olive oil","quantity":10,"unit":"ml"}]',
  1,
  380,
  8,
  35,
  24,
  10,
  2,
  520,
  '["gluten"]',
  '["moderate_polyol","high_fructan"]',
  '["vegan","dairy-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');
