INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'gumbo',
  'Gumbo',
  '[{"name":"andouille sausage","quantity":200,"unit":"g"},{"name":"shrimp","quantity":200,"unit":"g"},{"name":"okra","quantity":150,"unit":"g"},{"name":"celery","quantity":80,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"bell pepper","quantity":80,"unit":"g"},{"name":"roux","quantity":60,"unit":"g"},{"name":"chicken stock","quantity":500,"unit":"ml"},{"name":"rice","quantity":150,"unit":"g"}]',
  1,
  520,
  32,
  48,
  22,
  4,
  6,
  1080,
  '["shellfish","wheat"]',
  '["high_fructan","high_polyol","high_gos"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'jambalaya',
  'Jambalaya',
  '[{"name":"andouille sausage","quantity":200,"unit":"g"},{"name":"chicken thigh","quantity":200,"unit":"g"},{"name":"shrimp","quantity":150,"unit":"g"},{"name":"rice","quantity":250,"unit":"g"},{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"celery","quantity":60,"unit":"g"},{"name":"bell pepper","quantity":80,"unit":"g"},{"name":"cajun seasoning","quantity":15,"unit":"g"}]',
  1,
  580,
  38,
  52,
  24,
  3,
  6,
  980,
  '["shellfish"]',
  '["high_fructan","high_polyol"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pancakes',
  'Pancakes',
  '[{"name":"flour","quantity":200,"unit":"g"},{"name":"buttermilk","quantity":300,"unit":"ml"},{"name":"eggs","quantity":2,"unit":"pieces"},{"name":"butter","quantity":40,"unit":"g"},{"name":"maple syrup","quantity":60,"unit":"ml"},{"name":"baking powder","quantity":10,"unit":"g"}]',
  1,
  480,
  12,
  68,
  18,
  2,
  28,
  520,
  '["wheat","egg","milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'apple pie',
  'Apple Pie',
  '[{"name":"apples","quantity":800,"unit":"g"},{"name":"pie crust","quantity":400,"unit":"g"},{"name":"sugar","quantity":150,"unit":"g"},{"name":"butter","quantity":60,"unit":"g"},{"name":"cinnamon","quantity":8,"unit":"g"},{"name":"nutmeg","quantity":2,"unit":"g"},{"name":"lemon juice","quantity":15,"unit":"ml"}]',
  1,
  380,
  4,
  58,
  16,
  3,
  32,
  280,
  '["wheat","milk"]',
  '["high_fructan","high_fructose","high_polyol"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chocolate chip cookies',
  'Chocolate Chip Cookies',
  '[{"name":"flour","quantity":280,"unit":"g"},{"name":"butter","quantity":230,"unit":"g"},{"name":"chocolate chips","quantity":200,"unit":"g"},{"name":"brown sugar","quantity":150,"unit":"g"},{"name":"white sugar","quantity":100,"unit":"g"},{"name":"eggs","quantity":2,"unit":"pieces"},{"name":"vanilla extract","quantity":10,"unit":"ml"}]',
  1,
  220,
  3,
  28,
  12,
  1,
  18,
  140,
  '["wheat","milk","egg","soy"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tacos americanized',
  'Tacos (Americanized)',
  '[{"name":"ground beef","quantity":200,"unit":"g"},{"name":"taco shells","quantity":3,"unit":"pieces"},{"name":"cheddar cheese","quantity":60,"unit":"g"},{"name":"lettuce","quantity":50,"unit":"g"},{"name":"tomato","quantity":60,"unit":"g"},{"name":"sour cream","quantity":40,"unit":"g"},{"name":"taco seasoning","quantity":15,"unit":"g"}]',
  1,
  520,
  28,
  32,
  32,
  3,
  4,
  780,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'jerk chicken',
  'Jerk Chicken',
  '[{"name":"chicken pieces","quantity":600,"unit":"g"},{"name":"scotch bonnet peppers","quantity":30,"unit":"g"},{"name":"allspice","quantity":10,"unit":"g"},{"name":"thyme","quantity":8,"unit":"g"},{"name":"scallions","quantity":50,"unit":"g"},{"name":"garlic","quantity":20,"unit":"g"},{"name":"ginger","quantity":15,"unit":"g"},{"name":"soy sauce","quantity":30,"unit":"ml"},{"name":"brown sugar","quantity":20,"unit":"g"}]',
  1,
  420,
  45,
  12,
  22,
  2,
  8,
  680,
  '["soy"]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'oxtail stew',
  'Oxtail Stew',
  '[{"name":"oxtail","quantity":800,"unit":"g"},{"name":"butter beans","quantity":200,"unit":"g"},{"name":"carrots","quantity":100,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"thyme","quantity":5,"unit":"g"},{"name":"scotch bonnet","quantity":10,"unit":"g"},{"name":"allspice","quantity":5,"unit":"g"}]',
  1,
  580,
  48,
  28,
  32,
  8,
  6,
  620,
  '[]',
  '["high_fructan","high_gos"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'curry goat',
  'Curry Goat',
  '[{"name":"goat meat","quantity":600,"unit":"g"},{"name":"curry powder","quantity":30,"unit":"g"},{"name":"potatoes","quantity":200,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"scotch bonnet","quantity":10,"unit":"g"},{"name":"thyme","quantity":5,"unit":"g"},{"name":"coconut milk","quantity":200,"unit":"ml"}]',
  1,
  520,
  42,
  24,
  30,
  4,
  4,
  580,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'rice and peas',
  'Rice and Peas',
  '[{"name":"rice","quantity":300,"unit":"g"},{"name":"kidney beans","quantity":200,"unit":"g"},{"name":"coconut milk","quantity":400,"unit":"ml"},{"name":"thyme","quantity":5,"unit":"g"},{"name":"scotch bonnet","quantity":10,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"scallions","quantity":30,"unit":"g"}]',
  1,
  420,
  12,
  62,
  16,
  8,
  2,
  320,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'jamaican beef patty',
  'Jamaican Beef Patty',
  '[{"name":"ground beef","quantity":300,"unit":"g"},{"name":"pastry dough","quantity":400,"unit":"g"},{"name":"curry powder","quantity":15,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"scotch bonnet","quantity":10,"unit":"g"},{"name":"thyme","quantity":3,"unit":"g"},{"name":"turmeric","quantity":5,"unit":"g"}]',
  1,
  380,
  18,
  32,
  22,
  2,
  2,
  520,
  '["wheat"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'saltfish and ackee',
  'Saltfish and Ackee',
  '[{"name":"salt cod","quantity":300,"unit":"g"},{"name":"ackee","quantity":400,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"tomatoes","quantity":100,"unit":"g"},{"name":"scotch bonnet","quantity":10,"unit":"g"},{"name":"scallions","quantity":30,"unit":"g"},{"name":"black pepper","quantity":3,"unit":"g"},{"name":"vegetable oil","quantity":30,"unit":"ml"}]',
  1,
  380,
  32,
  12,
  24,
  4,
  4,
  920,
  '["fish"]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'callaloo',
  'Callaloo',
  '[{"name":"callaloo leaves","quantity":400,"unit":"g"},{"name":"okra","quantity":100,"unit":"g"},{"name":"coconut milk","quantity":200,"unit":"ml"},{"name":"onion","quantity":60,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"scotch bonnet","quantity":8,"unit":"g"},{"name":"thyme","quantity":3,"unit":"g"}]',
  1,
  180,
  6,
  14,
  12,
  6,
  4,
  280,
  '[]',
  '["high_fructan","high_gos"]',
  '["vegan","gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'mofongo',
  'Mofongo',
  '[{"name":"green plantains","quantity":400,"unit":"g"},{"name":"pork cracklings","quantity":80,"unit":"g"},{"name":"garlic","quantity":20,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"},{"name":"chicken broth","quantity":100,"unit":"ml"}]',
  1,
  480,
  12,
  58,
  24,
  4,
  8,
  520,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pernil',
  'Pernil',
  '[{"name":"pork shoulder","quantity":2000,"unit":"g"},{"name":"garlic","quantity":40,"unit":"g"},{"name":"oregano","quantity":10,"unit":"g"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"},{"name":"achiote","quantity":15,"unit":"g"},{"name":"lime juice","quantity":60,"unit":"ml"}]',
  1,
  420,
  38,
  4,
  28,
  1,
  1,
  580,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free","keto","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'arroz con gandules',
  'Arroz con Gandules',
  '[{"name":"rice","quantity":400,"unit":"g"},{"name":"pigeon peas","quantity":300,"unit":"g"},{"name":"sofrito","quantity":100,"unit":"g"},{"name":"pork","quantity":150,"unit":"g"},{"name":"olives","quantity":40,"unit":"g"},{"name":"capers","quantity":15,"unit":"g"},{"name":"achiote oil","quantity":30,"unit":"ml"}]',
  1,
  480,
  18,
  68,
  16,
  8,
  3,
  620,
  '[]',
  '["high_gos","high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pasteles',
  'Pasteles',
  '[{"name":"green bananas","quantity":500,"unit":"g"},{"name":"yautia","quantity":300,"unit":"g"},{"name":"pork","quantity":400,"unit":"g"},{"name":"sofrito","quantity":80,"unit":"g"},{"name":"olives","quantity":40,"unit":"g"},{"name":"achiote oil","quantity":60,"unit":"ml"},{"name":"banana leaves","quantity":8,"unit":"pieces"}]',
  1,
  380,
  22,
  42,
  14,
  4,
  4,
  480,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'ropa vieja',
  'Ropa Vieja',
  '[{"name":"flank steak","quantity":600,"unit":"g"},{"name":"tomato sauce","quantity":200,"unit":"ml"},{"name":"bell peppers","quantity":150,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"bay leaves","quantity":2,"unit":"pieces"},{"name":"white wine","quantity":60,"unit":"ml"}]',
  1,
  380,
  42,
  12,
  18,
  3,
  6,
  520,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'lechon',
  'Lechón',
  '[{"name":"whole pig","quantity":5000,"unit":"g"},{"name":"mojo criollo","quantity":500,"unit":"ml"},{"name":"garlic","quantity":60,"unit":"g"},{"name":"oregano","quantity":15,"unit":"g"},{"name":"cumin","quantity":10,"unit":"g"},{"name":"sour orange juice","quantity":200,"unit":"ml"}]',
  1,
  480,
  42,
  4,
  32,
  0,
  2,
  680,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free","keto"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'picadillo',
  'Picadillo',
  '[{"name":"ground beef","quantity":500,"unit":"g"},{"name":"tomato sauce","quantity":150,"unit":"ml"},{"name":"olives","quantity":60,"unit":"g"},{"name":"raisins","quantity":40,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"bell pepper","quantity":60,"unit":"g"}]',
  1,
  380,
  32,
  18,
  22,
  3,
  12,
  580,
  '[]',
  '["high_fructan","high_fructose"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sancocho',
  'Sancocho',
  '[{"name":"chicken","quantity":400,"unit":"g"},{"name":"pork","quantity":300,"unit":"g"},{"name":"yuca","quantity":200,"unit":"g"},{"name":"plantains","quantity":200,"unit":"g"},{"name":"corn","quantity":150,"unit":"g"},{"name":"potatoes","quantity":150,"unit":"g"},{"name":"cilantro","quantity":20,"unit":"g"},{"name":"lime","quantity":1,"unit":"piece"}]',
  1,
  480,
  38,
  42,
  18,
  5,
  6,
  520,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'caribbean roti',
  'Caribbean Roti',
  '[{"name":"roti skin","quantity":2,"unit":"pieces"},{"name":"curried chickpeas","quantity":300,"unit":"g"},{"name":"potato","quantity":150,"unit":"g"},{"name":"curry powder","quantity":15,"unit":"g"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"}]',
  1,
  420,
  14,
  62,
  14,
  10,
  4,
  480,
  '["wheat"]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tostones',
  'Tostones',
  '[{"name":"green plantains","quantity":400,"unit":"g"},{"name":"vegetable oil","quantity":200,"unit":"ml"},{"name":"salt","quantity":5,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"}]',
  1,
  320,
  2,
  48,
  14,
  3,
  4,
  380,
  '[]',
  '["high_fructan"]',
  '["vegan","gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'conch fritters',
  'Conch Fritters',
  '[{"name":"conch meat","quantity":300,"unit":"g"},{"name":"flour","quantity":150,"unit":"g"},{"name":"egg","quantity":2,"unit":"pieces"},{"name":"bell pepper","quantity":60,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"scotch bonnet","quantity":10,"unit":"g"},{"name":"baking powder","quantity":8,"unit":"g"}]',
  1,
  280,
  22,
  28,
  10,
  2,
  2,
  520,
  '["shellfish","wheat","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tres leches cake',
  'Tres Leches Cake',
  '[{"name":"sponge cake","quantity":300,"unit":"g"},{"name":"evaporated milk","quantity":350,"unit":"ml"},{"name":"condensed milk","quantity":400,"unit":"ml"},{"name":"heavy cream","quantity":250,"unit":"ml"},{"name":"eggs","quantity":5,"unit":"pieces"},{"name":"vanilla","quantity":10,"unit":"ml"},{"name":"whipped cream","quantity":200,"unit":"g"}]',
  1,
  420,
  10,
  52,
  20,
  0,
  42,
  180,
  '["milk","egg","wheat"]',
  '["high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'feijoada',
  'Feijoada',
  '[{"name":"black beans","quantity":500,"unit":"g"},{"name":"pork ribs","quantity":300,"unit":"g"},{"name":"bacon","quantity":150,"unit":"g"},{"name":"linguiça sausage","quantity":200,"unit":"g"},{"name":"pork shoulder","quantity":200,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"garlic","quantity":20,"unit":"g"},{"name":"bay leaves","quantity":3,"unit":"pieces"},{"name":"orange","quantity":1,"unit":"piece"}]',
  1,
  580,
  42,
  38,
  32,
  12,
  4,
  980,
  '[]',
  '["high_gos","high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'picanha',
  'Picanha',
  '[{"name":"picanha beef","quantity":500,"unit":"g"},{"name":"coarse salt","quantity":20,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"}]',
  1,
  480,
  52,
  1,
  30,
  0,
  0,
  680,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free","keto","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'churrasco mixed grill',
  'Churrasco Mixed Grill',
  '[{"name":"picanha","quantity":200,"unit":"g"},{"name":"fraldinha","quantity":150,"unit":"g"},{"name":"linguiça","quantity":100,"unit":"g"},{"name":"chicken hearts","quantity":100,"unit":"g"},{"name":"coarse salt","quantity":15,"unit":"g"},{"name":"farofa","quantity":80,"unit":"g"}]',
  1,
  680,
  58,
  18,
  42,
  2,
  1,
  920,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'carne de sol',
  'Carne de Sol',
  '[{"name":"sun-dried beef","quantity":400,"unit":"g"},{"name":"butter","quantity":40,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"cassava","quantity":200,"unit":"g"},{"name":"cream cheese","quantity":60,"unit":"g"}]',
  1,
  520,
  42,
  28,
  28,
  3,
  4,
  1100,
  '["milk"]',
  '["high_fructan","high_lactose"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'coxinha',
  'Coxinha',
  '[{"name":"shredded chicken","quantity":300,"unit":"g"},{"name":"wheat flour","quantity":250,"unit":"g"},{"name":"chicken broth","quantity":400,"unit":"ml"},{"name":"cream cheese","quantity":100,"unit":"g"},{"name":"eggs","quantity":2,"unit":"pieces"},{"name":"breadcrumbs","quantity":150,"unit":"g"}]',
  1,
  280,
  18,
  24,
  14,
  1,
  1,
  420,
  '["wheat","egg","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pao de queijo',
  'Pão de Queijo',
  '[{"name":"tapioca starch","quantity":400,"unit":"g"},{"name":"queijo minas","quantity":200,"unit":"g"},{"name":"parmesan","quantity":100,"unit":"g"},{"name":"eggs","quantity":2,"unit":"pieces"},{"name":"milk","quantity":200,"unit":"ml"},{"name":"vegetable oil","quantity":80,"unit":"ml"}]',
  1,
  180,
  6,
  22,
  8,
  0,
  1,
  280,
  '["milk","egg"]',
  '["high_lactose"]',
  '["gluten-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pastel',
  'Pastel',
  '[{"name":"pastry dough","quantity":300,"unit":"g"},{"name":"ground beef","quantity":200,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"olives","quantity":30,"unit":"g"},{"name":"egg","quantity":1,"unit":"piece"},{"name":"vegetable oil","quantity":500,"unit":"ml"}]',
  1,
  320,
  14,
  28,
  18,
  1,
  2,
  380,
  '["wheat","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'acaraje',
  'Acarajé',
  '[{"name":"black-eyed peas","quantity":400,"unit":"g"},{"name":"dried shrimp","quantity":100,"unit":"g"},{"name":"palm oil","quantity":200,"unit":"ml"},{"name":"onion","quantity":80,"unit":"g"},{"name":"vatapá filling","quantity":150,"unit":"g"},{"name":"caruru","quantity":100,"unit":"g"}]',
  1,
  380,
  18,
  32,
  22,
  8,
  3,
  620,
  '["shellfish"]',
  '["high_gos","high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tapioca crepes',
  'Tapioca Crepes',
  '[{"name":"tapioca starch","quantity":150,"unit":"g"},{"name":"coconut flakes","quantity":40,"unit":"g"},{"name":"condensed milk","quantity":60,"unit":"ml"},{"name":"butter","quantity":20,"unit":"g"}]',
  1,
  320,
  2,
  52,
  12,
  2,
  18,
  80,
  '["milk"]',
  '["high_lactose"]',
  '["gluten-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'moqueca',
  'Moqueca',
  '[{"name":"fish fillets","quantity":600,"unit":"g"},{"name":"coconut milk","quantity":400,"unit":"ml"},{"name":"palm oil","quantity":60,"unit":"ml"},{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"bell peppers","quantity":100,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"cilantro","quantity":20,"unit":"g"},{"name":"lime","quantity":1,"unit":"piece"}]',
  1,
  420,
  38,
  12,
  26,
  3,
  6,
  480,
  '["fish"]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'vatapa',
  'Vatapá',
  '[{"name":"dried shrimp","quantity":200,"unit":"g"},{"name":"bread","quantity":150,"unit":"g"},{"name":"coconut milk","quantity":400,"unit":"ml"},{"name":"palm oil","quantity":60,"unit":"ml"},{"name":"peanuts","quantity":100,"unit":"g"},{"name":"cashews","quantity":80,"unit":"g"},{"name":"ginger","quantity":15,"unit":"g"}]',
  1,
  480,
  22,
  28,
  34,
  4,
  6,
  680,
  '["shellfish","wheat","peanut","tree_nut"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bobo de camarao',
  'Bobó de Camarão',
  '[{"name":"shrimp","quantity":500,"unit":"g"},{"name":"cassava","quantity":400,"unit":"g"},{"name":"coconut milk","quantity":400,"unit":"ml"},{"name":"palm oil","quantity":60,"unit":"ml"},{"name":"onion","quantity":80,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"tomatoes","quantity":100,"unit":"g"}]',
  1,
  480,
  32,
  36,
  26,
  4,
  5,
  580,
  '["shellfish"]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'farofa',
  'Farofa',
  '[{"name":"cassava flour","quantity":200,"unit":"g"},{"name":"bacon","quantity":100,"unit":"g"},{"name":"butter","quantity":40,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"egg","quantity":2,"unit":"pieces"},{"name":"parsley","quantity":15,"unit":"g"}]',
  1,
  320,
  10,
  38,
  16,
  3,
  2,
  480,
  '["milk","egg"]',
  '["high_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'baiao de dois',
  'Baião de Dois',
  '[{"name":"rice","quantity":250,"unit":"g"},{"name":"black-eyed peas","quantity":200,"unit":"g"},{"name":"bacon","quantity":100,"unit":"g"},{"name":"queijo coalho","quantity":100,"unit":"g"},{"name":"butter","quantity":30,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"}]',
  1,
  520,
  22,
  58,
  24,
  8,
  3,
  720,
  '["milk"]',
  '["high_gos","high_fructan","high_lactose"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'caldo verde',
  'Caldo Verde',
  '[{"name":"collard greens","quantity":300,"unit":"g"},{"name":"potatoes","quantity":400,"unit":"g"},{"name":"linguiça","quantity":150,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"}]',
  1,
  380,
  16,
  38,
  20,
  6,
  4,
  680,
  '[]',
  '["high_fructan"]',
  '["gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'escondidinho',
  'Escondidinho',
  '[{"name":"cassava","quantity":600,"unit":"g"},{"name":"shredded beef","quantity":400,"unit":"g"},{"name":"cream cheese","quantity":150,"unit":"g"},{"name":"butter","quantity":60,"unit":"g"},{"name":"mozzarella","quantity":150,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"}]',
  1,
  520,
  32,
  42,
  28,
  4,
  4,
  680,
  '["milk"]',
  '["high_fructan","high_lactose"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'brazilian stroganoff',
  'Brazilian Stroganoff',
  '[{"name":"chicken breast","quantity":500,"unit":"g"},{"name":"heavy cream","quantity":300,"unit":"ml"},{"name":"tomato paste","quantity":60,"unit":"g"},{"name":"ketchup","quantity":40,"unit":"ml"},{"name":"mushrooms","quantity":150,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"potato sticks","quantity":100,"unit":"g"}]',
  1,
  580,
  42,
  28,
  36,
  2,
  10,
  720,
  '["milk"]',
  '["high_fructan","high_lactose","high_polyol"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'brigadeiro',
  'Brigadeiro',
  '[{"name":"condensed milk","quantity":400,"unit":"ml"},{"name":"cocoa powder","quantity":40,"unit":"g"},{"name":"butter","quantity":30,"unit":"g"},{"name":"chocolate sprinkles","quantity":60,"unit":"g"}]',
  1,
  120,
  2,
  18,
  5,
  1,
  16,
  40,
  '["milk"]',
  '["high_lactose"]',
  '["gluten-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'quindim',
  'Quindim',
  '[{"name":"egg yolks","quantity":12,"unit":"pieces"},{"name":"sugar","quantity":300,"unit":"g"},{"name":"shredded coconut","quantity":150,"unit":"g"},{"name":"butter","quantity":30,"unit":"g"}]',
  1,
  180,
  4,
  24,
  8,
  1,
  22,
  30,
  '["egg","milk"]',
  '[]',
  '["gluten-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'caipirinha',
  'Caipirinha',
  '[{"name":"cachaça","quantity":60,"unit":"ml"},{"name":"lime","quantity":1,"unit":"piece"},{"name":"sugar","quantity":20,"unit":"g"},{"name":"ice","quantity":150,"unit":"g"}]',
  1,
  180,
  0,
  22,
  0,
  0,
  20,
  2,
  '[]',
  '[]',
  '["vegan","gluten-free","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');
