INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kimchi',
  'Kimchi',
  '[{"name":"napa cabbage","quantity":500,"unit":"g"},{"name":"gochugaru","quantity":60,"unit":"g"},{"name":"fish sauce","quantity":40,"unit":"ml"},{"name":"garlic","quantity":8,"unit":"cloves"},{"name":"ginger","quantity":20,"unit":"g"},{"name":"green onion","quantity":50,"unit":"g"},{"name":"salted shrimp","quantity":30,"unit":"g"},{"name":"sugar","quantity":15,"unit":"g"}]',
  1,
  40,
  2,
  8,
  0,
  2,
  4,
  680,
  '["fish","shellfish"]',
  '["high_fructan"]',
  '["vegan","gluten-free","dairy-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pho bo',
  'Phở Bò',
  '[{"name":"rice noodles","quantity":200,"unit":"g"},{"name":"beef brisket","quantity":150,"unit":"g"},{"name":"beef bone broth","quantity":500,"unit":"ml"},{"name":"star anise","quantity":2,"unit":"whole"},{"name":"cinnamon stick","quantity":1,"unit":"piece"},{"name":"ginger","quantity":30,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"bean sprouts","quantity":50,"unit":"g"},{"name":"thai basil","quantity":10,"unit":"g"},{"name":"lime","quantity":1,"unit":"wedge"},{"name":"hoisin sauce","quantity":15,"unit":"ml"},{"name":"sriracha","quantity":10,"unit":"ml"}]',
  1,
  450,
  32,
  55,
  12,
  3,
  6,
  1200,
  '["soy"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pho ga',
  'Phở Gà',
  '[{"name":"rice noodles","quantity":200,"unit":"g"},{"name":"chicken breast","quantity":150,"unit":"g"},{"name":"chicken broth","quantity":500,"unit":"ml"},{"name":"star anise","quantity":2,"unit":"whole"},{"name":"cinnamon stick","quantity":1,"unit":"piece"},{"name":"ginger","quantity":30,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"bean sprouts","quantity":50,"unit":"g"},{"name":"cilantro","quantity":10,"unit":"g"},{"name":"green onion","quantity":20,"unit":"g"},{"name":"lime","quantity":1,"unit":"wedge"}]',
  1,
  380,
  35,
  48,
  6,
  2,
  4,
  980,
  '[]',
  '["high_fructan"]',
  '["dairy-free","gluten-free","low-fat"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bun rieu',
  'Bún Riêu',
  '[{"name":"rice vermicelli","quantity":200,"unit":"g"},{"name":"crab paste","quantity":60,"unit":"g"},{"name":"tomatoes","quantity":150,"unit":"g"},{"name":"tofu puffs","quantity":80,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"shrimp paste","quantity":15,"unit":"g"},{"name":"pork broth","quantity":500,"unit":"ml"},{"name":"water spinach","quantity":50,"unit":"g"},{"name":"bean sprouts","quantity":30,"unit":"g"},{"name":"shallots","quantity":30,"unit":"g"}]',
  1,
  420,
  24,
  52,
  14,
  3,
  6,
  1100,
  '["shellfish","egg","soy"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bun bo hue',
  'Bún Bò Huế',
  '[{"name":"rice vermicelli","quantity":200,"unit":"g"},{"name":"beef shank","quantity":150,"unit":"g"},{"name":"pork knuckle","quantity":80,"unit":"g"},{"name":"lemongrass","quantity":30,"unit":"g"},{"name":"shrimp paste","quantity":20,"unit":"g"},{"name":"chili oil","quantity":15,"unit":"ml"},{"name":"banana blossom","quantity":50,"unit":"g"},{"name":"water spinach","quantity":50,"unit":"g"},{"name":"bean sprouts","quantity":30,"unit":"g"},{"name":"pork blood cake","quantity":40,"unit":"g"},{"name":"lime","quantity":1,"unit":"wedge"}]',
  1,
  520,
  38,
  48,
  20,
  3,
  4,
  1350,
  '["shellfish"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'hu tieu',
  'Hủ Tiếu',
  '[{"name":"rice noodles","quantity":200,"unit":"g"},{"name":"pork","quantity":100,"unit":"g"},{"name":"shrimp","quantity":80,"unit":"g"},{"name":"pork liver","quantity":50,"unit":"g"},{"name":"pork broth","quantity":450,"unit":"ml"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"bean sprouts","quantity":50,"unit":"g"},{"name":"chinese celery","quantity":20,"unit":"g"},{"name":"fried shallots","quantity":15,"unit":"g"},{"name":"green onion","quantity":20,"unit":"g"}]',
  1,
  480,
  36,
  50,
  15,
  2,
  3,
  1050,
  '["shellfish"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'banh mi',
  'Bánh Mì',
  '[{"name":"baguette","quantity":150,"unit":"g"},{"name":"pork belly","quantity":80,"unit":"g"},{"name":"vietnamese ham","quantity":50,"unit":"g"},{"name":"pate","quantity":30,"unit":"g"},{"name":"pickled carrots","quantity":40,"unit":"g"},{"name":"pickled daikon","quantity":40,"unit":"g"},{"name":"cucumber","quantity":30,"unit":"g"},{"name":"cilantro","quantity":10,"unit":"g"},{"name":"jalapeño","quantity":10,"unit":"g"},{"name":"mayonnaise","quantity":20,"unit":"g"},{"name":"maggi sauce","quantity":5,"unit":"ml"}]',
  1,
  580,
  26,
  52,
  30,
  3,
  8,
  1400,
  '["wheat","egg","soy"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'goi cuon',
  'Gỏi Cuốn',
  '[{"name":"rice paper","quantity":4,"unit":"sheets"},{"name":"shrimp","quantity":80,"unit":"g"},{"name":"pork belly","quantity":60,"unit":"g"},{"name":"rice vermicelli","quantity":60,"unit":"g"},{"name":"lettuce","quantity":40,"unit":"g"},{"name":"mint","quantity":10,"unit":"g"},{"name":"thai basil","quantity":10,"unit":"g"},{"name":"chives","quantity":15,"unit":"g"},{"name":"peanut sauce","quantity":40,"unit":"ml"},{"name":"hoisin sauce","quantity":20,"unit":"ml"}]',
  1,
  320,
  22,
  35,
  10,
  2,
  6,
  680,
  '["shellfish","peanut","soy"]',
  '["high_fructan","high_gos"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'cha gio',
  'Chả Giò',
  '[{"name":"rice paper","quantity":8,"unit":"sheets"},{"name":"ground pork","quantity":200,"unit":"g"},{"name":"crab meat","quantity":50,"unit":"g"},{"name":"wood ear mushrooms","quantity":30,"unit":"g"},{"name":"glass noodles","quantity":40,"unit":"g"},{"name":"carrots","quantity":50,"unit":"g"},{"name":"taro","quantity":50,"unit":"g"},{"name":"shallots","quantity":20,"unit":"g"},{"name":"fish sauce","quantity":15,"unit":"ml"},{"name":"vegetable oil","quantity":100,"unit":"ml"}]',
  1,
  450,
  18,
  32,
  28,
  2,
  3,
  720,
  '["shellfish","fish"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bun cha',
  'Bún Chả',
  '[{"name":"rice vermicelli","quantity":200,"unit":"g"},{"name":"pork patties","quantity":150,"unit":"g"},{"name":"pork belly","quantity":100,"unit":"g"},{"name":"fish sauce","quantity":30,"unit":"ml"},{"name":"sugar","quantity":20,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"lettuce","quantity":40,"unit":"g"},{"name":"herbs","quantity":30,"unit":"g"},{"name":"pickled papaya","quantity":40,"unit":"g"},{"name":"lime","quantity":1,"unit":"wedge"}]',
  1,
  580,
  32,
  55,
  26,
  2,
  12,
  1100,
  '["fish"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bun thit nuong',
  'Bún Thịt Nướng',
  '[{"name":"rice vermicelli","quantity":200,"unit":"g"},{"name":"grilled pork","quantity":150,"unit":"g"},{"name":"lettuce","quantity":50,"unit":"g"},{"name":"cucumber","quantity":40,"unit":"g"},{"name":"pickled carrots","quantity":40,"unit":"g"},{"name":"bean sprouts","quantity":40,"unit":"g"},{"name":"peanuts","quantity":20,"unit":"g"},{"name":"fried shallots","quantity":15,"unit":"g"},{"name":"nuoc cham","quantity":60,"unit":"ml"},{"name":"mint","quantity":10,"unit":"g"}]',
  1,
  520,
  30,
  55,
  20,
  3,
  10,
  950,
  '["fish","peanut"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'com tam',
  'Cơm Tấm',
  '[{"name":"broken rice","quantity":200,"unit":"g"},{"name":"grilled pork chop","quantity":150,"unit":"g"},{"name":"pork skin","quantity":50,"unit":"g"},{"name":"steamed egg meatloaf","quantity":80,"unit":"g"},{"name":"pickled vegetables","quantity":40,"unit":"g"},{"name":"cucumber","quantity":30,"unit":"g"},{"name":"tomato","quantity":40,"unit":"g"},{"name":"fried shallots","quantity":10,"unit":"g"},{"name":"nuoc cham","quantity":50,"unit":"ml"},{"name":"scallion oil","quantity":15,"unit":"ml"}]',
  1,
  650,
  38,
  60,
  28,
  2,
  8,
  1050,
  '["fish","egg"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'xoi',
  'Xôi',
  '[{"name":"sticky rice","quantity":200,"unit":"g"},{"name":"mung beans","quantity":80,"unit":"g"},{"name":"coconut milk","quantity":60,"unit":"ml"},{"name":"shallots","quantity":30,"unit":"g"},{"name":"vegetable oil","quantity":15,"unit":"ml"},{"name":"salt","quantity":2,"unit":"g"},{"name":"sugar","quantity":10,"unit":"g"}]',
  1,
  380,
  10,
  68,
  8,
  4,
  6,
  320,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'banh xeo',
  'Bánh Xèo',
  '[{"name":"rice flour","quantity":100,"unit":"g"},{"name":"coconut milk","quantity":100,"unit":"ml"},{"name":"turmeric","quantity":5,"unit":"g"},{"name":"shrimp","quantity":80,"unit":"g"},{"name":"pork belly","quantity":80,"unit":"g"},{"name":"bean sprouts","quantity":60,"unit":"g"},{"name":"mung beans","quantity":40,"unit":"g"},{"name":"green onion","quantity":20,"unit":"g"},{"name":"lettuce","quantity":40,"unit":"g"},{"name":"nuoc cham","quantity":50,"unit":"ml"}]',
  1,
  480,
  24,
  42,
  24,
  3,
  5,
  850,
  '["shellfish","fish"]',
  '["high_fructan","high_gos"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'ca kho to',
  'Cá Kho Tộ',
  '[{"name":"catfish","quantity":300,"unit":"g"},{"name":"fish sauce","quantity":45,"unit":"ml"},{"name":"coconut water","quantity":100,"unit":"ml"},{"name":"caramel sauce","quantity":30,"unit":"ml"},{"name":"sugar","quantity":20,"unit":"g"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"shallots","quantity":30,"unit":"g"},{"name":"black pepper","quantity":3,"unit":"g"},{"name":"chili","quantity":10,"unit":"g"},{"name":"green onion","quantity":15,"unit":"g"}]',
  1,
  380,
  32,
  22,
  18,
  1,
  18,
  1400,
  '["fish"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'thit kho trung',
  'Thịt Kho Trứng',
  '[{"name":"pork belly","quantity":300,"unit":"g"},{"name":"eggs","quantity":4,"unit":"whole"},{"name":"coconut water","quantity":200,"unit":"ml"},{"name":"fish sauce","quantity":40,"unit":"ml"},{"name":"caramel sauce","quantity":30,"unit":"ml"},{"name":"sugar","quantity":25,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"shallots","quantity":20,"unit":"g"},{"name":"black pepper","quantity":2,"unit":"g"}]',
  1,
  520,
  28,
  18,
  38,
  0,
  16,
  1250,
  '["fish","egg"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free","keto-friendly"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'lemongrass chicken',
  'Lemongrass Chicken',
  '[{"name":"chicken thighs","quantity":400,"unit":"g"},{"name":"lemongrass","quantity":40,"unit":"g"},{"name":"fish sauce","quantity":30,"unit":"ml"},{"name":"sugar","quantity":20,"unit":"g"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"shallots","quantity":30,"unit":"g"},{"name":"chili","quantity":15,"unit":"g"},{"name":"vegetable oil","quantity":30,"unit":"ml"},{"name":"black pepper","quantity":2,"unit":"g"}]',
  1,
  420,
  36,
  12,
  26,
  1,
  10,
  980,
  '["fish"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'goi u u',
  'Gỏi Đu Đủ',
  '[{"name":"green papaya","quantity":200,"unit":"g"},{"name":"shrimp","quantity":60,"unit":"g"},{"name":"pork","quantity":50,"unit":"g"},{"name":"carrots","quantity":40,"unit":"g"},{"name":"vietnamese coriander","quantity":15,"unit":"g"},{"name":"thai basil","quantity":10,"unit":"g"},{"name":"peanuts","quantity":25,"unit":"g"},{"name":"fried shallots","quantity":15,"unit":"g"},{"name":"nuoc cham","quantity":50,"unit":"ml"},{"name":"chili","quantity":5,"unit":"g"}]',
  1,
  280,
  18,
  22,
  14,
  4,
  12,
  720,
  '["shellfish","fish","peanut"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'vietnamese iced coffee',
  'Vietnamese Iced Coffee',
  '[{"name":"vietnamese coffee","quantity":25,"unit":"g"},{"name":"condensed milk","quantity":40,"unit":"ml"},{"name":"hot water","quantity":100,"unit":"ml"},{"name":"ice","quantity":150,"unit":"g"}]',
  1,
  180,
  3,
  28,
  6,
  0,
  26,
  45,
  '["milk"]',
  '["high_lactose"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'che',
  'Chè',
  '[{"name":"mung beans","quantity":80,"unit":"g"},{"name":"tapioca pearls","quantity":40,"unit":"g"},{"name":"coconut milk","quantity":150,"unit":"ml"},{"name":"sugar","quantity":50,"unit":"g"},{"name":"pandan leaves","quantity":5,"unit":"g"},{"name":"red beans","quantity":40,"unit":"g"},{"name":"palm sugar","quantity":20,"unit":"g"},{"name":"ice","quantity":100,"unit":"g"}]',
  1,
  320,
  8,
  58,
  8,
  4,
  38,
  25,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'fish sauce wings',
  'Fish Sauce Wings',
  '[{"name":"chicken wings","quantity":500,"unit":"g"},{"name":"fish sauce","quantity":45,"unit":"ml"},{"name":"sugar","quantity":40,"unit":"g"},{"name":"garlic","quantity":6,"unit":"cloves"},{"name":"butter","quantity":30,"unit":"g"},{"name":"black pepper","quantity":3,"unit":"g"},{"name":"vegetable oil","quantity":50,"unit":"ml"}]',
  1,
  580,
  38,
  18,
  40,
  0,
  16,
  1350,
  '["fish","milk"]',
  '["high_fructan"]',
  '["gluten-free","keto-friendly"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pad thai',
  'Pad Thai',
  '[{"name":"rice noodles","quantity":200,"unit":"g"},{"name":"shrimp","quantity":100,"unit":"g"},{"name":"tofu","quantity":80,"unit":"g"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"bean sprouts","quantity":80,"unit":"g"},{"name":"garlic chives","quantity":30,"unit":"g"},{"name":"peanuts","quantity":30,"unit":"g"},{"name":"tamarind paste","quantity":30,"unit":"g"},{"name":"fish sauce","quantity":30,"unit":"ml"},{"name":"palm sugar","quantity":25,"unit":"g"},{"name":"dried shrimp","quantity":15,"unit":"g"},{"name":"lime","quantity":1,"unit":"wedge"}]',
  1,
  520,
  28,
  62,
  18,
  3,
  14,
  1150,
  '["shellfish","egg","peanut","fish","soy"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pad see ew',
  'Pad See Ew',
  '[{"name":"wide rice noodles","quantity":250,"unit":"g"},{"name":"chicken breast","quantity":150,"unit":"g"},{"name":"chinese broccoli","quantity":150,"unit":"g"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"soy sauce","quantity":30,"unit":"ml"},{"name":"dark soy sauce","quantity":20,"unit":"ml"},{"name":"oyster sauce","quantity":20,"unit":"ml"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"vegetable oil","quantity":30,"unit":"ml"},{"name":"white pepper","quantity":2,"unit":"g"}]',
  1,
  580,
  32,
  68,
  20,
  3,
  6,
  1400,
  '["egg","soy","shellfish"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pad kee mao',
  'Pad Kee Mao',
  '[{"name":"wide rice noodles","quantity":250,"unit":"g"},{"name":"beef sirloin","quantity":150,"unit":"g"},{"name":"thai basil","quantity":30,"unit":"g"},{"name":"thai chilies","quantity":20,"unit":"g"},{"name":"garlic","quantity":5,"unit":"cloves"},{"name":"bell peppers","quantity":80,"unit":"g"},{"name":"tomatoes","quantity":60,"unit":"g"},{"name":"baby corn","quantity":50,"unit":"g"},{"name":"oyster sauce","quantity":25,"unit":"ml"},{"name":"fish sauce","quantity":20,"unit":"ml"},{"name":"soy sauce","quantity":15,"unit":"ml"},{"name":"egg","quantity":1,"unit":"whole"}]',
  1,
  550,
  30,
  65,
  18,
  4,
  8,
  1250,
  '["egg","soy","shellfish","fish"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'khao soi',
  'Khao Soi',
  '[{"name":"egg noodles","quantity":200,"unit":"g"},{"name":"chicken thighs","quantity":200,"unit":"g"},{"name":"coconut milk","quantity":300,"unit":"ml"},{"name":"red curry paste","quantity":40,"unit":"g"},{"name":"turmeric","quantity":5,"unit":"g"},{"name":"fish sauce","quantity":25,"unit":"ml"},{"name":"palm sugar","quantity":15,"unit":"g"},{"name":"shallots","quantity":30,"unit":"g"},{"name":"pickled mustard greens","quantity":30,"unit":"g"},{"name":"lime","quantity":1,"unit":"wedge"},{"name":"crispy noodles","quantity":30,"unit":"g"}]',
  1,
  680,
  35,
  55,
  38,
  3,
  10,
  1100,
  '["wheat","egg","fish"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'green curry',
  'Green Curry',
  '[{"name":"chicken thighs","quantity":250,"unit":"g"},{"name":"coconut milk","quantity":400,"unit":"ml"},{"name":"green curry paste","quantity":50,"unit":"g"},{"name":"thai eggplant","quantity":100,"unit":"g"},{"name":"bamboo shoots","quantity":80,"unit":"g"},{"name":"thai basil","quantity":20,"unit":"g"},{"name":"kaffir lime leaves","quantity":4,"unit":"leaves"},{"name":"fish sauce","quantity":25,"unit":"ml"},{"name":"palm sugar","quantity":15,"unit":"g"},{"name":"thai chilies","quantity":10,"unit":"g"}]',
  1,
  520,
  32,
  18,
  38,
  4,
  10,
  980,
  '["fish"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'red curry',
  'Red Curry',
  '[{"name":"beef sirloin","quantity":250,"unit":"g"},{"name":"coconut milk","quantity":400,"unit":"ml"},{"name":"red curry paste","quantity":50,"unit":"g"},{"name":"bamboo shoots","quantity":100,"unit":"g"},{"name":"bell peppers","quantity":80,"unit":"g"},{"name":"thai basil","quantity":20,"unit":"g"},{"name":"kaffir lime leaves","quantity":4,"unit":"leaves"},{"name":"fish sauce","quantity":25,"unit":"ml"},{"name":"palm sugar","quantity":15,"unit":"g"}]',
  1,
  550,
  34,
  16,
  40,
  3,
  10,
  1020,
  '["fish"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'massaman curry',
  'Massaman Curry',
  '[{"name":"beef chuck","quantity":300,"unit":"g"},{"name":"coconut milk","quantity":400,"unit":"ml"},{"name":"massaman curry paste","quantity":50,"unit":"g"},{"name":"potatoes","quantity":150,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"peanuts","quantity":40,"unit":"g"},{"name":"tamarind paste","quantity":20,"unit":"g"},{"name":"fish sauce","quantity":25,"unit":"ml"},{"name":"palm sugar","quantity":20,"unit":"g"},{"name":"cinnamon stick","quantity":1,"unit":"piece"},{"name":"cardamom","quantity":3,"unit":"pods"}]',
  1,
  620,
  38,
  32,
  42,
  4,
  14,
  1050,
  '["fish","peanut"]',
  '["high_fructan","high_polyol","high_gos"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'panang curry',
  'Panang Curry',
  '[{"name":"pork tenderloin","quantity":250,"unit":"g"},{"name":"coconut milk","quantity":350,"unit":"ml"},{"name":"panang curry paste","quantity":50,"unit":"g"},{"name":"kaffir lime leaves","quantity":5,"unit":"leaves"},{"name":"thai basil","quantity":20,"unit":"g"},{"name":"fish sauce","quantity":20,"unit":"ml"},{"name":"palm sugar","quantity":15,"unit":"g"},{"name":"peanuts","quantity":25,"unit":"g"},{"name":"red chilies","quantity":10,"unit":"g"}]',
  1,
  540,
  35,
  14,
  40,
  2,
  10,
  920,
  '["fish","peanut"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tom yum soup',
  'Tom Yum Soup',
  '[{"name":"shrimp","quantity":200,"unit":"g"},{"name":"mushrooms","quantity":100,"unit":"g"},{"name":"lemongrass","quantity":30,"unit":"g"},{"name":"galangal","quantity":20,"unit":"g"},{"name":"kaffir lime leaves","quantity":5,"unit":"leaves"},{"name":"thai chilies","quantity":15,"unit":"g"},{"name":"fish sauce","quantity":30,"unit":"ml"},{"name":"lime juice","quantity":40,"unit":"ml"},{"name":"tom yum paste","quantity":30,"unit":"g"},{"name":"cilantro","quantity":15,"unit":"g"},{"name":"cherry tomatoes","quantity":80,"unit":"g"}]',
  1,
  180,
  26,
  12,
  4,
  2,
  6,
  1350,
  '["shellfish","fish"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free","low-carb","low-fat"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tom kha gai',
  'Tom Kha Gai',
  '[{"name":"chicken breast","quantity":200,"unit":"g"},{"name":"coconut milk","quantity":400,"unit":"ml"},{"name":"mushrooms","quantity":100,"unit":"g"},{"name":"galangal","quantity":25,"unit":"g"},{"name":"lemongrass","quantity":25,"unit":"g"},{"name":"kaffir lime leaves","quantity":4,"unit":"leaves"},{"name":"fish sauce","quantity":25,"unit":"ml"},{"name":"lime juice","quantity":30,"unit":"ml"},{"name":"thai chilies","quantity":10,"unit":"g"},{"name":"cilantro","quantity":15,"unit":"g"}]',
  1,
  420,
  32,
  12,
  30,
  2,
  6,
  980,
  '["fish"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free","low-carb","keto-friendly"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'som tam',
  'Som Tam',
  '[{"name":"green papaya","quantity":250,"unit":"g"},{"name":"cherry tomatoes","quantity":60,"unit":"g"},{"name":"long beans","quantity":50,"unit":"g"},{"name":"dried shrimp","quantity":20,"unit":"g"},{"name":"peanuts","quantity":25,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"thai chilies","quantity":15,"unit":"g"},{"name":"palm sugar","quantity":20,"unit":"g"},{"name":"fish sauce","quantity":25,"unit":"ml"},{"name":"lime juice","quantity":30,"unit":"ml"}]',
  1,
  220,
  10,
  28,
  9,
  5,
  18,
  920,
  '["shellfish","fish","peanut"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'larb',
  'Larb',
  '[{"name":"ground pork","quantity":300,"unit":"g"},{"name":"shallots","quantity":40,"unit":"g"},{"name":"mint","quantity":25,"unit":"g"},{"name":"cilantro","quantity":20,"unit":"g"},{"name":"green onion","quantity":30,"unit":"g"},{"name":"toasted rice powder","quantity":20,"unit":"g"},{"name":"fish sauce","quantity":30,"unit":"ml"},{"name":"lime juice","quantity":40,"unit":"ml"},{"name":"thai chilies","quantity":15,"unit":"g"},{"name":"lettuce","quantity":60,"unit":"g"}]',
  1,
  320,
  28,
  12,
  18,
  2,
  4,
  1100,
  '["fish"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'satay',
  'Satay',
  '[{"name":"chicken thighs","quantity":400,"unit":"g"},{"name":"coconut milk","quantity":100,"unit":"ml"},{"name":"turmeric","quantity":5,"unit":"g"},{"name":"coriander powder","quantity":5,"unit":"g"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"lemongrass","quantity":20,"unit":"g"},{"name":"peanut sauce","quantity":100,"unit":"ml"},{"name":"fish sauce","quantity":15,"unit":"ml"},{"name":"palm sugar","quantity":15,"unit":"g"},{"name":"cucumber","quantity":50,"unit":"g"}]',
  1,
  480,
  38,
  18,
  30,
  2,
  12,
  850,
  '["peanut","fish"]',
  '["high_fructan","high_gos"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'thai spring rolls',
  'Thai Spring Rolls',
  '[{"name":"spring roll wrappers","quantity":8,"unit":"sheets"},{"name":"glass noodles","quantity":50,"unit":"g"},{"name":"ground pork","quantity":150,"unit":"g"},{"name":"cabbage","quantity":80,"unit":"g"},{"name":"carrots","quantity":50,"unit":"g"},{"name":"wood ear mushrooms","quantity":30,"unit":"g"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"soy sauce","quantity":15,"unit":"ml"},{"name":"white pepper","quantity":2,"unit":"g"},{"name":"vegetable oil","quantity":150,"unit":"ml"},{"name":"sweet chili sauce","quantity":50,"unit":"ml"}]',
  1,
  380,
  14,
  38,
  20,
  2,
  8,
  680,
  '["wheat","soy"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pad kra pao',
  'Pad Kra Pao',
  '[{"name":"ground chicken","quantity":300,"unit":"g"},{"name":"thai holy basil","quantity":40,"unit":"g"},{"name":"thai chilies","quantity":20,"unit":"g"},{"name":"garlic","quantity":6,"unit":"cloves"},{"name":"shallots","quantity":30,"unit":"g"},{"name":"fish sauce","quantity":25,"unit":"ml"},{"name":"oyster sauce","quantity":20,"unit":"ml"},{"name":"soy sauce","quantity":15,"unit":"ml"},{"name":"sugar","quantity":10,"unit":"g"},{"name":"fried egg","quantity":1,"unit":"whole"},{"name":"jasmine rice","quantity":200,"unit":"g"}]',
  1,
  580,
  35,
  55,
  24,
  2,
  6,
  1250,
  '["fish","soy","shellfish","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pad prik king',
  'Pad Prik King',
  '[{"name":"pork belly","quantity":250,"unit":"g"},{"name":"long beans","quantity":150,"unit":"g"},{"name":"red curry paste","quantity":40,"unit":"g"},{"name":"kaffir lime leaves","quantity":4,"unit":"leaves"},{"name":"fish sauce","quantity":20,"unit":"ml"},{"name":"palm sugar","quantity":15,"unit":"g"},{"name":"vegetable oil","quantity":30,"unit":"ml"}]',
  1,
  480,
  24,
  18,
  36,
  4,
  10,
  920,
  '["fish"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'crispy pork belly with basil',
  'Crispy Pork Belly with Basil',
  '[{"name":"crispy pork belly","quantity":300,"unit":"g"},{"name":"thai holy basil","quantity":40,"unit":"g"},{"name":"thai chilies","quantity":20,"unit":"g"},{"name":"garlic","quantity":6,"unit":"cloves"},{"name":"oyster sauce","quantity":25,"unit":"ml"},{"name":"fish sauce","quantity":20,"unit":"ml"},{"name":"soy sauce","quantity":15,"unit":"ml"},{"name":"sugar","quantity":10,"unit":"g"},{"name":"jasmine rice","quantity":200,"unit":"g"}]',
  1,
  720,
  32,
  52,
  44,
  2,
  6,
  1350,
  '["fish","soy","shellfish"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'thai fried rice',
  'Thai Fried Rice',
  '[{"name":"jasmine rice","quantity":300,"unit":"g"},{"name":"shrimp","quantity":100,"unit":"g"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"onion","quantity":60,"unit":"g"},{"name":"tomatoes","quantity":60,"unit":"g"},{"name":"green onion","quantity":30,"unit":"g"},{"name":"fish sauce","quantity":25,"unit":"ml"},{"name":"soy sauce","quantity":15,"unit":"ml"},{"name":"white pepper","quantity":2,"unit":"g"},{"name":"lime","quantity":1,"unit":"wedge"},{"name":"cucumber","quantity":40,"unit":"g"}]',
  1,
  480,
  22,
  65,
  14,
  2,
  5,
  1100,
  '["shellfish","egg","fish","soy"]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'mango sticky rice',
  'Mango Sticky Rice',
  '[{"name":"sticky rice","quantity":150,"unit":"g"},{"name":"ripe mango","quantity":200,"unit":"g"},{"name":"coconut milk","quantity":200,"unit":"ml"},{"name":"sugar","quantity":60,"unit":"g"},{"name":"salt","quantity":2,"unit":"g"},{"name":"toasted sesame seeds","quantity":10,"unit":"g"},{"name":"mung beans","quantity":20,"unit":"g"}]',
  1,
  480,
  6,
  82,
  14,
  3,
  45,
  180,
  '["sesame"]',
  '["high_fructose","high_polyol"]',
  '["vegan","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'thai iced tea',
  'Thai Iced Tea',
  '[{"name":"thai tea mix","quantity":30,"unit":"g"},{"name":"condensed milk","quantity":50,"unit":"ml"},{"name":"evaporated milk","quantity":30,"unit":"ml"},{"name":"sugar","quantity":20,"unit":"g"},{"name":"hot water","quantity":200,"unit":"ml"},{"name":"ice","quantity":150,"unit":"g"}]',
  1,
  220,
  4,
  38,
  6,
  0,
  36,
  80,
  '["milk"]',
  '["high_lactose"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'spaghetti and meatballs',
  'Spaghetti and Meatballs',
  '[{"name":"spaghetti","quantity":200,"unit":"g"},{"name":"ground beef","quantity":300,"unit":"g"},{"name":"breadcrumbs","quantity":30,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"parmesan cheese","quantity":30,"unit":"g"},{"name":"marinara sauce","quantity":250,"unit":"ml"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"olive oil","quantity":15,"unit":"ml"},{"name":"basil","quantity":5,"unit":"g"}]',
  1,
  650,
  35,
  70,
  25,
  4,
  8,
  850,
  '["gluten","egg","milk"]',
  '["high_fructan","moderate_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'penne arrabbiata',
  'Penne Arrabbiata',
  '[{"name":"penne pasta","quantity":200,"unit":"g"},{"name":"crushed tomatoes","quantity":400,"unit":"g"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"red chili flakes","quantity":5,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"parsley","quantity":10,"unit":"g"}]',
  1,
  420,
  12,
  72,
  10,
  4,
  6,
  320,
  '["gluten"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'classic cheeseburger',
  'Classic Cheeseburger',
  '[{"name":"ground beef patty","quantity":150,"unit":"g"},{"name":"hamburger bun","quantity":1,"unit":"whole"},{"name":"cheddar cheese","quantity":30,"unit":"g"},{"name":"lettuce","quantity":20,"unit":"g"},{"name":"tomato","quantity":30,"unit":"g"},{"name":"onion","quantity":20,"unit":"g"},{"name":"pickles","quantity":15,"unit":"g"},{"name":"ketchup","quantity":15,"unit":"ml"},{"name":"mustard","quantity":10,"unit":"ml"}]',
  1,
  550,
  32,
  35,
  32,
  2,
  8,
  850,
  '["gluten","milk"]',
  '["high_fructan","moderate_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bacon cheeseburger',
  'Bacon Cheeseburger',
  '[{"name":"ground beef patty","quantity":150,"unit":"g"},{"name":"hamburger bun","quantity":1,"unit":"whole"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"cheddar cheese","quantity":30,"unit":"g"},{"name":"lettuce","quantity":20,"unit":"g"},{"name":"tomato","quantity":30,"unit":"g"},{"name":"onion","quantity":20,"unit":"g"}]',
  1,
  680,
  38,
  35,
  42,
  2,
  6,
  1150,
  '["gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pad thai',
  'Pad Thai',
  '[{"name":"rice noodles","quantity":200,"unit":"g"},{"name":"shrimp","quantity":150,"unit":"g"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"tofu","quantity":100,"unit":"g"},{"name":"bean sprouts","quantity":80,"unit":"g"},{"name":"peanuts","quantity":30,"unit":"g"},{"name":"green onion","quantity":20,"unit":"g"},{"name":"fish sauce","quantity":30,"unit":"ml"},{"name":"tamarind paste","quantity":20,"unit":"g"},{"name":"palm sugar","quantity":15,"unit":"g"},{"name":"lime","quantity":1,"unit":"wedge"}]',
  1,
  580,
  28,
  65,
  22,
  3,
  12,
  1200,
  '["shellfish","peanut","egg","soy","fish"]',
  '["high_fructan","high_gos"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken burrito',
  'Chicken Burrito',
  '[{"name":"flour tortilla","quantity":1,"unit":"large"},{"name":"grilled chicken","quantity":150,"unit":"g"},{"name":"rice","quantity":100,"unit":"g"},{"name":"black beans","quantity":80,"unit":"g"},{"name":"cheddar cheese","quantity":40,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"guacamole","quantity":50,"unit":"g"},{"name":"salsa","quantity":50,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"}]',
  1,
  720,
  42,
  68,
  28,
  8,
  4,
  1250,
  '["gluten","milk"]',
  '["high_gos","moderate_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'beef tacos',
  'Beef Tacos',
  '[{"name":"corn tortillas","quantity":3,"unit":"pieces"},{"name":"ground beef","quantity":150,"unit":"g"},{"name":"taco seasoning","quantity":15,"unit":"g"},{"name":"cheddar cheese","quantity":40,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"},{"name":"tomato","quantity":40,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"salsa","quantity":40,"unit":"g"}]',
  1,
  480,
  28,
  35,
  26,
  4,
  4,
  820,
  '["milk"]',
  '["moderate_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken quesadilla',
  'Chicken Quesadilla',
  '[{"name":"flour tortilla","quantity":2,"unit":"large"},{"name":"grilled chicken","quantity":120,"unit":"g"},{"name":"cheddar cheese","quantity":80,"unit":"g"},{"name":"peppers","quantity":40,"unit":"g"},{"name":"onion","quantity":30,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"salsa","quantity":40,"unit":"g"}]',
  1,
  580,
  35,
  42,
  30,
  3,
  4,
  980,
  '["gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'caesar salad',
  'Caesar Salad',
  '[{"name":"romaine lettuce","quantity":200,"unit":"g"},{"name":"parmesan cheese","quantity":40,"unit":"g"},{"name":"croutons","quantity":40,"unit":"g"},{"name":"caesar dressing","quantity":60,"unit":"ml"},{"name":"lemon juice","quantity":15,"unit":"ml"},{"name":"anchovy paste","quantity":5,"unit":"g"}]',
  1,
  380,
  12,
  18,
  30,
  4,
  3,
  780,
  '["gluten","milk","egg","fish"]',
  '["low"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');
