INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'rotkohl red cabbage',
  'Rotkohl (Red Cabbage)',
  '[{"name":"red cabbage","quantity":500,"unit":"g"},{"name":"apple","quantity":100,"unit":"g"},{"name":"red wine vinegar","quantity":40,"unit":"ml"},{"name":"sugar","quantity":30,"unit":"g"},{"name":"cloves","quantity":3,"unit":"pieces"},{"name":"bay leaf","quantity":1,"unit":"piece"}]',
  1,
  120,
  3,
  26,
  1,
  5,
  18,
  180,
  '[]',
  '["high_fructan","high_polyol"]',
  '["vegan","gluten-free","dairy-free","low-fat"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'black forest cake',
  'Black Forest Cake',
  '[{"name":"chocolate sponge","quantity":400,"unit":"g"},{"name":"cherries","quantity":300,"unit":"g"},{"name":"whipped cream","quantity":500,"unit":"ml"},{"name":"kirsch","quantity":60,"unit":"ml"},{"name":"chocolate shavings","quantity":80,"unit":"g"}]',
  1,
  420,
  6,
  48,
  24,
  2,
  36,
  120,
  '["wheat","milk","egg"]',
  '["high_lactose","high_polyol"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'apple strudel',
  'Apple Strudel',
  '[{"name":"apples","quantity":600,"unit":"g"},{"name":"strudel dough","quantity":200,"unit":"g"},{"name":"breadcrumbs","quantity":60,"unit":"g"},{"name":"butter","quantity":80,"unit":"g"},{"name":"sugar","quantity":80,"unit":"g"},{"name":"cinnamon","quantity":5,"unit":"g"},{"name":"raisins","quantity":60,"unit":"g"}]',
  1,
  340,
  4,
  52,
  14,
  3,
  32,
  180,
  '["wheat","milk"]',
  '["high_fructan","high_polyol","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'berliner jam donut',
  'Berliner (Jam Donut)',
  '[{"name":"flour","quantity":400,"unit":"g"},{"name":"yeast","quantity":15,"unit":"g"},{"name":"butter","quantity":60,"unit":"g"},{"name":"eggs","quantity":2,"unit":"pieces"},{"name":"jam","quantity":150,"unit":"g"},{"name":"powdered sugar","quantity":60,"unit":"g"},{"name":"vegetable oil","quantity":500,"unit":"ml"}]',
  1,
  320,
  6,
  46,
  14,
  1,
  22,
  140,
  '["wheat","egg","milk"]',
  '["high_fructan","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'stollen',
  'Stollen',
  '[{"name":"flour","quantity":500,"unit":"g"},{"name":"butter","quantity":200,"unit":"g"},{"name":"marzipan","quantity":150,"unit":"g"},{"name":"raisins","quantity":150,"unit":"g"},{"name":"candied citrus peel","quantity":100,"unit":"g"},{"name":"almonds","quantity":80,"unit":"g"},{"name":"powdered sugar","quantity":60,"unit":"g"}]',
  1,
  380,
  6,
  52,
  18,
  2,
  28,
  160,
  '["wheat","milk","tree_nut"]',
  '["high_fructan","high_fructose","high_polyol"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');
