INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chana masala',
  'Chana Masala',
  '[{"name":"chickpeas","quantity":400,"unit":"g"},{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"ginger","quantity":20,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"coriander powder","quantity":10,"unit":"g"},{"name":"cumin","quantity":6,"unit":"g"},{"name":"garam masala","quantity":8,"unit":"g"},{"name":"amchur powder","quantity":5,"unit":"g"},{"name":"vegetable oil","quantity":30,"unit":"ml"},{"name":"cilantro","quantity":20,"unit":"g"}]',
  1,
  320,
  14,
  45,
  10,
  12,
  8,
  420,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'biryani',
  'Biryani',
  '[{"name":"basmati rice","quantity":300,"unit":"g"},{"name":"chicken","quantity":400,"unit":"g"},{"name":"yogurt","quantity":150,"unit":"g"},{"name":"onion","quantity":200,"unit":"g"},{"name":"tomatoes","quantity":100,"unit":"g"},{"name":"biryani masala","quantity":20,"unit":"g"},{"name":"saffron","quantity":0.5,"unit":"g"},{"name":"ghee","quantity":50,"unit":"g"},{"name":"mint","quantity":20,"unit":"g"},{"name":"ginger","quantity":20,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"}]',
  1,
  580,
  35,
  58,
  24,
  3,
  6,
  650,
  '["milk"]',
  '["high_lactose","high_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'naan',
  'Naan',
  '[{"name":"all-purpose flour","quantity":300,"unit":"g"},{"name":"yogurt","quantity":100,"unit":"g"},{"name":"milk","quantity":60,"unit":"ml"},{"name":"yeast","quantity":5,"unit":"g"},{"name":"sugar","quantity":10,"unit":"g"},{"name":"ghee","quantity":30,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"cilantro","quantity":10,"unit":"g"}]',
  1,
  280,
  8,
  45,
  8,
  2,
  4,
  320,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'samosas',
  'Samosas',
  '[{"name":"all-purpose flour","quantity":200,"unit":"g"},{"name":"potatoes","quantity":300,"unit":"g"},{"name":"peas","quantity":80,"unit":"g"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"coriander powder","quantity":5,"unit":"g"},{"name":"garam masala","quantity":5,"unit":"g"},{"name":"green chilies","quantity":15,"unit":"g"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"vegetable oil","quantity":150,"unit":"ml"},{"name":"mint chutney","quantity":50,"unit":"ml"}]',
  1,
  320,
  6,
  38,
  16,
  4,
  2,
  280,
  '["wheat"]',
  '["high_fructan","high_gos"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'masala dosa',
  'Masala Dosa',
  '[{"name":"rice","quantity":200,"unit":"g"},{"name":"urad dal","quantity":60,"unit":"g"},{"name":"potatoes","quantity":300,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"mustard seeds","quantity":5,"unit":"g"},{"name":"curry leaves","quantity":10,"unit":"leaves"},{"name":"turmeric","quantity":3,"unit":"g"},{"name":"green chilies","quantity":10,"unit":"g"},{"name":"vegetable oil","quantity":30,"unit":"ml"},{"name":"sambar","quantity":150,"unit":"ml"},{"name":"coconut chutney","quantity":60,"unit":"ml"}]',
  1,
  380,
  10,
  62,
  10,
  5,
  4,
  450,
  '[]',
  '["high_fructan","high_gos"]',
  '["vegan","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'idli with sambar',
  'Idli with Sambar',
  '[{"name":"rice","quantity":200,"unit":"g"},{"name":"urad dal","quantity":100,"unit":"g"},{"name":"toor dal","quantity":100,"unit":"g"},{"name":"tamarind","quantity":20,"unit":"g"},{"name":"sambar powder","quantity":15,"unit":"g"},{"name":"drumstick","quantity":50,"unit":"g"},{"name":"tomatoes","quantity":80,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"mustard seeds","quantity":3,"unit":"g"},{"name":"curry leaves","quantity":8,"unit":"leaves"}]',
  1,
  320,
  12,
  58,
  4,
  8,
  4,
  380,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free","low-fat"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chole bhature',
  'Chole Bhature',
  '[{"name":"chickpeas","quantity":300,"unit":"g"},{"name":"all-purpose flour","quantity":250,"unit":"g"},{"name":"yogurt","quantity":60,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":150,"unit":"g"},{"name":"ginger","quantity":20,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"chole masala","quantity":15,"unit":"g"},{"name":"vegetable oil","quantity":150,"unit":"ml"},{"name":"amchur powder","quantity":5,"unit":"g"}]',
  1,
  520,
  16,
  68,
  20,
  10,
  8,
  580,
  '["wheat","milk"]',
  '["high_gos","high_fructan"]',
  '["vegetarian","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'raita',
  'Raita',
  '[{"name":"yogurt","quantity":300,"unit":"g"},{"name":"cucumber","quantity":100,"unit":"g"},{"name":"tomatoes","quantity":50,"unit":"g"},{"name":"onion","quantity":30,"unit":"g"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"mint","quantity":10,"unit":"g"},{"name":"salt","quantity":3,"unit":"g"}]',
  1,
  120,
  8,
  12,
  4,
  1,
  10,
  320,
  '["milk"]',
  '["high_lactose","high_fructan"]',
  '["vegetarian","gluten-free","low-calorie"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'gulab jamun',
  'Gulab Jamun',
  '[{"name":"milk powder","quantity":200,"unit":"g"},{"name":"all-purpose flour","quantity":40,"unit":"g"},{"name":"ghee","quantity":30,"unit":"g"},{"name":"baking soda","quantity":2,"unit":"g"},{"name":"milk","quantity":60,"unit":"ml"},{"name":"sugar","quantity":300,"unit":"g"},{"name":"cardamom","quantity":4,"unit":"pods"},{"name":"rose water","quantity":10,"unit":"ml"},{"name":"vegetable oil","quantity":200,"unit":"ml"}]',
  1,
  380,
  6,
  58,
  14,
  0,
  48,
  120,
  '["wheat","milk"]',
  '["high_lactose","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'jalebi',
  'Jalebi',
  '[{"name":"all-purpose flour","quantity":200,"unit":"g"},{"name":"yogurt","quantity":30,"unit":"g"},{"name":"sugar","quantity":250,"unit":"g"},{"name":"saffron","quantity":0.3,"unit":"g"},{"name":"cardamom","quantity":3,"unit":"pods"},{"name":"rose water","quantity":10,"unit":"ml"},{"name":"vegetable oil","quantity":200,"unit":"ml"}]',
  1,
  350,
  4,
  62,
  10,
  0,
  45,
  80,
  '["wheat","milk"]',
  '["high_fructan","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chai',
  'Chai',
  '[{"name":"black tea","quantity":10,"unit":"g"},{"name":"milk","quantity":200,"unit":"ml"},{"name":"sugar","quantity":20,"unit":"g"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"cardamom","quantity":2,"unit":"pods"},{"name":"cinnamon","quantity":2,"unit":"g"},{"name":"cloves","quantity":2,"unit":"whole"}]',
  1,
  120,
  4,
  18,
  4,
  0,
  16,
  60,
  '["milk"]',
  '["high_lactose"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'hummus',
  'Hummus',
  '[{"name":"chickpeas","quantity":400,"unit":"g"},{"name":"tahini","quantity":80,"unit":"g"},{"name":"lemon juice","quantity":50,"unit":"ml"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"paprika","quantity":2,"unit":"g"},{"name":"salt","quantity":5,"unit":"g"}]',
  1,
  280,
  10,
  28,
  16,
  6,
  2,
  380,
  '["sesame"]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'baba ghanoush',
  'Baba Ghanoush',
  '[{"name":"eggplant","quantity":500,"unit":"g"},{"name":"tahini","quantity":60,"unit":"g"},{"name":"lemon juice","quantity":40,"unit":"ml"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"parsley","quantity":15,"unit":"g"},{"name":"pomegranate seeds","quantity":20,"unit":"g"},{"name":"cumin","quantity":2,"unit":"g"}]',
  1,
  180,
  5,
  16,
  12,
  6,
  6,
  280,
  '["sesame"]',
  '["high_fructan","high_polyol"]',
  '["vegan","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'labneh',
  'Labneh',
  '[{"name":"strained yogurt","quantity":400,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"za''atar","quantity":10,"unit":"g"},{"name":"salt","quantity":3,"unit":"g"},{"name":"mint","quantity":5,"unit":"g"}]',
  1,
  180,
  12,
  8,
  12,
  0,
  6,
  420,
  '["milk"]',
  '["high_lactose"]',
  '["vegetarian","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'falafel',
  'Falafel',
  '[{"name":"chickpeas","quantity":400,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"parsley","quantity":40,"unit":"g"},{"name":"cilantro","quantity":30,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"cumin","quantity":8,"unit":"g"},{"name":"coriander powder","quantity":5,"unit":"g"},{"name":"baking powder","quantity":5,"unit":"g"},{"name":"vegetable oil","quantity":150,"unit":"ml"},{"name":"tahini sauce","quantity":50,"unit":"ml"}]',
  1,
  340,
  14,
  38,
  16,
  8,
  4,
  420,
  '["sesame"]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken shawarma',
  'Chicken Shawarma',
  '[{"name":"chicken thighs","quantity":500,"unit":"g"},{"name":"yogurt","quantity":100,"unit":"g"},{"name":"shawarma spices","quantity":20,"unit":"g"},{"name":"lemon juice","quantity":30,"unit":"ml"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"pita bread","quantity":2,"unit":"pieces"},{"name":"pickled turnips","quantity":40,"unit":"g"},{"name":"garlic sauce","quantity":50,"unit":"ml"},{"name":"tomatoes","quantity":60,"unit":"g"}]',
  1,
  520,
  42,
  35,
  24,
  2,
  4,
  780,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'beef shawarma',
  'Beef Shawarma',
  '[{"name":"beef sirloin","quantity":500,"unit":"g"},{"name":"lamb fat","quantity":50,"unit":"g"},{"name":"shawarma spices","quantity":25,"unit":"g"},{"name":"vinegar","quantity":30,"unit":"ml"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"pita bread","quantity":2,"unit":"pieces"},{"name":"tahini sauce","quantity":50,"unit":"ml"},{"name":"pickles","quantity":40,"unit":"g"},{"name":"parsley","quantity":15,"unit":"g"}]',
  1,
  580,
  45,
  32,
  32,
  2,
  4,
  820,
  '["wheat","sesame"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kafta kebab',
  'Kafta Kebab',
  '[{"name":"ground beef","quantity":400,"unit":"g"},{"name":"ground lamb","quantity":100,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"parsley","quantity":40,"unit":"g"},{"name":"allspice","quantity":5,"unit":"g"},{"name":"cinnamon","quantity":2,"unit":"g"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"black pepper","quantity":2,"unit":"g"},{"name":"olive oil","quantity":20,"unit":"ml"}]',
  1,
  380,
  32,
  6,
  26,
  1,
  2,
  480,
  '[]',
  '["high_fructan"]',
  '["dairy-free","gluten-free","low-carb","keto-friendly"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'shish tawook',
  'Shish Tawook',
  '[{"name":"chicken breast","quantity":500,"unit":"g"},{"name":"yogurt","quantity":150,"unit":"g"},{"name":"lemon juice","quantity":40,"unit":"ml"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"tomato paste","quantity":20,"unit":"g"},{"name":"paprika","quantity":5,"unit":"g"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"garlic sauce","quantity":60,"unit":"ml"}]',
  1,
  380,
  48,
  10,
  16,
  1,
  6,
  520,
  '["milk"]',
  '["high_lactose","high_fructan"]',
  '["gluten-free","low-carb","high-protein"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kibbeh',
  'Kibbeh',
  '[{"name":"bulgur wheat","quantity":150,"unit":"g"},{"name":"ground lamb","quantity":400,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"pine nuts","quantity":40,"unit":"g"},{"name":"allspice","quantity":5,"unit":"g"},{"name":"cinnamon","quantity":3,"unit":"g"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"vegetable oil","quantity":150,"unit":"ml"}]',
  1,
  420,
  26,
  28,
  24,
  4,
  2,
  380,
  '["wheat","tree_nut"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'maqluba',
  'Maqluba',
  '[{"name":"basmati rice","quantity":300,"unit":"g"},{"name":"chicken","quantity":500,"unit":"g"},{"name":"eggplant","quantity":300,"unit":"g"},{"name":"cauliflower","quantity":200,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":100,"unit":"g"},{"name":"allspice","quantity":8,"unit":"g"},{"name":"turmeric","quantity":3,"unit":"g"},{"name":"vegetable oil","quantity":100,"unit":"ml"},{"name":"pine nuts","quantity":30,"unit":"g"}]',
  1,
  580,
  35,
  52,
  28,
  5,
  6,
  520,
  '["tree_nut"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'stuffed grape leaves',
  'Stuffed Grape Leaves',
  '[{"name":"grape leaves","quantity":40,"unit":"leaves"},{"name":"rice","quantity":200,"unit":"g"},{"name":"ground beef","quantity":150,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"tomatoes","quantity":100,"unit":"g"},{"name":"parsley","quantity":30,"unit":"g"},{"name":"mint","quantity":15,"unit":"g"},{"name":"allspice","quantity":5,"unit":"g"},{"name":"lemon juice","quantity":50,"unit":"ml"},{"name":"olive oil","quantity":40,"unit":"ml"}]',
  1,
  280,
  12,
  32,
  12,
  3,
  4,
  420,
  '[]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'mujaddara',
  'Mujaddara',
  '[{"name":"green lentils","quantity":200,"unit":"g"},{"name":"rice","quantity":150,"unit":"g"},{"name":"onion","quantity":300,"unit":"g"},{"name":"olive oil","quantity":80,"unit":"ml"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"coriander powder","quantity":3,"unit":"g"},{"name":"salt","quantity":5,"unit":"g"},{"name":"yogurt","quantity":100,"unit":"g"}]',
  1,
  380,
  14,
  52,
  14,
  10,
  6,
  380,
  '["milk"]',
  '["high_gos","high_fructan"]',
  '["vegetarian","gluten-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'fattoush',
  'Fattoush',
  '[{"name":"romaine lettuce","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":150,"unit":"g"},{"name":"cucumber","quantity":150,"unit":"g"},{"name":"radishes","quantity":80,"unit":"g"},{"name":"pita chips","quantity":60,"unit":"g"},{"name":"sumac","quantity":8,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"lemon juice","quantity":30,"unit":"ml"},{"name":"mint","quantity":15,"unit":"g"},{"name":"parsley","quantity":20,"unit":"g"}]',
  1,
  220,
  4,
  24,
  12,
  4,
  6,
  280,
  '["wheat"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tabbouleh',
  'Tabbouleh',
  '[{"name":"bulgur wheat","quantity":60,"unit":"g"},{"name":"parsley","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":150,"unit":"g"},{"name":"mint","quantity":30,"unit":"g"},{"name":"green onion","quantity":40,"unit":"g"},{"name":"lemon juice","quantity":50,"unit":"ml"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"salt","quantity":3,"unit":"g"}]',
  1,
  180,
  4,
  22,
  10,
  5,
  3,
  320,
  '["wheat"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'manakish',
  'Manakish',
  '[{"name":"pizza dough","quantity":300,"unit":"g"},{"name":"za''atar","quantity":40,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"},{"name":"sesame seeds","quantity":10,"unit":"g"}]',
  1,
  380,
  10,
  52,
  16,
  4,
  2,
  480,
  '["wheat","sesame"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'fatayer',
  'Fatayer',
  '[{"name":"pizza dough","quantity":300,"unit":"g"},{"name":"spinach","quantity":300,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"sumac","quantity":8,"unit":"g"},{"name":"lemon juice","quantity":20,"unit":"ml"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"pine nuts","quantity":20,"unit":"g"}]',
  1,
  320,
  10,
  42,
  14,
  5,
  3,
  420,
  '["wheat","tree_nut"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'shakshuka',
  'Shakshuka',
  '[{"name":"eggs","quantity":4,"unit":"whole"},{"name":"tomatoes","quantity":400,"unit":"g"},{"name":"bell peppers","quantity":150,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"paprika","quantity":5,"unit":"g"},{"name":"harissa","quantity":15,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"feta cheese","quantity":50,"unit":"g"}]',
  1,
  320,
  18,
  18,
  22,
  4,
  10,
  580,
  '["egg","milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'lentil soup',
  'Lentil Soup',
  '[{"name":"red lentils","quantity":250,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"carrots","quantity":100,"unit":"g"},{"name":"celery","quantity":50,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"cumin","quantity":8,"unit":"g"},{"name":"lemon juice","quantity":30,"unit":"ml"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"vegetable broth","quantity":1000,"unit":"ml"}]',
  1,
  280,
  16,
  42,
  6,
  14,
  6,
  520,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free","high-fiber","low-fat"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'baklava',
  'Baklava',
  '[{"name":"phyllo dough","quantity":400,"unit":"g"},{"name":"walnuts","quantity":200,"unit":"g"},{"name":"pistachios","quantity":100,"unit":"g"},{"name":"butter","quantity":200,"unit":"g"},{"name":"sugar","quantity":200,"unit":"g"},{"name":"honey","quantity":100,"unit":"g"},{"name":"lemon juice","quantity":20,"unit":"ml"},{"name":"rose water","quantity":10,"unit":"ml"},{"name":"cinnamon","quantity":3,"unit":"g"}]',
  1,
  420,
  6,
  48,
  24,
  2,
  32,
  180,
  '["wheat","milk","tree_nut"]',
  '["high_fructan","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kunafa',
  'Kunafa',
  '[{"name":"kataifi pastry","quantity":400,"unit":"g"},{"name":"mozzarella cheese","quantity":300,"unit":"g"},{"name":"ricotta cheese","quantity":200,"unit":"g"},{"name":"butter","quantity":150,"unit":"g"},{"name":"sugar syrup","quantity":250,"unit":"ml"},{"name":"rose water","quantity":15,"unit":"ml"},{"name":"pistachios","quantity":40,"unit":"g"}]',
  1,
  480,
  14,
  52,
  26,
  1,
  35,
  420,
  '["wheat","milk","tree_nut"]',
  '["high_lactose","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'spaghetti and meatballs',
  'Spaghetti and Meatballs',
  '[{"name":"spaghetti","quantity":200,"unit":"g"},{"name":"ground beef","quantity":300,"unit":"g"},{"name":"breadcrumbs","quantity":30,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"parmesan cheese","quantity":30,"unit":"g"},{"name":"marinara sauce","quantity":250,"unit":"ml"},{"name":"garlic","quantity":3,"unit":"cloves"},{"name":"olive oil","quantity":15,"unit":"ml"},{"name":"basil","quantity":5,"unit":"g"}]',
  1,
  650,
  35,
  70,
  25,
  4,
  8,
  850,
  '["gluten","egg","milk"]',
  '["high_fructan","moderate_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'penne arrabbiata',
  'Penne Arrabbiata',
  '[{"name":"penne pasta","quantity":200,"unit":"g"},{"name":"crushed tomatoes","quantity":400,"unit":"g"},{"name":"garlic","quantity":4,"unit":"cloves"},{"name":"red chili flakes","quantity":5,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"parsley","quantity":10,"unit":"g"}]',
  1,
  420,
  12,
  72,
  10,
  4,
  6,
  320,
  '["gluten"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'classic cheeseburger',
  'Classic Cheeseburger',
  '[{"name":"ground beef patty","quantity":150,"unit":"g"},{"name":"hamburger bun","quantity":1,"unit":"whole"},{"name":"cheddar cheese","quantity":30,"unit":"g"},{"name":"lettuce","quantity":20,"unit":"g"},{"name":"tomato","quantity":30,"unit":"g"},{"name":"onion","quantity":20,"unit":"g"},{"name":"pickles","quantity":15,"unit":"g"},{"name":"ketchup","quantity":15,"unit":"ml"},{"name":"mustard","quantity":10,"unit":"ml"}]',
  1,
  550,
  32,
  35,
  32,
  2,
  8,
  850,
  '["gluten","milk"]',
  '["high_fructan","moderate_polyol"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'bacon cheeseburger',
  'Bacon Cheeseburger',
  '[{"name":"ground beef patty","quantity":150,"unit":"g"},{"name":"hamburger bun","quantity":1,"unit":"whole"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"cheddar cheese","quantity":30,"unit":"g"},{"name":"lettuce","quantity":20,"unit":"g"},{"name":"tomato","quantity":30,"unit":"g"},{"name":"onion","quantity":20,"unit":"g"}]',
  1,
  680,
  38,
  35,
  42,
  2,
  6,
  1150,
  '["gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pad thai',
  'Pad Thai',
  '[{"name":"rice noodles","quantity":200,"unit":"g"},{"name":"shrimp","quantity":150,"unit":"g"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"tofu","quantity":100,"unit":"g"},{"name":"bean sprouts","quantity":80,"unit":"g"},{"name":"peanuts","quantity":30,"unit":"g"},{"name":"green onion","quantity":20,"unit":"g"},{"name":"fish sauce","quantity":30,"unit":"ml"},{"name":"tamarind paste","quantity":20,"unit":"g"},{"name":"palm sugar","quantity":15,"unit":"g"},{"name":"lime","quantity":1,"unit":"wedge"}]',
  1,
  580,
  28,
  65,
  22,
  3,
  12,
  1200,
  '["shellfish","peanut","egg","soy","fish"]',
  '["high_fructan","high_gos"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken burrito',
  'Chicken Burrito',
  '[{"name":"flour tortilla","quantity":1,"unit":"large"},{"name":"grilled chicken","quantity":150,"unit":"g"},{"name":"rice","quantity":100,"unit":"g"},{"name":"black beans","quantity":80,"unit":"g"},{"name":"cheddar cheese","quantity":40,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"guacamole","quantity":50,"unit":"g"},{"name":"salsa","quantity":50,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"}]',
  1,
  720,
  42,
  68,
  28,
  8,
  4,
  1250,
  '["gluten","milk"]',
  '["high_gos","moderate_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'beef tacos',
  'Beef Tacos',
  '[{"name":"corn tortillas","quantity":3,"unit":"pieces"},{"name":"ground beef","quantity":150,"unit":"g"},{"name":"taco seasoning","quantity":15,"unit":"g"},{"name":"cheddar cheese","quantity":40,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"},{"name":"tomato","quantity":40,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"salsa","quantity":40,"unit":"g"}]',
  1,
  480,
  28,
  35,
  26,
  4,
  4,
  820,
  '["milk"]',
  '["moderate_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken quesadilla',
  'Chicken Quesadilla',
  '[{"name":"flour tortilla","quantity":2,"unit":"large"},{"name":"grilled chicken","quantity":120,"unit":"g"},{"name":"cheddar cheese","quantity":80,"unit":"g"},{"name":"peppers","quantity":40,"unit":"g"},{"name":"onion","quantity":30,"unit":"g"},{"name":"sour cream","quantity":30,"unit":"g"},{"name":"salsa","quantity":40,"unit":"g"}]',
  1,
  580,
  35,
  42,
  30,
  3,
  4,
  980,
  '["gluten","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'caesar salad',
  'Caesar Salad',
  '[{"name":"romaine lettuce","quantity":200,"unit":"g"},{"name":"parmesan cheese","quantity":40,"unit":"g"},{"name":"croutons","quantity":40,"unit":"g"},{"name":"caesar dressing","quantity":60,"unit":"ml"},{"name":"lemon juice","quantity":15,"unit":"ml"},{"name":"anchovy paste","quantity":5,"unit":"g"}]',
  1,
  380,
  12,
  18,
  30,
  4,
  3,
  780,
  '["gluten","milk","egg","fish"]',
  '["low"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken caesar salad',
  'Chicken Caesar Salad',
  '[{"name":"romaine lettuce","quantity":200,"unit":"g"},{"name":"grilled chicken breast","quantity":150,"unit":"g"},{"name":"parmesan cheese","quantity":40,"unit":"g"},{"name":"croutons","quantity":40,"unit":"g"},{"name":"caesar dressing","quantity":60,"unit":"ml"},{"name":"lemon juice","quantity":15,"unit":"ml"}]',
  1,
  520,
  42,
  18,
  32,
  4,
  3,
  920,
  '["gluten","milk","egg","fish"]',
  '["low"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'greek salad',
  'Greek Salad',
  '[{"name":"cucumber","quantity":100,"unit":"g"},{"name":"tomato","quantity":120,"unit":"g"},{"name":"red onion","quantity":40,"unit":"g"},{"name":"kalamata olives","quantity":40,"unit":"g"},{"name":"feta cheese","quantity":60,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"oregano","quantity":2,"unit":"g"},{"name":"red wine vinegar","quantity":15,"unit":"ml"}]',
  1,
  320,
  8,
  12,
  28,
  3,
  6,
  680,
  '["milk"]',
  '["high_fructan","moderate_polyol"]',
  '["vegetarian","gluten-free","keto"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'cobb salad',
  'Cobb Salad',
  '[{"name":"mixed greens","quantity":150,"unit":"g"},{"name":"grilled chicken","quantity":120,"unit":"g"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"hard-boiled egg","quantity":2,"unit":"whole"},{"name":"avocado","quantity":80,"unit":"g"},{"name":"tomato","quantity":60,"unit":"g"},{"name":"blue cheese","quantity":40,"unit":"g"},{"name":"red wine vinaigrette","quantity":45,"unit":"ml"}]',
  1,
  580,
  38,
  14,
  42,
  6,
  4,
  920,
  '["egg","milk"]',
  '["moderate_polyol"]',
  '["gluten-free","keto"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'club sandwich',
  'Club Sandwich',
  '[{"name":"white bread","quantity":3,"unit":"slices"},{"name":"turkey breast","quantity":80,"unit":"g"},{"name":"bacon","quantity":40,"unit":"g"},{"name":"lettuce","quantity":30,"unit":"g"},{"name":"tomato","quantity":40,"unit":"g"},{"name":"mayonnaise","quantity":30,"unit":"g"}]',
  1,
  520,
  28,
  38,
  28,
  3,
  5,
  1150,
  '["gluten","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'blt sandwich',
  'BLT Sandwich',
  '[{"name":"white bread","quantity":2,"unit":"slices"},{"name":"bacon","quantity":60,"unit":"g"},{"name":"lettuce","quantity":40,"unit":"g"},{"name":"tomato","quantity":60,"unit":"g"},{"name":"mayonnaise","quantity":30,"unit":"g"}]',
  1,
  450,
  18,
  28,
  30,
  2,
  4,
  980,
  '["gluten","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'grilled cheese sandwich',
  'Grilled Cheese Sandwich',
  '[{"name":"white bread","quantity":2,"unit":"slices"},{"name":"cheddar cheese","quantity":60,"unit":"g"},{"name":"butter","quantity":20,"unit":"g"}]',
  1,
  420,
  15,
  28,
  28,
  1,
  3,
  680,
  '["gluten","milk"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'eggs benedict',
  'Eggs Benedict',
  '[{"name":"English muffin","quantity":1,"unit":"whole"},{"name":"Canadian bacon","quantity":60,"unit":"g"},{"name":"poached egg","quantity":2,"unit":"whole"},{"name":"hollandaise sauce","quantity":60,"unit":"ml"}]',
  1,
  580,
  25,
  28,
  42,
  2,
  2,
  1150,
  '["gluten","egg","milk"]',
  '["high_fructan"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pancakes',
  'Pancakes',
  '[{"name":"all-purpose flour","quantity":150,"unit":"g"},{"name":"milk","quantity":240,"unit":"ml"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"butter","quantity":30,"unit":"g"},{"name":"maple syrup","quantity":60,"unit":"ml"},{"name":"baking powder","quantity":5,"unit":"g"}]',
  1,
  520,
  12,
  82,
  16,
  2,
  35,
  580,
  '["gluten","milk","egg"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'french toast',
  'French Toast',
  '[{"name":"brioche bread","quantity":3,"unit":"slices"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"milk","quantity":60,"unit":"ml"},{"name":"cinnamon","quantity":2,"unit":"g"},{"name":"vanilla extract","quantity":5,"unit":"ml"},{"name":"butter","quantity":20,"unit":"g"},{"name":"maple syrup","quantity":45,"unit":"ml"},{"name":"powdered sugar","quantity":15,"unit":"g"}]',
  1,
  580,
  15,
  72,
  25,
  2,
  42,
  420,
  '["gluten","milk","egg"]',
  '["high_fructan","moderate_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'avocado toast',
  'Avocado Toast',
  '[{"name":"sourdough bread","quantity":2,"unit":"slices"},{"name":"avocado","quantity":150,"unit":"g"},{"name":"lemon juice","quantity":10,"unit":"ml"},{"name":"red pepper flakes","quantity":1,"unit":"g"},{"name":"sea salt","quantity":2,"unit":"g"},{"name":"olive oil","quantity":10,"unit":"ml"}]',
  1,
  380,
  8,
  35,
  24,
  10,
  2,
  520,
  '["gluten"]',
  '["moderate_polyol","high_fructan"]',
  '["vegan","dairy-free","vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');
