INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chana masala',
  'Chana Masala',
  '[{"name":"chickpeas","quantity":400,"unit":"g"},{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"ginger","quantity":20,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"coriander powder","quantity":10,"unit":"g"},{"name":"cumin","quantity":6,"unit":"g"},{"name":"garam masala","quantity":8,"unit":"g"},{"name":"amchur powder","quantity":5,"unit":"g"},{"name":"vegetable oil","quantity":30,"unit":"ml"},{"name":"cilantro","quantity":20,"unit":"g"}]',
  1,
  320,
  14,
  45,
  10,
  12,
  8,
  420,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'biryani',
  'Biryani',
  '[{"name":"basmati rice","quantity":300,"unit":"g"},{"name":"chicken","quantity":400,"unit":"g"},{"name":"yogurt","quantity":150,"unit":"g"},{"name":"onion","quantity":200,"unit":"g"},{"name":"tomatoes","quantity":100,"unit":"g"},{"name":"biryani masala","quantity":20,"unit":"g"},{"name":"saffron","quantity":0.5,"unit":"g"},{"name":"ghee","quantity":50,"unit":"g"},{"name":"mint","quantity":20,"unit":"g"},{"name":"ginger","quantity":20,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"}]',
  1,
  580,
  35,
  58,
  24,
  3,
  6,
  650,
  '["milk"]',
  '["high_lactose","high_fructan"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'naan',
  'Naan',
  '[{"name":"all-purpose flour","quantity":300,"unit":"g"},{"name":"yogurt","quantity":100,"unit":"g"},{"name":"milk","quantity":60,"unit":"ml"},{"name":"yeast","quantity":5,"unit":"g"},{"name":"sugar","quantity":10,"unit":"g"},{"name":"ghee","quantity":30,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"cilantro","quantity":10,"unit":"g"}]',
  1,
  280,
  8,
  45,
  8,
  2,
  4,
  320,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'samosas',
  'Samosas',
  '[{"name":"all-purpose flour","quantity":200,"unit":"g"},{"name":"potatoes","quantity":300,"unit":"g"},{"name":"peas","quantity":80,"unit":"g"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"coriander powder","quantity":5,"unit":"g"},{"name":"garam masala","quantity":5,"unit":"g"},{"name":"green chilies","quantity":15,"unit":"g"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"vegetable oil","quantity":150,"unit":"ml"},{"name":"mint chutney","quantity":50,"unit":"ml"}]',
  1,
  320,
  6,
  38,
  16,
  4,
  2,
  280,
  '["wheat"]',
  '["high_fructan","high_gos"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'masala dosa',
  'Masala Dosa',
  '[{"name":"rice","quantity":200,"unit":"g"},{"name":"urad dal","quantity":60,"unit":"g"},{"name":"potatoes","quantity":300,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"mustard seeds","quantity":5,"unit":"g"},{"name":"curry leaves","quantity":10,"unit":"leaves"},{"name":"turmeric","quantity":3,"unit":"g"},{"name":"green chilies","quantity":10,"unit":"g"},{"name":"vegetable oil","quantity":30,"unit":"ml"},{"name":"sambar","quantity":150,"unit":"ml"},{"name":"coconut chutney","quantity":60,"unit":"ml"}]',
  1,
  380,
  10,
  62,
  10,
  5,
  4,
  450,
  '[]',
  '["high_fructan","high_gos"]',
  '["vegan","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'idli with sambar',
  'Idli with Sambar',
  '[{"name":"rice","quantity":200,"unit":"g"},{"name":"urad dal","quantity":100,"unit":"g"},{"name":"toor dal","quantity":100,"unit":"g"},{"name":"tamarind","quantity":20,"unit":"g"},{"name":"sambar powder","quantity":15,"unit":"g"},{"name":"drumstick","quantity":50,"unit":"g"},{"name":"tomatoes","quantity":80,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"mustard seeds","quantity":3,"unit":"g"},{"name":"curry leaves","quantity":8,"unit":"leaves"}]',
  1,
  320,
  12,
  58,
  4,
  8,
  4,
  380,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free","low-fat"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chole bhature',
  'Chole Bhature',
  '[{"name":"chickpeas","quantity":300,"unit":"g"},{"name":"all-purpose flour","quantity":250,"unit":"g"},{"name":"yogurt","quantity":60,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":150,"unit":"g"},{"name":"ginger","quantity":20,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"chole masala","quantity":15,"unit":"g"},{"name":"vegetable oil","quantity":150,"unit":"ml"},{"name":"amchur powder","quantity":5,"unit":"g"}]',
  1,
  520,
  16,
  68,
  20,
  10,
  8,
  580,
  '["wheat","milk"]',
  '["high_gos","high_fructan"]',
  '["vegetarian","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'raita',
  'Raita',
  '[{"name":"yogurt","quantity":300,"unit":"g"},{"name":"cucumber","quantity":100,"unit":"g"},{"name":"tomatoes","quantity":50,"unit":"g"},{"name":"onion","quantity":30,"unit":"g"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"mint","quantity":10,"unit":"g"},{"name":"salt","quantity":3,"unit":"g"}]',
  1,
  120,
  8,
  12,
  4,
  1,
  10,
  320,
  '["milk"]',
  '["high_lactose","high_fructan"]',
  '["vegetarian","gluten-free","low-calorie"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'gulab jamun',
  'Gulab Jamun',
  '[{"name":"milk powder","quantity":200,"unit":"g"},{"name":"all-purpose flour","quantity":40,"unit":"g"},{"name":"ghee","quantity":30,"unit":"g"},{"name":"baking soda","quantity":2,"unit":"g"},{"name":"milk","quantity":60,"unit":"ml"},{"name":"sugar","quantity":300,"unit":"g"},{"name":"cardamom","quantity":4,"unit":"pods"},{"name":"rose water","quantity":10,"unit":"ml"},{"name":"vegetable oil","quantity":200,"unit":"ml"}]',
  1,
  380,
  6,
  58,
  14,
  0,
  48,
  120,
  '["wheat","milk"]',
  '["high_lactose","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'jalebi',
  'Jalebi',
  '[{"name":"all-purpose flour","quantity":200,"unit":"g"},{"name":"yogurt","quantity":30,"unit":"g"},{"name":"sugar","quantity":250,"unit":"g"},{"name":"saffron","quantity":0.3,"unit":"g"},{"name":"cardamom","quantity":3,"unit":"pods"},{"name":"rose water","quantity":10,"unit":"ml"},{"name":"vegetable oil","quantity":200,"unit":"ml"}]',
  1,
  350,
  4,
  62,
  10,
  0,
  45,
  80,
  '["wheat","milk"]',
  '["high_fructan","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chai',
  'Chai',
  '[{"name":"black tea","quantity":10,"unit":"g"},{"name":"milk","quantity":200,"unit":"ml"},{"name":"sugar","quantity":20,"unit":"g"},{"name":"ginger","quantity":10,"unit":"g"},{"name":"cardamom","quantity":2,"unit":"pods"},{"name":"cinnamon","quantity":2,"unit":"g"},{"name":"cloves","quantity":2,"unit":"whole"}]',
  1,
  120,
  4,
  18,
  4,
  0,
  16,
  60,
  '["milk"]',
  '["high_lactose"]',
  '["vegetarian","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'hummus',
  'Hummus',
  '[{"name":"chickpeas","quantity":400,"unit":"g"},{"name":"tahini","quantity":80,"unit":"g"},{"name":"lemon juice","quantity":50,"unit":"ml"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"paprika","quantity":2,"unit":"g"},{"name":"salt","quantity":5,"unit":"g"}]',
  1,
  280,
  10,
  28,
  16,
  6,
  2,
  380,
  '["sesame"]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'baba ghanoush',
  'Baba Ghanoush',
  '[{"name":"eggplant","quantity":500,"unit":"g"},{"name":"tahini","quantity":60,"unit":"g"},{"name":"lemon juice","quantity":40,"unit":"ml"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"parsley","quantity":15,"unit":"g"},{"name":"pomegranate seeds","quantity":20,"unit":"g"},{"name":"cumin","quantity":2,"unit":"g"}]',
  1,
  180,
  5,
  16,
  12,
  6,
  6,
  280,
  '["sesame"]',
  '["high_fructan","high_polyol"]',
  '["vegan","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'labneh',
  'Labneh',
  '[{"name":"strained yogurt","quantity":400,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"za''atar","quantity":10,"unit":"g"},{"name":"salt","quantity":3,"unit":"g"},{"name":"mint","quantity":5,"unit":"g"}]',
  1,
  180,
  12,
  8,
  12,
  0,
  6,
  420,
  '["milk"]',
  '["high_lactose"]',
  '["vegetarian","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'falafel',
  'Falafel',
  '[{"name":"chickpeas","quantity":400,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"parsley","quantity":40,"unit":"g"},{"name":"cilantro","quantity":30,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"cumin","quantity":8,"unit":"g"},{"name":"coriander powder","quantity":5,"unit":"g"},{"name":"baking powder","quantity":5,"unit":"g"},{"name":"vegetable oil","quantity":150,"unit":"ml"},{"name":"tahini sauce","quantity":50,"unit":"ml"}]',
  1,
  340,
  14,
  38,
  16,
  8,
  4,
  420,
  '["sesame"]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'chicken shawarma',
  'Chicken Shawarma',
  '[{"name":"chicken thighs","quantity":500,"unit":"g"},{"name":"yogurt","quantity":100,"unit":"g"},{"name":"shawarma spices","quantity":20,"unit":"g"},{"name":"lemon juice","quantity":30,"unit":"ml"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"pita bread","quantity":2,"unit":"pieces"},{"name":"pickled turnips","quantity":40,"unit":"g"},{"name":"garlic sauce","quantity":50,"unit":"ml"},{"name":"tomatoes","quantity":60,"unit":"g"}]',
  1,
  520,
  42,
  35,
  24,
  2,
  4,
  780,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'beef shawarma',
  'Beef Shawarma',
  '[{"name":"beef sirloin","quantity":500,"unit":"g"},{"name":"lamb fat","quantity":50,"unit":"g"},{"name":"shawarma spices","quantity":25,"unit":"g"},{"name":"vinegar","quantity":30,"unit":"ml"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"pita bread","quantity":2,"unit":"pieces"},{"name":"tahini sauce","quantity":50,"unit":"ml"},{"name":"pickles","quantity":40,"unit":"g"},{"name":"parsley","quantity":15,"unit":"g"}]',
  1,
  580,
  45,
  32,
  32,
  2,
  4,
  820,
  '["wheat","sesame"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kafta kebab',
  'Kafta Kebab',
  '[{"name":"ground beef","quantity":400,"unit":"g"},{"name":"ground lamb","quantity":100,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"parsley","quantity":40,"unit":"g"},{"name":"allspice","quantity":5,"unit":"g"},{"name":"cinnamon","quantity":2,"unit":"g"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"black pepper","quantity":2,"unit":"g"},{"name":"olive oil","quantity":20,"unit":"ml"}]',
  1,
  380,
  32,
  6,
  26,
  1,
  2,
  480,
  '[]',
  '["high_fructan"]',
  '["dairy-free","gluten-free","low-carb","keto-friendly"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'shish tawook',
  'Shish Tawook',
  '[{"name":"chicken breast","quantity":500,"unit":"g"},{"name":"yogurt","quantity":150,"unit":"g"},{"name":"lemon juice","quantity":40,"unit":"ml"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"tomato paste","quantity":20,"unit":"g"},{"name":"paprika","quantity":5,"unit":"g"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"garlic sauce","quantity":60,"unit":"ml"}]',
  1,
  380,
  48,
  10,
  16,
  1,
  6,
  520,
  '["milk"]',
  '["high_lactose","high_fructan"]',
  '["gluten-free","low-carb","high-protein"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kibbeh',
  'Kibbeh',
  '[{"name":"bulgur wheat","quantity":150,"unit":"g"},{"name":"ground lamb","quantity":400,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"pine nuts","quantity":40,"unit":"g"},{"name":"allspice","quantity":5,"unit":"g"},{"name":"cinnamon","quantity":3,"unit":"g"},{"name":"cumin","quantity":3,"unit":"g"},{"name":"vegetable oil","quantity":150,"unit":"ml"}]',
  1,
  420,
  26,
  28,
  24,
  4,
  2,
  380,
  '["wheat","tree_nut"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'maqluba',
  'Maqluba',
  '[{"name":"basmati rice","quantity":300,"unit":"g"},{"name":"chicken","quantity":500,"unit":"g"},{"name":"eggplant","quantity":300,"unit":"g"},{"name":"cauliflower","quantity":200,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":100,"unit":"g"},{"name":"allspice","quantity":8,"unit":"g"},{"name":"turmeric","quantity":3,"unit":"g"},{"name":"vegetable oil","quantity":100,"unit":"ml"},{"name":"pine nuts","quantity":30,"unit":"g"}]',
  1,
  580,
  35,
  52,
  28,
  5,
  6,
  520,
  '["tree_nut"]',
  '["high_fructan","high_polyol"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'stuffed grape leaves',
  'Stuffed Grape Leaves',
  '[{"name":"grape leaves","quantity":40,"unit":"leaves"},{"name":"rice","quantity":200,"unit":"g"},{"name":"ground beef","quantity":150,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"tomatoes","quantity":100,"unit":"g"},{"name":"parsley","quantity":30,"unit":"g"},{"name":"mint","quantity":15,"unit":"g"},{"name":"allspice","quantity":5,"unit":"g"},{"name":"lemon juice","quantity":50,"unit":"ml"},{"name":"olive oil","quantity":40,"unit":"ml"}]',
  1,
  280,
  12,
  32,
  12,
  3,
  4,
  420,
  '[]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'mujaddara',
  'Mujaddara',
  '[{"name":"green lentils","quantity":200,"unit":"g"},{"name":"rice","quantity":150,"unit":"g"},{"name":"onion","quantity":300,"unit":"g"},{"name":"olive oil","quantity":80,"unit":"ml"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"coriander powder","quantity":3,"unit":"g"},{"name":"salt","quantity":5,"unit":"g"},{"name":"yogurt","quantity":100,"unit":"g"}]',
  1,
  380,
  14,
  52,
  14,
  10,
  6,
  380,
  '["milk"]',
  '["high_gos","high_fructan"]',
  '["vegetarian","gluten-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'fattoush',
  'Fattoush',
  '[{"name":"romaine lettuce","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":150,"unit":"g"},{"name":"cucumber","quantity":150,"unit":"g"},{"name":"radishes","quantity":80,"unit":"g"},{"name":"pita chips","quantity":60,"unit":"g"},{"name":"sumac","quantity":8,"unit":"g"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"lemon juice","quantity":30,"unit":"ml"},{"name":"mint","quantity":15,"unit":"g"},{"name":"parsley","quantity":20,"unit":"g"}]',
  1,
  220,
  4,
  24,
  12,
  4,
  6,
  280,
  '["wheat"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'tabbouleh',
  'Tabbouleh',
  '[{"name":"bulgur wheat","quantity":60,"unit":"g"},{"name":"parsley","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":150,"unit":"g"},{"name":"mint","quantity":30,"unit":"g"},{"name":"green onion","quantity":40,"unit":"g"},{"name":"lemon juice","quantity":50,"unit":"ml"},{"name":"olive oil","quantity":40,"unit":"ml"},{"name":"salt","quantity":3,"unit":"g"}]',
  1,
  180,
  4,
  22,
  10,
  5,
  3,
  320,
  '["wheat"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'manakish',
  'Manakish',
  '[{"name":"pizza dough","quantity":300,"unit":"g"},{"name":"za''atar","quantity":40,"unit":"g"},{"name":"olive oil","quantity":60,"unit":"ml"},{"name":"sesame seeds","quantity":10,"unit":"g"}]',
  1,
  380,
  10,
  52,
  16,
  4,
  2,
  480,
  '["wheat","sesame"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'fatayer',
  'Fatayer',
  '[{"name":"pizza dough","quantity":300,"unit":"g"},{"name":"spinach","quantity":300,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"sumac","quantity":8,"unit":"g"},{"name":"lemon juice","quantity":20,"unit":"ml"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"pine nuts","quantity":20,"unit":"g"}]',
  1,
  320,
  10,
  42,
  14,
  5,
  3,
  420,
  '["wheat","tree_nut"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'shakshuka',
  'Shakshuka',
  '[{"name":"eggs","quantity":4,"unit":"whole"},{"name":"tomatoes","quantity":400,"unit":"g"},{"name":"bell peppers","quantity":150,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"paprika","quantity":5,"unit":"g"},{"name":"harissa","quantity":15,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"feta cheese","quantity":50,"unit":"g"}]',
  1,
  320,
  18,
  18,
  22,
  4,
  10,
  580,
  '["egg","milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'lentil soup',
  'Lentil Soup',
  '[{"name":"red lentils","quantity":250,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"carrots","quantity":100,"unit":"g"},{"name":"celery","quantity":50,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"},{"name":"cumin","quantity":8,"unit":"g"},{"name":"lemon juice","quantity":30,"unit":"ml"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"vegetable broth","quantity":1000,"unit":"ml"}]',
  1,
  280,
  16,
  42,
  6,
  14,
  6,
  520,
  '[]',
  '["high_gos","high_fructan"]',
  '["vegan","dairy-free","gluten-free","high-fiber","low-fat"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'baklava',
  'Baklava',
  '[{"name":"phyllo dough","quantity":400,"unit":"g"},{"name":"walnuts","quantity":200,"unit":"g"},{"name":"pistachios","quantity":100,"unit":"g"},{"name":"butter","quantity":200,"unit":"g"},{"name":"sugar","quantity":200,"unit":"g"},{"name":"honey","quantity":100,"unit":"g"},{"name":"lemon juice","quantity":20,"unit":"ml"},{"name":"rose water","quantity":10,"unit":"ml"},{"name":"cinnamon","quantity":3,"unit":"g"}]',
  1,
  420,
  6,
  48,
  24,
  2,
  32,
  180,
  '["wheat","milk","tree_nut"]',
  '["high_fructan","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kunafa',
  'Kunafa',
  '[{"name":"kataifi pastry","quantity":400,"unit":"g"},{"name":"mozzarella cheese","quantity":300,"unit":"g"},{"name":"ricotta cheese","quantity":200,"unit":"g"},{"name":"butter","quantity":150,"unit":"g"},{"name":"sugar syrup","quantity":250,"unit":"ml"},{"name":"rose water","quantity":15,"unit":"ml"},{"name":"pistachios","quantity":40,"unit":"g"}]',
  1,
  480,
  14,
  52,
  26,
  1,
  35,
  420,
  '["wheat","milk","tree_nut"]',
  '["high_lactose","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'doner kebab',
  'Döner Kebab',
  '[{"name":"lamb shoulder","quantity":500,"unit":"g"},{"name":"beef fat","quantity":50,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"cumin","quantity":8,"unit":"g"},{"name":"paprika","quantity":5,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"pita bread","quantity":2,"unit":"pieces"},{"name":"tomatoes","quantity":80,"unit":"g"},{"name":"yogurt sauce","quantity":60,"unit":"ml"}]',
  1,
  580,
  38,
  35,
  32,
  2,
  4,
  780,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'adana kebab',
  'Adana Kebab',
  '[{"name":"ground lamb","quantity":400,"unit":"g"},{"name":"lamb fat","quantity":80,"unit":"g"},{"name":"red pepper flakes","quantity":15,"unit":"g"},{"name":"sumac","quantity":5,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"parsley","quantity":20,"unit":"g"},{"name":"bulgur pilaf","quantity":150,"unit":"g"},{"name":"grilled tomatoes","quantity":80,"unit":"g"}]',
  1,
  520,
  32,
  28,
  34,
  4,
  4,
  620,
  '["wheat"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'sis kebab',
  'Şiş Kebab',
  '[{"name":"lamb leg","quantity":400,"unit":"g"},{"name":"bell peppers","quantity":100,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"tomatoes","quantity":80,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"},{"name":"yogurt","quantity":60,"unit":"g"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"rice pilaf","quantity":150,"unit":"g"}]',
  1,
  480,
  35,
  32,
  24,
  3,
  5,
  520,
  '["milk"]',
  '["high_fructan","high_lactose"]',
  '["gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'iskender kebab',
  'İskender Kebab',
  '[{"name":"döner meat","quantity":300,"unit":"g"},{"name":"pide bread","quantity":150,"unit":"g"},{"name":"tomato sauce","quantity":150,"unit":"ml"},{"name":"butter","quantity":50,"unit":"g"},{"name":"yogurt","quantity":150,"unit":"g"},{"name":"garlic","quantity":10,"unit":"g"}]',
  1,
  680,
  42,
  38,
  42,
  2,
  8,
  920,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'kofte',
  'Köfte',
  '[{"name":"ground beef","quantity":400,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"breadcrumbs","quantity":40,"unit":"g"},{"name":"parsley","quantity":20,"unit":"g"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"garlic","quantity":10,"unit":"g"}]',
  1,
  380,
  32,
  12,
  24,
  1,
  2,
  480,
  '["wheat","egg"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'lahmacun',
  'Lahmacun',
  '[{"name":"flatbread dough","quantity":150,"unit":"g"},{"name":"ground lamb","quantity":150,"unit":"g"},{"name":"tomatoes","quantity":100,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"bell peppers","quantity":60,"unit":"g"},{"name":"parsley","quantity":20,"unit":"g"},{"name":"red pepper paste","quantity":20,"unit":"g"},{"name":"lemon","quantity":1,"unit":"wedge"}]',
  1,
  420,
  22,
  42,
  18,
  3,
  5,
  580,
  '["wheat"]',
  '["high_fructan"]',
  '["dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'pide',
  'Pide',
  '[{"name":"pide dough","quantity":200,"unit":"g"},{"name":"ground beef","quantity":150,"unit":"g"},{"name":"cheese","quantity":80,"unit":"g"},{"name":"egg","quantity":1,"unit":"whole"},{"name":"tomatoes","quantity":60,"unit":"g"},{"name":"butter","quantity":20,"unit":"g"}]',
  1,
  520,
  28,
  45,
  26,
  2,
  4,
  680,
  '["wheat","milk","egg"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'borek',
  'Börek',
  '[{"name":"phyllo dough","quantity":300,"unit":"g"},{"name":"feta cheese","quantity":200,"unit":"g"},{"name":"spinach","quantity":200,"unit":"g"},{"name":"egg","quantity":2,"unit":"whole"},{"name":"butter","quantity":80,"unit":"g"},{"name":"parsley","quantity":20,"unit":"g"}]',
  1,
  420,
  16,
  32,
  28,
  3,
  2,
  620,
  '["wheat","milk","egg"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'gozleme',
  'Gözleme',
  '[{"name":"flatbread dough","quantity":200,"unit":"g"},{"name":"feta cheese","quantity":100,"unit":"g"},{"name":"spinach","quantity":150,"unit":"g"},{"name":"potato","quantity":100,"unit":"g"},{"name":"butter","quantity":30,"unit":"g"},{"name":"onion","quantity":50,"unit":"g"}]',
  1,
  380,
  14,
  42,
  18,
  4,
  3,
  520,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'simit',
  'Simit',
  '[{"name":"bread flour","quantity":300,"unit":"g"},{"name":"yeast","quantity":7,"unit":"g"},{"name":"molasses","quantity":30,"unit":"ml"},{"name":"sesame seeds","quantity":60,"unit":"g"},{"name":"salt","quantity":5,"unit":"g"}]',
  1,
  320,
  10,
  52,
  8,
  3,
  6,
  380,
  '["wheat","sesame"]',
  '["high_fructan"]',
  '["vegan","dairy-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'mercimek corbas',
  'Mercimek Çorbası',
  '[{"name":"red lentils","quantity":200,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"carrots","quantity":80,"unit":"g"},{"name":"potato","quantity":100,"unit":"g"},{"name":"tomato paste","quantity":20,"unit":"g"},{"name":"cumin","quantity":5,"unit":"g"},{"name":"butter","quantity":30,"unit":"g"},{"name":"lemon","quantity":1,"unit":"wedge"}]',
  1,
  280,
  14,
  42,
  8,
  12,
  6,
  420,
  '["milk"]',
  '["high_gos","high_fructan"]',
  '["vegetarian","gluten-free","high-fiber"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'ezme salad',
  'Ezme Salad',
  '[{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"bell peppers","quantity":80,"unit":"g"},{"name":"parsley","quantity":30,"unit":"g"},{"name":"red pepper paste","quantity":20,"unit":"g"},{"name":"pomegranate molasses","quantity":15,"unit":"ml"},{"name":"olive oil","quantity":30,"unit":"ml"}]',
  1,
  150,
  3,
  16,
  10,
  4,
  10,
  280,
  '[]',
  '["high_fructan"]',
  '["vegan","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'menemen',
  'Menemen',
  '[{"name":"eggs","quantity":3,"unit":"whole"},{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"bell peppers","quantity":100,"unit":"g"},{"name":"onion","quantity":60,"unit":"g"},{"name":"butter","quantity":30,"unit":"g"},{"name":"green chilies","quantity":20,"unit":"g"}]',
  1,
  320,
  18,
  14,
  22,
  3,
  8,
  420,
  '["egg","milk"]',
  '["high_fructan"]',
  '["vegetarian","gluten-free","low-carb"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'cig kofte',
  'Çiğ Köfte',
  '[{"name":"bulgur","quantity":200,"unit":"g"},{"name":"tomato paste","quantity":40,"unit":"g"},{"name":"red pepper paste","quantity":40,"unit":"g"},{"name":"onion","quantity":100,"unit":"g"},{"name":"parsley","quantity":30,"unit":"g"},{"name":"green onion","quantity":30,"unit":"g"},{"name":"pomegranate molasses","quantity":20,"unit":"ml"},{"name":"cumin","quantity":5,"unit":"g"}]',
  1,
  280,
  8,
  52,
  4,
  8,
  8,
  380,
  '["wheat"]',
  '["high_fructan"]',
  '["vegan","dairy-free","low-fat"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'mant',
  'Mantı',
  '[{"name":"flour","quantity":250,"unit":"g"},{"name":"ground beef","quantity":200,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"yogurt","quantity":200,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"butter","quantity":40,"unit":"g"},{"name":"paprika","quantity":5,"unit":"g"},{"name":"dried mint","quantity":5,"unit":"g"}]',
  1,
  520,
  26,
  48,
  26,
  2,
  6,
  580,
  '["wheat","milk"]',
  '["high_fructan","high_lactose"]',
  '[]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'imam bay ld',
  'İmam Bayıldı',
  '[{"name":"eggplant","quantity":400,"unit":"g"},{"name":"tomatoes","quantity":200,"unit":"g"},{"name":"onion","quantity":150,"unit":"g"},{"name":"garlic","quantity":15,"unit":"g"},{"name":"bell peppers","quantity":80,"unit":"g"},{"name":"olive oil","quantity":80,"unit":"ml"},{"name":"parsley","quantity":20,"unit":"g"}]',
  1,
  280,
  4,
  22,
  20,
  8,
  14,
  280,
  '[]',
  '["high_fructan","high_polyol"]',
  '["vegan","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'turkish stuffed peppers',
  'Turkish Stuffed Peppers',
  '[{"name":"bell peppers","quantity":400,"unit":"g"},{"name":"rice","quantity":150,"unit":"g"},{"name":"ground beef","quantity":200,"unit":"g"},{"name":"tomatoes","quantity":100,"unit":"g"},{"name":"onion","quantity":80,"unit":"g"},{"name":"parsley","quantity":20,"unit":"g"},{"name":"mint","quantity":10,"unit":"g"},{"name":"olive oil","quantity":30,"unit":"ml"}]',
  1,
  380,
  20,
  38,
  18,
  4,
  8,
  420,
  '[]',
  '["high_fructan"]',
  '["dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'turkish baklava',
  'Turkish Baklava',
  '[{"name":"phyllo dough","quantity":400,"unit":"g"},{"name":"pistachios","quantity":250,"unit":"g"},{"name":"butter","quantity":200,"unit":"g"},{"name":"sugar","quantity":250,"unit":"g"},{"name":"lemon juice","quantity":20,"unit":"ml"}]',
  1,
  450,
  8,
  52,
  26,
  2,
  36,
  180,
  '["wheat","milk","tree_nut"]',
  '["high_fructan","high_fructose"]',
  '["vegetarian"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');

INSERT INTO cached_recipes (
  dish_name_normalized, dish_name_display, ingredients_json, servings,
  calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
  allergen_flags_json, fodmap_flags_json, diet_tags_json,
  source, confidence
) VALUES (
  'turkish delight',
  'Turkish Delight',
  '[{"name":"sugar","quantity":400,"unit":"g"},{"name":"cornstarch","quantity":100,"unit":"g"},{"name":"cream of tartar","quantity":3,"unit":"g"},{"name":"rose water","quantity":20,"unit":"ml"},{"name":"pistachios","quantity":60,"unit":"g"}]',
  1,
  280,
  2,
  68,
  4,
  1,
  58,
  20,
  '["tree_nut"]',
  '["high_fructose"]',
  '["vegan","dairy-free","gluten-free"]',
  'curated',
  0.95
) ON CONFLICT(dish_name_normalized) DO UPDATE SET
  ingredients_json = excluded.ingredients_json,
  calories_kcal = excluded.calories_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  allergen_flags_json = excluded.allergen_flags_json,
  fodmap_flags_json = excluded.fodmap_flags_json,
  diet_tags_json = excluded.diet_tags_json,
  updated_at = datetime('now');
